/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_ACC_Time_Gap_ID_44268_h
#define __HEADER_ACC_Time_Gap_ID_44268_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int TimeChange_ID_44290;

extern GEN_TYPE_boolean noval_TimeChange_ID_44290;

extern GEN_TYPE_double LastTimeGap_ID_44285;

extern GEN_TYPE_boolean noval_LastTimeGap_ID_44285;

extern GEN_TYPE_double TimeGap_ID_44677;

extern GEN_TYPE_boolean noval_TimeGap_ID_44677;

extern void clear_inputs_ACC_Time_Gap_ID_44268();

extern void clear_outputs_ACC_Time_Gap_ID_44268();

extern void init_ACC_Time_Gap_ID_44268();

extern void perform_step_ACC_Time_Gap_ID_44268();

#endif // __HEADER_ACC_Time_Gap_ID_44268_h
