/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Adaptive_Cruise_Control_ID_8419_h
#define __HEADER_Adaptive_Cruise_Control_ID_8419_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceEvents DACommand_ID_8445;

extern GEN_TYPE_boolean noval_DACommand_ID_8445;

extern GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_10398;

extern GEN_TYPE_boolean noval_DA_TurnOff_ID_10398;

extern GEN_TYPE_On_Off_States acc_ID_8459;

extern GEN_TYPE_boolean noval_acc_ID_8459;

extern void clear_inputs_Adaptive_Cruise_Control_ID_8419();

extern void clear_outputs_Adaptive_Cruise_Control_ID_8419();

extern void init_Adaptive_Cruise_Control_ID_8419();

extern void perform_step_Adaptive_Cruise_Control_ID_8419();

#endif // __HEADER_Adaptive_Cruise_Control_ID_8419_h
