/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Automatic_ID_12164_h
#define __HEADER_Automatic_ID_12164_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int GearShift_ID_11455;

extern GEN_TYPE_boolean noval_GearShift_ID_11455;

extern GEN_TYPE_double GasPedal_ID_11450;

extern GEN_TYPE_boolean noval_GasPedal_ID_11450;

extern GEN_TYPE_double Velocity_ID_11476;

extern GEN_TYPE_boolean noval_Velocity_ID_11476;

extern GEN_TYPE_double Throttle_ID_11458;

extern GEN_TYPE_boolean noval_Throttle_ID_11458;

extern GEN_TYPE_int Gear_ID_12696;

extern GEN_TYPE_boolean noval_Gear_ID_12696;

extern void clear_inputs_Automatic_ID_12164();

extern void clear_outputs_Automatic_ID_12164();

extern void init_Automatic_ID_12164();

extern void perform_step_Automatic_ID_12164();

#endif // __HEADER_Automatic_ID_12164_h
