/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_BlinkLeft_ID_19399_h
#define __HEADER_BlinkLeft_ID_19399_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean EnableLeftSignal_ID_19496;

extern GEN_TYPE_boolean noval_EnableLeftSignal_ID_19496;

extern GEN_TYPE_int CountTickInLeft_ID_19526;

extern GEN_TYPE_boolean noval_CountTickInLeft_ID_19526;

extern GEN_TYPE_int CountTickOutLeft_ID_19524;

extern GEN_TYPE_boolean noval_CountTickOutLeft_ID_19524;

extern GEN_TYPE_RGBColor BlinkLeft_ID_19537;

extern GEN_TYPE_boolean noval_BlinkLeft_ID_19537;

extern void clear_inputs_BlinkLeft_ID_19399();

extern void clear_outputs_BlinkLeft_ID_19399();

extern void init_BlinkLeft_ID_19399();

extern void perform_step_BlinkLeft_ID_19399();

#endif // __HEADER_BlinkLeft_ID_19399_h
