/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Boundaries_ID_16309_h
#define __HEADER_Boundaries_ID_16309_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double SteeringAngleRegulated_In_ID_16318;

extern GEN_TYPE_boolean noval_SteeringAngleRegulated_In_ID_16318;

extern GEN_TYPE_double SteeringAngleRegulated_ID_16323;

extern GEN_TYPE_boolean noval_SteeringAngleRegulated_ID_16323;

extern GEN_TYPE_boolean BoundariesActive_ID_16345;

extern GEN_TYPE_boolean noval_BoundariesActive_ID_16345;

extern void clear_inputs_Boundaries_ID_16309();

extern void clear_outputs_Boundaries_ID_16309();

extern void init_Boundaries_ID_16309();

extern void perform_step_Boundaries_ID_16309();

#endif // __HEADER_Boundaries_ID_16309_h
