/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Deadzone_check_ID_7080_h
#define __HEADER_Deadzone_check_ID_7080_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetVelocity_ID_19712;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_19712;

extern GEN_TYPE_double OutputValue_ID_7186;

extern GEN_TYPE_boolean noval_OutputValue_ID_7186;

extern void clear_inputs_Deadzone_check_ID_7080();

extern void clear_outputs_Deadzone_check_ID_7080();

extern void init_Deadzone_check_ID_7080();

extern void perform_step_Deadzone_check_ID_7080();

#endif // __HEADER_Deadzone_check_ID_7080_h
