/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Delay_ID_13898_h
#define __HEADER_Delay_ID_13898_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAccelerationEB_ID_29303;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29303;

extern GEN_TYPE_boolean EB_On_ID_14053;

extern GEN_TYPE_boolean noval_EB_On_ID_14053;

extern void clear_inputs_Delay_ID_13898();

extern void clear_outputs_Delay_ID_13898();

extern void init_Delay_ID_13898();

extern void perform_step_Delay_ID_13898();

#endif // __HEADER_Delay_ID_13898_h
