/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Distance_Transformation_ID_16635_h
#define __HEADER_Distance_Transformation_ID_16635_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double DistanceToFrontLaser_ID_16644;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_16644;

extern GEN_TYPE_double DistanceToFrontUS1_ID_16651;

extern GEN_TYPE_boolean noval_DistanceToFrontUS1_ID_16651;

extern GEN_TYPE_double DistanceToFrontUS2_ID_16726;

extern GEN_TYPE_boolean noval_DistanceToFrontUS2_ID_16726;

extern GEN_TYPE_double DistanceToFrontLaser_Out_ID_32217;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_Out_ID_32217;

extern GEN_TYPE_double DistanceToFrontUS_Out1_ID_32224;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_Out1_ID_32224;

extern GEN_TYPE_double DistanceToFrontUS_Out2_ID_32231;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_Out2_ID_32231;

extern void clear_inputs_Distance_Transformation_ID_16635();

extern void clear_outputs_Distance_Transformation_ID_16635();

extern void init_Distance_Transformation_ID_16635();

extern void perform_step_Distance_Transformation_ID_16635();

#endif // __HEADER_Distance_Transformation_ID_16635_h
