/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_DPadLeft_ID_18705_h
#define __HEADER_DPadLeft_ID_18705_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int DPadLeftIn_ID_32537;

extern GEN_TYPE_boolean noval_DPadLeftIn_ID_32537;

extern GEN_TYPE_KeyEvent DPadLeftOut_ID_32510;

extern GEN_TYPE_boolean noval_DPadLeftOut_ID_32510;

extern void clear_inputs_DPadLeft_ID_18705();

extern void clear_outputs_DPadLeft_ID_18705();

extern void init_DPadLeft_ID_18705();

extern void perform_step_DPadLeft_ID_18705();

#endif // __HEADER_DPadLeft_ID_18705_h
