/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_DrivingMode_ID_5723_h
#define __HEADER_DrivingMode_ID_5723_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriveModeSettings DriveMode_ID_12240;

extern GEN_TYPE_boolean noval_DriveMode_ID_12240;

extern GEN_TYPE_double GasPedalIn_ID_12230;

extern GEN_TYPE_boolean noval_GasPedalIn_ID_12230;

extern GEN_TYPE_int GearShiftIn_ID_12225;

extern GEN_TYPE_boolean noval_GearShiftIn_ID_12225;

extern GEN_TYPE_DriveMode StateOld_ID_12596;

extern GEN_TYPE_boolean noval_StateOld_ID_12596;

extern GEN_TYPE_double GasPedalOut_ID_11448;

extern GEN_TYPE_boolean noval_GasPedalOut_ID_11448;

extern GEN_TYPE_int GearShiftOut_ID_11453;

extern GEN_TYPE_boolean noval_GearShiftOut_ID_11453;

extern GEN_TYPE_DriveMode StateNew_ID_12585;

extern GEN_TYPE_boolean noval_StateNew_ID_12585;

extern void clear_inputs_DrivingMode_ID_5723();

extern void clear_outputs_DrivingMode_ID_5723();

extern void init_DrivingMode_ID_5723();

extern void perform_step_DrivingMode_ID_5723();

#endif // __HEADER_DrivingMode_ID_5723_h
