/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_EBRumble_ID_17138_h
#define __HEADER_EBRumble_ID_17138_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean RumbleEB_ID_17206;

extern GEN_TYPE_boolean noval_RumbleEB_ID_17206;

extern GEN_TYPE_boolean ForceEBOff_ID_17754;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_17754;

extern GEN_TYPE_int RumbleEB_In_ID_17209;

extern GEN_TYPE_boolean noval_RumbleEB_In_ID_17209;

extern void clear_inputs_EBRumble_ID_17138();

extern void clear_outputs_EBRumble_ID_17138();

extern void init_EBRumble_ID_17138();

extern void perform_step_EBRumble_ID_17138();

#endif // __HEADER_EBRumble_ID_17138_h
