/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_I_term_ID_16014_h
#define __HEADER_I_term_ID_16014_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Error_ID_16073;

extern GEN_TYPE_boolean noval_Error_ID_16073;

extern GEN_TYPE_double ErrorSumIn_ID_16119;

extern GEN_TYPE_boolean noval_ErrorSumIn_ID_16119;

extern GEN_TYPE_boolean BoundariesActive_ID_16354;

extern GEN_TYPE_boolean noval_BoundariesActive_ID_16354;

extern GEN_TYPE_double Coef_I_ID_16037;

extern GEN_TYPE_boolean noval_Coef_I_ID_16037;

extern GEN_TYPE_double ErrorSumOut_ID_16108;

extern GEN_TYPE_boolean noval_ErrorSumOut_ID_16108;

extern void clear_inputs_I_term_ID_16014();

extern void clear_outputs_I_term_ID_16014();

extern void init_I_term_ID_16014();

extern void perform_step_I_term_ID_16014();

#endif // __HEADER_I_term_ID_16014_h
