/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Lane_Keeping_ID_8424_h
#define __HEADER_Lane_Keeping_ID_8424_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceEvents DACommand_ID_8452;

extern GEN_TYPE_boolean noval_DACommand_ID_8452;

extern GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_10393;

extern GEN_TYPE_boolean noval_DA_TurnOff_ID_10393;

extern GEN_TYPE_On_Off_States laneKeep_ID_8468;

extern GEN_TYPE_boolean noval_laneKeep_ID_8468;

extern void clear_inputs_Lane_Keeping_ID_8424();

extern void clear_outputs_Lane_Keeping_ID_8424();

extern void init_Lane_Keeping_ID_8424();

extern void perform_step_Lane_Keeping_ID_8424();

#endif // __HEADER_Lane_Keeping_ID_8424_h
