/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Lane_Keeping_Rumble_ID_30647_h
#define __HEADER_Lane_Keeping_Rumble_ID_30647_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean RumbleLK_ID_30655;

extern GEN_TYPE_boolean noval_RumbleLK_ID_30655;

extern GEN_TYPE_int RumbleLK_Out_ID_30657;

extern GEN_TYPE_boolean noval_RumbleLK_Out_ID_30657;

extern void clear_inputs_Lane_Keeping_Rumble_ID_30647();

extern void clear_outputs_Lane_Keeping_Rumble_ID_30647();

extern void init_Lane_Keeping_Rumble_ID_30647();

extern void perform_step_Lane_Keeping_Rumble_ID_30647();

#endif // __HEADER_Lane_Keeping_Rumble_ID_30647_h
