/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_LK_Coordinator_ID_15951_h
#define __HEADER_LK_Coordinator_ID_15951_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int SteeringCommand_ID_15969;

extern GEN_TYPE_boolean noval_SteeringCommand_ID_15969;

extern GEN_TYPE_double SteeringAngleRegulated_ID_15978;

extern GEN_TYPE_boolean noval_SteeringAngleRegulated_ID_15978;

extern GEN_TYPE_double Velocity_ID_44989;

extern GEN_TYPE_boolean noval_Velocity_ID_44989;

extern GEN_TYPE_double LastSteeringAngle_ID_45010;

extern GEN_TYPE_boolean noval_LastSteeringAngle_ID_45010;

extern GEN_TYPE_double SteeringAngle_ID_44999;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_44999;

extern void clear_inputs_LK_Coordinator_ID_15951();

extern void clear_outputs_LK_Coordinator_ID_15951();

extern void init_LK_Coordinator_ID_15951();

extern void perform_step_LK_Coordinator_ID_15951();

#endif // __HEADER_LK_Coordinator_ID_15951_h
