/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Max_ACC_Velocity_ID_8163_h
#define __HEADER_Max_ACC_Velocity_ID_8163_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int SpeedChange_ID_44191;

extern GEN_TYPE_boolean noval_SpeedChange_ID_44191;

extern GEN_TYPE_double LastMaxVelocity_ID_44207;

extern GEN_TYPE_boolean noval_LastMaxVelocity_ID_44207;

extern GEN_TYPE_double MaxVelocity_ID_44684;

extern GEN_TYPE_boolean noval_MaxVelocity_ID_44684;

extern void clear_inputs_Max_ACC_Velocity_ID_8163();

extern void clear_outputs_Max_ACC_Velocity_ID_8163();

extern void init_Max_ACC_Velocity_ID_8163();

extern void perform_step_Max_ACC_Velocity_ID_8163();

#endif // __HEADER_Max_ACC_Velocity_ID_8163_h
