/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_MaxAccel_Decel_ID_44530_h
#define __HEADER_MaxAccel_Decel_ID_44530_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetVelocityOut_ID_44539;

extern GEN_TYPE_boolean noval_TargetVelocityOut_ID_44539;

extern GEN_TYPE_double Velocity_ID_44561;

extern GEN_TYPE_boolean noval_Velocity_ID_44561;

extern GEN_TYPE_double TargetVelocity_ID_44544;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_44544;

extern GEN_TYPE_double MaxAcceleration_ID_44551;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_44551;

extern void clear_inputs_MaxAccel_Decel_ID_44530();

extern void clear_outputs_MaxAccel_Decel_ID_44530();

extern void init_MaxAccel_Decel_ID_44530();

extern void perform_step_MaxAccel_Decel_ID_44530();

#endif // __HEADER_MaxAccel_Decel_ID_44530_h
