/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Min_ID_16760_h
#define __HEADER_Min_ID_16760_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double DistanceToFrontUS_1_ID_32194;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_1_ID_32194;

extern GEN_TYPE_double DistanceToFrontUS_2_ID_32212;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_2_ID_32212;

extern GEN_TYPE_double DistanceToFrontUS_Out_ID_24616;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_Out_ID_24616;

extern void clear_inputs_Min_ID_16760();

extern void clear_outputs_Min_ID_16760();

extern void init_Min_ID_16760();

extern void perform_step_Min_ID_16760();

#endif // __HEADER_Min_ID_16760_h
