/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Preliminary_DriveMode_ID_13768_h
#define __HEADER_Preliminary_DriveMode_ID_13768_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Velocity_ID_13874;

extern GEN_TYPE_boolean noval_Velocity_ID_13874;

extern GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13895;

extern GEN_TYPE_boolean noval_DriveModeCommands_ID_13895;

extern GEN_TYPE_boolean EB_On_ID_13916;

extern GEN_TYPE_boolean noval_EB_On_ID_13916;

extern GEN_TYPE_boolean ForceEBOff_ID_29323;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_29323;

extern GEN_TYPE_int DriveMode_ID_13826;

extern GEN_TYPE_boolean noval_DriveMode_ID_13826;

extern void clear_inputs_Preliminary_DriveMode_ID_13768();

extern void clear_outputs_Preliminary_DriveMode_ID_13768();

extern void init_Preliminary_DriveMode_ID_13768();

extern void perform_step_Preliminary_DriveMode_ID_13768();

#endif // __HEADER_Preliminary_DriveMode_ID_13768_h
