/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_R1_ID_13581_h
#define __HEADER_R1_ID_13581_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int In_ID_13606;

extern GEN_TYPE_boolean noval_In_ID_13606;

extern GEN_TYPE_int Out_ID_13604;

extern GEN_TYPE_boolean noval_Out_ID_13604;

extern void clear_inputs_R1_ID_13581();

extern void clear_outputs_R1_ID_13581();

extern void init_R1_ID_13581();

extern void perform_step_R1_ID_13581();

#endif // __HEADER_R1_ID_13581_h
