/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Ranges_ID_32178_h
#define __HEADER_Ranges_ID_32178_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double DistanceToFrontLaser_Out_ID_32219;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_Out_ID_32219;

extern GEN_TYPE_double DistanceToFrontUS_Out1_ID_32226;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_Out1_ID_32226;

extern GEN_TYPE_double DistanceToFrontUS_Out2_ID_32233;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_Out2_ID_32233;

extern GEN_TYPE_double DistanceToFrontLaser_In_ID_44740;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_In_ID_44740;

extern GEN_TYPE_double DistanceToFrontUS_1_ID_44335;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_1_ID_44335;

extern GEN_TYPE_double DistanceToFrontUS_2_ID_44342;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_2_ID_44342;

extern void clear_inputs_Ranges_ID_32178();

extern void clear_outputs_Ranges_ID_32178();

extern void init_Ranges_ID_32178();

extern void perform_step_Ranges_ID_32178();

#endif // __HEADER_Ranges_ID_32178_h
