/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Select_ID_13469_h
#define __HEADER_Select_ID_13469_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonSelectIn_ID_32552;

extern GEN_TYPE_boolean noval_ButtonSelectIn_ID_32552;

extern GEN_TYPE_KeyEvent ButtonSelectOut_ID_32495;

extern GEN_TYPE_boolean noval_ButtonSelectOut_ID_32495;

extern void clear_inputs_Select_ID_13469();

extern void clear_outputs_Select_ID_13469();

extern void init_Select_ID_13469();

extern void perform_step_Select_ID_13469();

#endif // __HEADER_Select_ID_13469_h
