/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Sum_ID_15989_h
#define __HEADER_Sum_ID_15989_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Coef_P_ID_16030;

extern GEN_TYPE_boolean noval_Coef_P_ID_16030;

extern GEN_TYPE_double Coef_I_ID_16039;

extern GEN_TYPE_boolean noval_Coef_I_ID_16039;

extern GEN_TYPE_double Coef_D_ID_16048;

extern GEN_TYPE_boolean noval_Coef_D_ID_16048;

extern GEN_TYPE_double Steering_FeedForward_ID_31436;

extern GEN_TYPE_boolean noval_Steering_FeedForward_ID_31436;

extern GEN_TYPE_double SteeringAngleRegulated_ID_16316;

extern GEN_TYPE_boolean noval_SteeringAngleRegulated_ID_16316;

extern void clear_inputs_Sum_ID_15989();

extern void clear_outputs_Sum_ID_15989();

extern void init_Sum_ID_15989();

extern void perform_step_Sum_ID_15989();

#endif // __HEADER_Sum_ID_15989_h
