/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_SumUpControl_ID_24113_h
#define __HEADER_SumUpControl_ID_24113_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_AD_Commands platooning_ID_24126;

extern GEN_TYPE_boolean noval_platooning_ID_24126;

extern GEN_TYPE_boolean fuseIn_ID_27245;

extern GEN_TYPE_boolean noval_fuseIn_ID_27245;

extern GEN_TYPE_boolean splitIn_ID_27254;

extern GEN_TYPE_boolean noval_splitIn_ID_27254;

extern GEN_TYPE_ADOnOffCommands Control_AD_ID_24135;

extern GEN_TYPE_boolean noval_Control_AD_ID_24135;

extern GEN_TYPE_int HERETOCHECK_ID_24150;

extern GEN_TYPE_boolean noval_HERETOCHECK_ID_24150;

extern void clear_inputs_SumUpControl_ID_24113();

extern void clear_outputs_SumUpControl_ID_24113();

extern void init_SumUpControl_ID_24113();

extern void perform_step_SumUpControl_ID_24113();

#endif // __HEADER_SumUpControl_ID_24113_h
