/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_TargetVelocity_ID_10210_h
#define __HEADER_TargetVelocity_ID_10210_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxVelocity_ID_10230;

extern GEN_TYPE_boolean noval_MaxVelocity_ID_10230;

extern GEN_TYPE_double TargetVelocityIn_ID_16462;

extern GEN_TYPE_boolean noval_TargetVelocityIn_ID_16462;

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_45628;

extern GEN_TYPE_boolean noval_DA_States_ID_45628;

extern GEN_TYPE_double TargetVelocityOut_ID_44537;

extern GEN_TYPE_boolean noval_TargetVelocityOut_ID_44537;

extern void clear_inputs_TargetVelocity_ID_10210();

extern void clear_outputs_TargetVelocity_ID_10210();

extern void init_TargetVelocity_ID_10210();

extern void perform_step_TargetVelocity_ID_10210();

#endif // __HEADER_TargetVelocity_ID_10210_h
