/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_VelocityMem_ID_11087_h
#define __HEADER_VelocityMem_ID_11087_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityIn_ID_12245;

extern GEN_TYPE_boolean noval_VelocityIn_ID_12245;

extern GEN_TYPE_double LoopIn_ID_12220;

extern GEN_TYPE_boolean noval_LoopIn_ID_12220;

extern GEN_TYPE_double LoopOut_ID_12218;

extern GEN_TYPE_boolean noval_LoopOut_ID_12218;

extern GEN_TYPE_double VelocityOut_ID_11474;

extern GEN_TYPE_boolean noval_VelocityOut_ID_11474;

extern void clear_inputs_VelocityMem_ID_11087();

extern void clear_outputs_VelocityMem_ID_11087();

extern void init_VelocityMem_ID_11087();

extern void perform_step_VelocityMem_ID_11087();

#endif // __HEADER_VelocityMem_ID_11087_h
