/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Velocity_of_Obstacle_in_front_ID_6981_h
#define __HEADER_Velocity_of_Obstacle_in_front_ID_6981_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityDiff_ID_7693;

extern GEN_TYPE_boolean noval_VelocityDiff_ID_7693;

extern GEN_TYPE_double Velocity_ID_8817;

extern GEN_TYPE_boolean noval_Velocity_ID_8817;

extern GEN_TYPE_double LastVelocityIn_ID_7749;

extern GEN_TYPE_boolean noval_LastVelocityIn_ID_7749;

extern GEN_TYPE_boolean InvalidValue_ID_7762;

extern GEN_TYPE_boolean noval_InvalidValue_ID_7762;

extern GEN_TYPE_double VelocityFrontObstacle_ID_44668;

extern GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_44668;

extern GEN_TYPE_double LastVelocityOut_ID_7738;

extern GEN_TYPE_boolean noval_LastVelocityOut_ID_7738;

extern void clear_inputs_Velocity_of_Obstacle_in_front_ID_6981();

extern void clear_outputs_Velocity_of_Obstacle_in_front_ID_6981();

extern void init_Velocity_of_Obstacle_in_front_ID_6981();

extern void perform_step_Velocity_of_Obstacle_in_front_ID_6981();

#endif // __HEADER_Velocity_of_Obstacle_in_front_ID_6981_h
