/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#ifndef __HEADER_Weight_Current_ID_73_h
#define __HEADER_Weight_Current_ID_73_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Weight_Current_ID_45027;

extern GEN_TYPE_boolean noval_Weight_Current_ID_45027;

extern void clear_inputs_Weight_Current_ID_73();

extern void clear_outputs_Weight_Current_ID_73();

extern void init_Weight_Current_ID_73();

extern void perform_step_Weight_Current_ID_73();

#endif // __HEADER_Weight_Current_ID_73_h
