/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/ACC_Error_ID_44576.h"

GEN_TYPE_double TargetDistance_ID_44585;

GEN_TYPE_boolean noval_TargetDistance_ID_44585;

GEN_TYPE_double DistanceFront_ID_44592;

GEN_TYPE_boolean noval_DistanceFront_ID_44592;

GEN_TYPE_double Error_ID_44634;

GEN_TYPE_boolean noval_Error_ID_44634;

void clear_inputs_ACC_Error_ID_44576(){
	noval_TargetDistance_ID_44585 = true;
	noval_DistanceFront_ID_44592 = true;
}

void clear_outputs_ACC_Error_ID_44576(){
	noval_Error_ID_44634 = true;
}

void init_ACC_Error_ID_44576(){
	noval_Error_ID_44634 = true;
}

void perform_step_ACC_Error_ID_44576(){
	clear_outputs_ACC_Error_ID_44576();
	if (!(noval_DistanceFront_ID_44592 == true) && !(noval_TargetDistance_ID_44585 == true)) {
		noval_Error_ID_44634 = false;
		Error_ID_44634 = DistanceFront_ID_44592 - TargetDistance_ID_44585;
		
	}
	else {
		noval_Error_ID_44634 = false;
		Error_ID_44634 = 0.0;
		
	}
	return;
	
}
