/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Automatic_ID_12164.h"

GEN_TYPE_int GearShift_ID_11455;

GEN_TYPE_boolean noval_GearShift_ID_11455;

GEN_TYPE_double GasPedal_ID_11450;

GEN_TYPE_boolean noval_GasPedal_ID_11450;

GEN_TYPE_double Velocity_ID_11476;

GEN_TYPE_boolean noval_Velocity_ID_11476;

GEN_TYPE_double Throttle_ID_11458;

GEN_TYPE_boolean noval_Throttle_ID_11458;

GEN_TYPE_int Gear_ID_12696;

GEN_TYPE_boolean noval_Gear_ID_12696;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11397();

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11400();

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11403();

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11406();

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11409();

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11412();

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11415();

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11418();

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11421();

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11424();

static GEN_TYPE_boolean fire_transition_reset_ID_11427();

static GEN_TYPE_boolean fire_transition_reset_ID_11430();

static GEN_TYPE_boolean fire_transition_reset_ID_11433();

static GEN_TYPE_boolean fire_transition_reset_ID_11436();

static GEN_TYPE_boolean fire_transition_reset_ID_11439();

static GEN_TYPE_boolean fire_state_Gear1_ID_12171();

static GEN_TYPE_boolean fire_state_Gear2_ID_12181();

static GEN_TYPE_boolean fire_state_Gear3_ID_11361();

static GEN_TYPE_boolean fire_state_Gear4_ID_12193();

static GEN_TYPE_boolean fire_state_Gear5_ID_12202();

static GEN_TYPE_boolean fire_state_Gear6_ID_11388();

void clear_inputs_Automatic_ID_12164(){
	noval_GearShift_ID_11455 = true;
	noval_GasPedal_ID_11450 = true;
	noval_Velocity_ID_11476 = true;
}

void clear_outputs_Automatic_ID_12164(){
	noval_Throttle_ID_11458 = true;
	noval_Gear_ID_12696 = true;
}

void init_Automatic_ID_12164(){
	noval_Throttle_ID_11458 = true;
	noval_Gear_ID_12696 = true;
	current_state = 12171;
}

void perform_step_Automatic_ID_12164(){
	clear_outputs_Automatic_ID_12164();
	if (current_state == 11388) {
		fire_state_Gear6_ID_11388();
	}
	else {
		if (current_state == 12202) {
			fire_state_Gear5_ID_12202();
		}
		else {
			if (current_state == 12193) {
				fire_state_Gear4_ID_12193();
			}
			else {
				if (current_state == 11361) {
					fire_state_Gear3_ID_11361();
				}
				else {
					if (current_state == 12181) {
						fire_state_Gear2_ID_12181();
					}
					else {
						if (current_state == 12171) {
							fire_state_Gear1_ID_12171();
						}
					}
				}
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11397(){
	if ((!(noval_Velocity_ID_11476 == true) && Velocity_ID_11476 >= 0) && (GasPedal_ID_11450 >= 0.8 && Velocity_ID_11476 / MAX_SPEED() >= gear1(0.7))) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear2(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 2;
		
		current_state = 12181;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11400(){
	if (GasPedal_ID_11450 <= 0.3 && Velocity_ID_11476 / MAX_SPEED() <= gear2(0.4) || Velocity_ID_11476 / MAX_SPEED() <= gear2(0.2)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11403(){
	if (GasPedal_ID_11450 >= 0.8 && Velocity_ID_11476 / MAX_SPEED() >= gear2(0.7)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear3(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 3;
		
		current_state = 11361;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11406(){
	if (GasPedal_ID_11450 <= 0.3 && Velocity_ID_11476 / MAX_SPEED() <= gear3(0.4) || Velocity_ID_11476 / MAX_SPEED() <= gear3(0.2)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear2(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 2;
		
		current_state = 12181;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11409(){
	if (GasPedal_ID_11450 >= 0.8 && Velocity_ID_11476 / MAX_SPEED() >= gear3(0.7)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear4(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 4;
		
		current_state = 12193;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11412(){
	if (GasPedal_ID_11450 <= 0.3 && Velocity_ID_11476 / MAX_SPEED() <= gear4(0.4) || Velocity_ID_11476 / MAX_SPEED() <= gear4(0.2)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear3(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 3;
		
		current_state = 11361;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11415(){
	if (GasPedal_ID_11450 >= 0.8 && Velocity_ID_11476 / MAX_SPEED() >= gear4(0.7)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear5(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 5;
		
		current_state = 12202;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11418(){
	if (GasPedal_ID_11450 <= 0.3 && Velocity_ID_11476 / MAX_SPEED() <= gear5(0.4) || Velocity_ID_11476 / MAX_SPEED() <= gear5(0.2)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear4(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 4;
		
		current_state = 12193;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftUp_ID_11421(){
	if (GasPedal_ID_11450 >= 0.8 && Velocity_ID_11476 / MAX_SPEED() >= gear5(0.7)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear6(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 6;
		
		current_state = 11388;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_shiftDown_ID_11424(){
	if (GasPedal_ID_11450 <= 0.3 && Velocity_ID_11476 / MAX_SPEED() <= gear6(0.4) || Velocity_ID_11476 / MAX_SPEED() <= gear6(0.2)) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear5(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 5;
		
		current_state = 12202;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_reset_ID_11427(){
	if (noval_GearShift_ID_11455 == false && GearShift_ID_11455 == 0) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_reset_ID_11430(){
	if (noval_GearShift_ID_11455 == false && GearShift_ID_11455 == 0) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_reset_ID_11433(){
	if (noval_GearShift_ID_11455 == false && GearShift_ID_11455 == 0) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_reset_ID_11436(){
	if (noval_GearShift_ID_11455 == false && GearShift_ID_11455 == 0) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_reset_ID_11439(){
	if (noval_GearShift_ID_11455 == false && GearShift_ID_11455 == 0) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
		current_state = 12171;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Gear1_ID_12171(){
	if (!fire_transition_shiftUp_ID_11397()) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear1(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 1;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Gear2_ID_12181(){
	if (!(fire_transition_shiftDown_ID_11400() || (fire_transition_shiftUp_ID_11403() || fire_transition_reset_ID_11433()))) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear2(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 2;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Gear3_ID_11361(){
	if (!(fire_transition_shiftDown_ID_11406() || (fire_transition_shiftUp_ID_11409() || fire_transition_reset_ID_11427()))) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear3(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 3;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Gear4_ID_12193(){
	if (!(fire_transition_shiftDown_ID_11412() || (fire_transition_shiftUp_ID_11415() || fire_transition_reset_ID_11436()))) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear4(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 4;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Gear5_ID_12202(){
	if (!(fire_transition_shiftDown_ID_11418() || (fire_transition_shiftUp_ID_11421() || fire_transition_reset_ID_11430()))) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear5(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 5;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Gear6_ID_11388(){
	if (!(fire_transition_shiftDown_ID_11424() || fire_transition_reset_ID_11439())) {
		noval_Throttle_ID_11458 = false;
		Throttle_ID_11458 = gear6(GasPedal_ID_11450);
		
		noval_Gear_ID_12696 = false;
		Gear_ID_12696 = 6;
		
	}
	return true;
}
