/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Check_ID_24609.h"

GEN_TYPE_double DistanceToFrontUS_In_ID_24618;

GEN_TYPE_boolean noval_DistanceToFrontUS_In_ID_24618;

GEN_TYPE_double DistanceToFrontLaser_In_ID_32187;

GEN_TYPE_boolean noval_DistanceToFrontLaser_In_ID_32187;

GEN_TYPE_double DistanceToFrontUS2_Orig_ID_24632;

GEN_TYPE_boolean noval_DistanceToFrontUS2_Orig_ID_24632;

GEN_TYPE_double DistanceToFrontUS1_Orig_ID_24639;

GEN_TYPE_boolean noval_DistanceToFrontUS1_Orig_ID_24639;

GEN_TYPE_double DistanceToFrontLaser_Orig_ID_24646;

GEN_TYPE_boolean noval_DistanceToFrontLaser_Orig_ID_24646;

GEN_TYPE_double DistanceToFrontLaser_ID_24651;

GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_24651;

GEN_TYPE_double DistanceToFrontUS_ID_24658;

GEN_TYPE_boolean noval_DistanceToFrontUS_ID_24658;

void clear_inputs_Check_ID_24609(){
	noval_DistanceToFrontUS_In_ID_24618 = true;
	noval_DistanceToFrontLaser_In_ID_32187 = true;
	noval_DistanceToFrontUS2_Orig_ID_24632 = true;
	noval_DistanceToFrontUS1_Orig_ID_24639 = true;
	noval_DistanceToFrontLaser_Orig_ID_24646 = true;
}

void clear_outputs_Check_ID_24609(){
	noval_DistanceToFrontLaser_ID_24651 = true;
	noval_DistanceToFrontUS_ID_24658 = true;
}

void init_Check_ID_24609(){
	noval_DistanceToFrontLaser_ID_24651 = true;
	noval_DistanceToFrontUS_ID_24658 = true;
}

void perform_step_Check_ID_24609(){
	clear_outputs_Check_ID_24609();
	noval_DistanceToFrontLaser_ID_24651 = noval_DistanceToFrontLaser_In_ID_32187;
	if (!noval_DistanceToFrontLaser_In_ID_32187) {
		DistanceToFrontLaser_ID_24651 = DistanceToFrontLaser_In_ID_32187;
	}
	
	noval_DistanceToFrontUS_ID_24658 = noval_DistanceToFrontUS_In_ID_24618;
	if (!noval_DistanceToFrontUS_In_ID_24618) {
		DistanceToFrontUS_ID_24658 = DistanceToFrontUS_In_ID_24618;
	}
	
	return;
	
}
