/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/DA_Plausibilization_Test_ID_10270.h"

GEN_TYPE_DriverAssistanceCommands DA_States_ID_16169;

GEN_TYPE_boolean noval_DA_States_ID_16169;

GEN_TYPE_double MaxAccelerationMD_ID_10287;

GEN_TYPE_boolean noval_MaxAccelerationMD_ID_10287;

GEN_TYPE_double MaxAccelerationEB_ID_29313;

GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29313;

GEN_TYPE_double TargetVelocityMD_ID_10301;

GEN_TYPE_boolean noval_TargetVelocityMD_ID_10301;

GEN_TYPE_double TargetVelocityDA_ID_10308;

GEN_TYPE_boolean noval_TargetVelocityDA_ID_10308;

GEN_TYPE_double SteeringAngleDA_ID_16188;

GEN_TYPE_boolean noval_SteeringAngleDA_ID_16188;

GEN_TYPE_double SteeringAngleMD_ID_16902;

GEN_TYPE_boolean noval_SteeringAngleMD_ID_16902;

GEN_TYPE_boolean Platooning_IsLeader_ID_29659;

GEN_TYPE_boolean noval_Platooning_IsLeader_ID_29659;

GEN_TYPE_boolean platooningOff_ID_29668;

GEN_TYPE_boolean noval_platooningOff_ID_29668;

GEN_TYPE_boolean ForceEBOff_ID_44971;

GEN_TYPE_boolean noval_ForceEBOff_ID_44971;

GEN_TYPE_PlatoonState platoonState_ID_61160;

GEN_TYPE_boolean noval_platoonState_ID_61160;

GEN_TYPE_boolean ACC_On_Correct_ID_16267;

GEN_TYPE_boolean noval_ACC_On_Correct_ID_16267;

GEN_TYPE_boolean Shutdown_ID_17990;

GEN_TYPE_boolean noval_Shutdown_ID_17990;

GEN_TYPE_boolean ACC_TurnOff_ID_16218;

GEN_TYPE_boolean noval_ACC_TurnOff_ID_16218;

GEN_TYPE_boolean LK_On_Correct_ID_16193;

GEN_TYPE_boolean noval_LK_On_Correct_ID_16193;

GEN_TYPE_boolean LK_TurnOff_ID_16227;

GEN_TYPE_boolean noval_LK_TurnOff_ID_16227;

void clear_inputs_DA_Plausibilization_Test_ID_10270(){
	noval_DA_States_ID_16169 = true;
	noval_MaxAccelerationMD_ID_10287 = true;
	noval_MaxAccelerationEB_ID_29313 = true;
	noval_TargetVelocityMD_ID_10301 = true;
	noval_TargetVelocityDA_ID_10308 = true;
	noval_SteeringAngleDA_ID_16188 = true;
	noval_SteeringAngleMD_ID_16902 = true;
	noval_Platooning_IsLeader_ID_29659 = true;
	noval_platooningOff_ID_29668 = true;
	noval_ForceEBOff_ID_44971 = true;
	noval_platoonState_ID_61160 = true;
}

void clear_outputs_DA_Plausibilization_Test_ID_10270(){
	noval_ACC_On_Correct_ID_16267 = true;
	noval_Shutdown_ID_17990 = true;
	noval_ACC_TurnOff_ID_16218 = true;
	noval_LK_On_Correct_ID_16193 = true;
	noval_LK_TurnOff_ID_16227 = true;
}

void init_DA_Plausibilization_Test_ID_10270(){
	noval_ACC_On_Correct_ID_16267 = true;
	noval_Shutdown_ID_17990 = true;
	noval_ACC_TurnOff_ID_16218 = true;
	noval_LK_On_Correct_ID_16193 = true;
	noval_LK_TurnOff_ID_16227 = true;
}

void perform_step_DA_Plausibilization_Test_ID_10270(){
	clear_outputs_DA_Plausibilization_Test_ID_10270();
	if (!(noval_MaxAccelerationEB_ID_29313 == true) && !ForceEBOff_ID_44971) {
		noval_ACC_On_Correct_ID_16267 = false;
		ACC_On_Correct_ID_16267 = false;
		
		noval_LK_On_Correct_ID_16193 = false;
		LK_On_Correct_ID_16193 = false;
		
		noval_ACC_TurnOff_ID_16218 = false;
		ACC_TurnOff_ID_16218 = true;
		
		noval_LK_TurnOff_ID_16227 = false;
		LK_TurnOff_ID_16227 = true;
		
		noval_Shutdown_ID_17990 = false;
		Shutdown_ID_17990 = true;
		
	}
	else {
		noval_Shutdown_ID_17990 = false;
		Shutdown_ID_17990 = false;
		
		if (noval_DA_States_ID_16169 == true) {
			noval_ACC_On_Correct_ID_16267 = false;
			ACC_On_Correct_ID_16267 = false;
			
			noval_LK_On_Correct_ID_16193 = false;
			LK_On_Correct_ID_16193 = false;
			
			noval_ACC_TurnOff_ID_16218 = false;
			ACC_TurnOff_ID_16218 = true;
			
			noval_LK_TurnOff_ID_16227 = false;
			LK_TurnOff_ID_16227 = true;
			
		}
		else {
			if ((DA_States_ID_16169.acc == On() && !(noval_TargetVelocityDA_ID_10308 == true)) && ((noval_platooningOff_ID_29668 == true || platooningOff_ID_29668) || Platooning_IsLeader_ID_29659)) {
				if (noval_MaxAccelerationMD_ID_10287 == true || !(noval_MaxAccelerationMD_ID_10287 == true) && MaxAccelerationMD_ID_10287 >= 0.0) {
					if (noval_TargetVelocityMD_ID_10301 == true || !(noval_TargetVelocityMD_ID_10301 == true) && TargetVelocityMD_ID_10301 < TargetVelocityDA_ID_10308) {
						noval_ACC_On_Correct_ID_16267 = false;
						ACC_On_Correct_ID_16267 = true;
						
						noval_ACC_TurnOff_ID_16218 = false;
						ACC_TurnOff_ID_16218 = false;
						
					}
					else {
						noval_ACC_On_Correct_ID_16267 = false;
						ACC_On_Correct_ID_16267 = false;
						
						noval_ACC_TurnOff_ID_16218 = false;
						ACC_TurnOff_ID_16218 = false;
						
					}
				}
				else {
					noval_ACC_On_Correct_ID_16267 = false;
					ACC_On_Correct_ID_16267 = false;
					
					noval_ACC_TurnOff_ID_16218 = false;
					ACC_TurnOff_ID_16218 = true;
					
				}
			}
			else {
				noval_ACC_On_Correct_ID_16267 = false;
				ACC_On_Correct_ID_16267 = false;
				
				noval_ACC_TurnOff_ID_16218 = false;
				ACC_TurnOff_ID_16218 = true;
				
			}
			if (noval_SteeringAngleDA_ID_16188 == true) {
				noval_LK_On_Correct_ID_16193 = false;
				LK_On_Correct_ID_16193 = false;
				
				noval_LK_TurnOff_ID_16227 = false;
				LK_TurnOff_ID_16227 = true;
				
			}
			else {
				if (DA_States_ID_16169.laneKeep == On() || !(noval_platoonState_ID_61160 == true) && (noval_platoonState_ID_61160 == false && platoonState_ID_61160 == follower())) {
					if (noval_SteeringAngleDA_ID_16188 == false && SteeringAngleDA_ID_16188 == -1000.0 || myabs(SteeringAngleMD_ID_16902) > STEERING_DEADZONE()) {
						noval_LK_On_Correct_ID_16193 = false;
						LK_On_Correct_ID_16193 = false;
						
						noval_LK_TurnOff_ID_16227 = false;
						LK_TurnOff_ID_16227 = true;
						
					}
					else {
						noval_LK_On_Correct_ID_16193 = false;
						LK_On_Correct_ID_16193 = true;
						
						noval_LK_TurnOff_ID_16227 = false;
						LK_TurnOff_ID_16227 = false;
						
					}
				}
				else {
					noval_LK_On_Correct_ID_16193 = false;
					LK_On_Correct_ID_16193 = false;
					
					noval_LK_TurnOff_ID_16227 = false;
					LK_TurnOff_ID_16227 = false;
					
				}
			}
		}
	}
	if (noval_platooningOff_ID_29668 == false && platooningOff_ID_29668 == false) {
		noval_ACC_On_Correct_ID_16267 = false;
		ACC_On_Correct_ID_16267 = true;
		
		noval_ACC_TurnOff_ID_16218 = false;
		ACC_TurnOff_ID_16218 = false;
		
	}
	return;
	
}
