/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/DriveModeFusion_ID_13838.h"

GEN_TYPE_int DriveModeIn_ID_13862;

GEN_TYPE_boolean noval_DriveModeIn_ID_13862;

GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13888;

GEN_TYPE_boolean noval_DriveModeCommands_ID_13888;

GEN_TYPE_DriveModeSettings DriveModeOut_ID_13866;

GEN_TYPE_boolean noval_DriveModeOut_ID_13866;

void clear_inputs_DriveModeFusion_ID_13838(){
	noval_DriveModeIn_ID_13862 = true;
	noval_DriveModeCommands_ID_13888 = true;
}

void clear_outputs_DriveModeFusion_ID_13838(){
	noval_DriveModeOut_ID_13866 = true;
}

void init_DriveModeFusion_ID_13838(){
	noval_DriveModeOut_ID_13866 = true;
}

void perform_step_DriveModeFusion_ID_13838(){
	clear_outputs_DriveModeFusion_ID_13838();
	if (noval_DriveModeIn_ID_13862 == true) {
		if (!(noval_DriveModeCommands_ID_13888 == true) && DriveModeCommands_ID_13888.Button4 == pressed()) {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = Switch();
			DriveModeOut_ID_13866.DriveMode = Change();
			
			
		}
		else {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = NoOp();
			DriveModeOut_ID_13866.DriveMode = Change();
			
			
		}
	}
	if (noval_DriveModeIn_ID_13862 == false && DriveModeIn_ID_13862 == 0) {
		if (!(noval_DriveModeCommands_ID_13888 == true) && DriveModeCommands_ID_13888.Button4 == pressed()) {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = Switch();
			DriveModeOut_ID_13866.DriveMode = Parking();
			
			
		}
		else {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = NoOp();
			DriveModeOut_ID_13866.DriveMode = Parking();
			
			
		}
	}
	if (DriveModeIn_ID_13862 > 0) {
		if (!(noval_DriveModeCommands_ID_13888 == true) && DriveModeCommands_ID_13888.Button4 == pressed()) {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = Switch();
			DriveModeOut_ID_13866.DriveMode = Forward();
			
			
		}
		else {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = NoOp();
			DriveModeOut_ID_13866.DriveMode = Forward();
			
			
		}
	}
	if (DriveModeIn_ID_13862 < 0) {
		if (!(noval_DriveModeCommands_ID_13888 == true) && DriveModeCommands_ID_13888.Button4 == pressed()) {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = Switch();
			DriveModeOut_ID_13866.DriveMode = Backward();
			
			
		}
		else {
			noval_DriveModeOut_ID_13866 = false;
			DriveModeOut_ID_13866.EngineMode = NoOp();
			DriveModeOut_ID_13866.DriveMode = Backward();
			
			
		}
	}
	return;
	
}
