/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/EBRumble_ID_17138.h"

GEN_TYPE_boolean RumbleEB_ID_17206;

GEN_TYPE_boolean noval_RumbleEB_ID_17206;

GEN_TYPE_boolean ForceEBOff_ID_17754;

GEN_TYPE_boolean noval_ForceEBOff_ID_17754;

GEN_TYPE_int RumbleEB_In_ID_17209;

GEN_TYPE_boolean noval_RumbleEB_In_ID_17209;

static GEN_TYPE_int current_state;

static GEN_TYPE_int counter;

static GEN_TYPE_int scratch_paper_counter;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17157();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17159();

static GEN_TYPE_boolean fire_state_Init_ID_17145();

static GEN_TYPE_boolean fire_state_State_ID_17150();

void clear_inputs_EBRumble_ID_17138(){
	noval_RumbleEB_ID_17206 = true;
	noval_ForceEBOff_ID_17754 = true;
}

void clear_outputs_EBRumble_ID_17138(){
	noval_RumbleEB_In_ID_17209 = true;
}

void init_EBRumble_ID_17138(){
	noval_RumbleEB_In_ID_17209 = true;
	current_state = 17145;
	counter = 0;
	scratch_paper_counter = 0;
}

void perform_step_EBRumble_ID_17138(){
	clear_outputs_EBRumble_ID_17138();
	if (current_state == 17150) {
		fire_state_State_ID_17150();
	}
	else {
		if (current_state == 17145) {
			fire_state_Init_ID_17145();
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	counter = scratch_paper_counter;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17157(){
	if ((!(noval_RumbleEB_ID_17206 == true) && RumbleEB_ID_17206) && !ForceEBOff_ID_17754) {
		noval_RumbleEB_In_ID_17209 = false;
		RumbleEB_In_ID_17209 = 0;
		
		current_state = 17150;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17159(){
	if ((noval_RumbleEB_ID_17206 == true || !RumbleEB_ID_17206) && counter == 30 || ForceEBOff_ID_17754) {
		noval_RumbleEB_In_ID_17209 = false;
		RumbleEB_In_ID_17209 = 0;
		
		current_state = 17145;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_17145(){
	if (!fire_transition_Transition_Segment_ID_17157()) {
		noval_RumbleEB_In_ID_17209 = false;
		RumbleEB_In_ID_17209 = 0;
		
		scratch_paper_counter = 0;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_State_ID_17150(){
	if (!fire_transition_Transition_Segment_ID_17159()) {
		noval_RumbleEB_In_ID_17209 = false;
		RumbleEB_In_ID_17209 = RUMBLE_MAX();
		
		scratch_paper_counter = counter + 1;
	}
	return true;
}
