/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Fuse_Split_ID_27169.h"

GEN_TYPE_AutonomousDrivingEvents ADCommand_ID_27226;

GEN_TYPE_boolean noval_ADCommand_ID_27226;

GEN_TYPE_boolean fuse_ID_27243;

GEN_TYPE_boolean noval_fuse_ID_27243;

GEN_TYPE_boolean split_ID_27252;

GEN_TYPE_boolean noval_split_ID_27252;

void clear_inputs_Fuse_Split_ID_27169(){
	noval_ADCommand_ID_27226 = true;
}

void clear_outputs_Fuse_Split_ID_27169(){
	noval_fuse_ID_27243 = true;
	noval_split_ID_27252 = true;
}

void init_Fuse_Split_ID_27169(){
	noval_fuse_ID_27243 = true;
	noval_split_ID_27252 = true;
}

void perform_step_Fuse_Split_ID_27169(){
	clear_outputs_Fuse_Split_ID_27169();
	if (!(noval_ADCommand_ID_27226 == true) && ADCommand_ID_27226.fusePlatoon == pressed()) {
		noval_fuse_ID_27243 = false;
		fuse_ID_27243 = true;
		
	}
	else {
		noval_fuse_ID_27243 = false;
		fuse_ID_27243 = false;
		
	}
	if (!(noval_ADCommand_ID_27226 == true) && ADCommand_ID_27226.splitPlatoon == pressed()) {
		noval_split_ID_27252 = false;
		split_ID_27252 = true;
		
	}
	else {
		noval_split_ID_27252 = false;
		split_ID_27252 = false;
		
	}
	return;
	
}
