/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/L1_ID_13496.h"

GEN_TYPE_int ButtonL1In_ID_32547;

GEN_TYPE_boolean noval_ButtonL1In_ID_32547;

GEN_TYPE_KeyEvent ButtonL1Out_ID_32500;

GEN_TYPE_boolean noval_ButtonL1Out_ID_32500;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_13515();

static GEN_TYPE_boolean fire_transition_Release_ID_13517();

static GEN_TYPE_boolean fire_state_Released_ID_13503();

static GEN_TYPE_boolean fire_state_Pressed_ID_13508();

void clear_inputs_L1_ID_13496(){
	noval_ButtonL1In_ID_32547 = true;
}

void clear_outputs_L1_ID_13496(){
	noval_ButtonL1Out_ID_32500 = true;
}

void init_L1_ID_13496(){
	noval_ButtonL1Out_ID_32500 = true;
	current_state = 13503;
}

void perform_step_L1_ID_13496(){
	clear_outputs_L1_ID_13496();
	if (current_state == 13508) {
		fire_state_Pressed_ID_13508();
	}
	else {
		if (current_state == 13503) {
			fire_state_Released_ID_13503();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_13515(){
	if (noval_ButtonL1In_ID_32547 == false && ButtonL1In_ID_32547 == 1) {
		noval_ButtonL1Out_ID_32500 = false;
		ButtonL1Out_ID_32500 = pressed();
		
		current_state = 13508;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_13517(){
	if (noval_ButtonL1In_ID_32547 == true || noval_ButtonL1In_ID_32547 == false && ButtonL1In_ID_32547 == 0) {
		noval_ButtonL1Out_ID_32500 = false;
		ButtonL1Out_ID_32500 = notPressed();
		
		current_state = 13503;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_13503(){
	if (!fire_transition_Press_ID_13515()) {
		noval_ButtonL1Out_ID_32500 = false;
		ButtonL1Out_ID_32500 = notPressed();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_13508(){
	if (!fire_transition_Release_ID_13517()) {
		noval_ButtonL1Out_ID_32500 = false;
		ButtonL1Out_ID_32500 = pressed();
		
	}
	return true;
}
