/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Max_ACC_Velocity_ID_8163.h"

GEN_TYPE_int SpeedChange_ID_44191;

GEN_TYPE_boolean noval_SpeedChange_ID_44191;

GEN_TYPE_double LastMaxVelocity_ID_44207;

GEN_TYPE_boolean noval_LastMaxVelocity_ID_44207;

GEN_TYPE_double MaxVelocity_ID_44684;

GEN_TYPE_boolean noval_MaxVelocity_ID_44684;

void clear_inputs_Max_ACC_Velocity_ID_8163(){
	noval_SpeedChange_ID_44191 = true;
	noval_LastMaxVelocity_ID_44207 = true;
}

void clear_outputs_Max_ACC_Velocity_ID_8163(){
	noval_MaxVelocity_ID_44684 = true;
}

void init_Max_ACC_Velocity_ID_8163(){
	noval_MaxVelocity_ID_44684 = true;
}

void perform_step_Max_ACC_Velocity_ID_8163(){
	clear_outputs_Max_ACC_Velocity_ID_8163();
	if (noval_LastMaxVelocity_ID_44207 == true) {
		noval_MaxVelocity_ID_44684 = false;
		MaxVelocity_ID_44684 = ACC_DEFAULT_VELOCITY();
		
	}
	else {
		if (LastMaxVelocity_ID_44207 + SpeedChange_ID_44191 * 0.1 > 1.0) {
			noval_MaxVelocity_ID_44684 = false;
			MaxVelocity_ID_44684 = 1.0;
			
		}
		else {
			if (LastMaxVelocity_ID_44207 + SpeedChange_ID_44191 * 0.1 < 0.0) {
				noval_MaxVelocity_ID_44684 = false;
				MaxVelocity_ID_44684 = 0.0;
				
			}
			else {
				noval_MaxVelocity_ID_44684 = false;
				MaxVelocity_ID_44684 = LastMaxVelocity_ID_44207 + SpeedChange_ID_44191 * 0.1;
				
			}
		}
	}
	return;
	
}
