/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Min_ID_16760.h"

GEN_TYPE_double DistanceToFrontUS_1_ID_32194;

GEN_TYPE_boolean noval_DistanceToFrontUS_1_ID_32194;

GEN_TYPE_double DistanceToFrontUS_2_ID_32212;

GEN_TYPE_boolean noval_DistanceToFrontUS_2_ID_32212;

GEN_TYPE_double DistanceToFrontUS_Out_ID_24616;

GEN_TYPE_boolean noval_DistanceToFrontUS_Out_ID_24616;

void clear_inputs_Min_ID_16760(){
	noval_DistanceToFrontUS_1_ID_32194 = true;
	noval_DistanceToFrontUS_2_ID_32212 = true;
}

void clear_outputs_Min_ID_16760(){
	noval_DistanceToFrontUS_Out_ID_24616 = true;
}

void init_Min_ID_16760(){
	noval_DistanceToFrontUS_Out_ID_24616 = true;
}

void perform_step_Min_ID_16760(){
	clear_outputs_Min_ID_16760();
	if (noval_DistanceToFrontUS_1_ID_32194 == true) {
		noval_DistanceToFrontUS_Out_ID_24616 = noval_DistanceToFrontUS_2_ID_32212;
		if (!noval_DistanceToFrontUS_2_ID_32212) {
			DistanceToFrontUS_Out_ID_24616 = DistanceToFrontUS_2_ID_32212;
		}
		
	}
	else {
		if (noval_DistanceToFrontUS_2_ID_32212 == true) {
			noval_DistanceToFrontUS_Out_ID_24616 = noval_DistanceToFrontUS_1_ID_32194;
			if (!noval_DistanceToFrontUS_1_ID_32194) {
				DistanceToFrontUS_Out_ID_24616 = DistanceToFrontUS_1_ID_32194;
			}
			
		}
		else {
			noval_DistanceToFrontUS_Out_ID_24616 = false;
			DistanceToFrontUS_Out_ID_24616 = min(DistanceToFrontUS_1_ID_32194, DistanceToFrontUS_2_ID_32212);
			
		}
	}
	return;
	
}
