/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/OLD_Stopping_distances_comparison_ID_45136.h"

GEN_TYPE_double Velocity_ID_45165;

GEN_TYPE_boolean noval_Velocity_ID_45165;

GEN_TYPE_double DistanceFront_ID_45167;

GEN_TYPE_boolean noval_DistanceFront_ID_45167;

GEN_TYPE_double VelocityFrontObstacle_ID_45169;

GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_45169;

GEN_TYPE_boolean CriticalSituation_ID_45163;

GEN_TYPE_boolean noval_CriticalSituation_ID_45163;

void clear_inputs_OLD_Stopping_distances_comparison_ID_45136(){
	noval_Velocity_ID_45165 = true;
	noval_DistanceFront_ID_45167 = true;
	noval_VelocityFrontObstacle_ID_45169 = true;
}

void clear_outputs_OLD_Stopping_distances_comparison_ID_45136(){
	noval_CriticalSituation_ID_45163 = true;
}

void init_OLD_Stopping_distances_comparison_ID_45136(){
	noval_CriticalSituation_ID_45163 = true;
}

void perform_step_OLD_Stopping_distances_comparison_ID_45136(){
	clear_outputs_OLD_Stopping_distances_comparison_ID_45136();
	if ((noval_Velocity_ID_45165 == true || noval_VelocityFrontObstacle_ID_45169 == true) || noval_DistanceFront_ID_45167 == true) {
		noval_CriticalSituation_ID_45163 = false;
		CriticalSituation_ID_45163 = true;
		
	}
	else {
		if (Velocity_ID_45165 > VELOCITY_DEADZONE()) {
			if (VelocityFrontObstacle_ID_45169 < 0.0) {
				if (DistanceFront_ID_45167 <= ((-0.5 * pow(Velocity_ID_45165, 2.0)) / MAX_BRAKE_VALUE() + pow(Velocity_ID_45165, EB_BUFFER_POW()) * EB_BUFFER_FACTOR()) - (Velocity_ID_45165 / MAX_BRAKE_VALUE()) * VelocityFrontObstacle_ID_45169) {
					noval_CriticalSituation_ID_45163 = false;
					CriticalSituation_ID_45163 = true;
					
					return;
				}
			}
			else {
				if (Velocity_ID_45165 - VelocityFrontObstacle_ID_45169 > 0.5) {
					if (DistanceFront_ID_45167 <= ((-0.5 * pow(Velocity_ID_45165, 2.0)) / MAX_BRAKE_VALUE() + pow(Velocity_ID_45165, EB_BUFFER_POW()) * EB_BUFFER_FACTOR()) - (-0.5 * pow(VelocityFrontObstacle_ID_45169, 2.0)) / MAX_EXPECTED_BRAKE_VALUE()) {
						noval_CriticalSituation_ID_45163 = false;
						CriticalSituation_ID_45163 = true;
						
						return;
					}
				}
				else {
					if (DistanceFront_ID_45167 <= ((-0.5 * pow(Velocity_ID_45165, 2.0)) / MAX_BRAKE_VALUE() + pow(Velocity_ID_45165, EB_BUFFER_POW()) * EB_BUFFER_FACTOR_FOLLOW()) - (-0.5 * pow(VelocityFrontObstacle_ID_45169, 2.0)) / MAX_EXPECTED_BRAKE_VALUE()) {
						noval_CriticalSituation_ID_45163 = false;
						CriticalSituation_ID_45163 = true;
						
						return;
					}
				}
			}
		}
		noval_CriticalSituation_ID_45163 = false;
		CriticalSituation_ID_45163 = false;
		
	}
	return;
	
}
