/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/P_term_ID_16009.h"

GEN_TYPE_double Error_ID_16080;

GEN_TYPE_boolean noval_Error_ID_16080;

GEN_TYPE_double Coef_P_ID_16028;

GEN_TYPE_boolean noval_Coef_P_ID_16028;

void clear_inputs_P_term_ID_16009(){
	noval_Error_ID_16080 = true;
}

void clear_outputs_P_term_ID_16009(){
	noval_Coef_P_ID_16028 = true;
}

void init_P_term_ID_16009(){
	noval_Coef_P_ID_16028 = true;
}

void perform_step_P_term_ID_16009(){
	clear_outputs_P_term_ID_16009();
	if (noval_Error_ID_16080 == true || noval_Error_ID_16080 == false && Error_ID_16080 == 0.0) {
		noval_Coef_P_ID_16028 = false;
		Coef_P_ID_16028 = 0.0;
		
	}
	else {
		noval_Coef_P_ID_16028 = false;
		Coef_P_ID_16028 = COEFFICIENT_LK_CONTROLLER_P() * Error_ID_16080;
		
	}
	return;
	
}
