/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Preliminary_DriveMode_ID_13768.h"

GEN_TYPE_double Velocity_ID_13874;

GEN_TYPE_boolean noval_Velocity_ID_13874;

GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13895;

GEN_TYPE_boolean noval_DriveModeCommands_ID_13895;

GEN_TYPE_boolean EB_On_ID_13916;

GEN_TYPE_boolean noval_EB_On_ID_13916;

GEN_TYPE_boolean ForceEBOff_ID_29323;

GEN_TYPE_boolean noval_ForceEBOff_ID_29323;

GEN_TYPE_int DriveMode_ID_13826;

GEN_TYPE_boolean noval_DriveMode_ID_13826;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13798();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13802();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13806();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13812();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13818();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13822();

static GEN_TYPE_boolean fire_state_Parking_ID_13775();

static GEN_TYPE_boolean fire_state_Forward_ID_13782();

static GEN_TYPE_boolean fire_state_Backward_ID_13789();

void clear_inputs_Preliminary_DriveMode_ID_13768(){
	noval_Velocity_ID_13874 = true;
	noval_DriveModeCommands_ID_13895 = true;
	noval_EB_On_ID_13916 = true;
	noval_ForceEBOff_ID_29323 = true;
}

void clear_outputs_Preliminary_DriveMode_ID_13768(){
	noval_DriveMode_ID_13826 = true;
}

void init_Preliminary_DriveMode_ID_13768(){
	noval_DriveMode_ID_13826 = true;
	current_state = 13775;
}

void perform_step_Preliminary_DriveMode_ID_13768(){
	clear_outputs_Preliminary_DriveMode_ID_13768();
	if (current_state == 13789) {
		fire_state_Backward_ID_13789();
	}
	else {
		if (current_state == 13782) {
			fire_state_Forward_ID_13782();
		}
		else {
			if (current_state == 13775) {
				fire_state_Parking_ID_13775();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13798(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button1 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 100;
		
		current_state = 13782;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13802(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button3 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = -100;
		
		current_state = 13789;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13806(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button2 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE()) || (!(noval_EB_On_ID_13916 == true) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE())) && ((noval_EB_On_ID_13916 == false && EB_On_ID_13916 == true) && !ForceEBOff_ID_29323)) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 0;
		
		current_state = 13775;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13812(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button2 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE()) || (!(noval_EB_On_ID_13916 == true) && (noval_Velocity_ID_13874 == true || Velocity_ID_13874 <= VELOCITY_DEADZONE())) && ((noval_EB_On_ID_13916 == false && EB_On_ID_13916 == true) && !ForceEBOff_ID_29323)) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 0;
		
		current_state = 13775;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13818(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button1 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 100;
		
		current_state = 13782;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_13822(){
	if ((!(noval_DriveModeCommands_ID_13895 == true) && DriveModeCommands_ID_13895.Button3 == pressed()) && (noval_Velocity_ID_13874 == true || myabs(Velocity_ID_13874) <= VELOCITY_DEADZONE())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = -100;
		
		current_state = 13789;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Parking_ID_13775(){
	if (!(fire_transition_Transition_Segment_ID_13798() || fire_transition_Transition_Segment_ID_13802())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Forward_ID_13782(){
	if (!(fire_transition_Transition_Segment_ID_13812() || fire_transition_Transition_Segment_ID_13822())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = 100;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Backward_ID_13789(){
	if (!(fire_transition_Transition_Segment_ID_13806() || fire_transition_Transition_Segment_ID_13818())) {
		noval_DriveMode_ID_13826 = false;
		DriveMode_ID_13826 = -100;
		
	}
	return true;
}
