/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/Speed_Change_ID_43293.h"

GEN_TYPE_DriverAssistanceCommands DA_States_ID_53834;

GEN_TYPE_boolean noval_DA_States_ID_53834;

GEN_TYPE_int SpeedChange_ID_44189;

GEN_TYPE_boolean noval_SpeedChange_ID_44189;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Rising_flank_ID_43319();

static GEN_TYPE_boolean fire_transition_Falling_flank_ID_43322();

static GEN_TYPE_boolean fire_transition_Rising_flank_ID_43325();

static GEN_TYPE_boolean fire_transition_Falling_flank_ID_43328();

static GEN_TYPE_boolean fire_state_Released_ID_43300();

static GEN_TYPE_boolean fire_state_Plus__Still_pushed_ID_43307();

static GEN_TYPE_boolean fire_state_Minus__Still_pushed_ID_43312();

void clear_inputs_Speed_Change_ID_43293(){
	noval_DA_States_ID_53834 = true;
}

void clear_outputs_Speed_Change_ID_43293(){
	noval_SpeedChange_ID_44189 = true;
}

void init_Speed_Change_ID_43293(){
	noval_SpeedChange_ID_44189 = true;
	current_state = 43300;
}

void perform_step_Speed_Change_ID_43293(){
	clear_outputs_Speed_Change_ID_43293();
	if (current_state == 43312) {
		fire_state_Minus__Still_pushed_ID_43312();
	}
	else {
		if (current_state == 43307) {
			fire_state_Plus__Still_pushed_ID_43307();
		}
		else {
			if (current_state == 43300) {
				fire_state_Released_ID_43300();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Rising_flank_ID_43319(){
	if (!(noval_DA_States_ID_53834 == true) && DA_States_ID_53834.speedPlus == pressed()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 1;
		
		current_state = 43307;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Falling_flank_ID_43322(){
	if (noval_DA_States_ID_53834 == true || DA_States_ID_53834.speedPlus == notPressed()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 0;
		
		current_state = 43300;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Rising_flank_ID_43325(){
	if (!(noval_DA_States_ID_53834 == true) && DA_States_ID_53834.speedMinus == pressed()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = -1;
		
		current_state = 43312;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Falling_flank_ID_43328(){
	if (noval_DA_States_ID_53834 == true || DA_States_ID_53834.speedMinus == notPressed()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 0;
		
		current_state = 43300;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_43300(){
	if (!(fire_transition_Rising_flank_ID_43319() || fire_transition_Rising_flank_ID_43325())) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Plus__Still_pushed_ID_43307(){
	if (!fire_transition_Falling_flank_ID_43322()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Minus__Still_pushed_ID_43312(){
	if (!fire_transition_Falling_flank_ID_43328()) {
		noval_SpeedChange_ID_44189 = false;
		SpeedChange_ID_44189 = 0;
		
	}
	return true;
}
