/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/V2V_Receive_ID_22660.h"

GEN_TYPE_MessageSplit receiveSplit_ID_22669;

GEN_TYPE_boolean noval_receiveSplit_ID_22669;

GEN_TYPE_MessageNewLeader receiveNewLeader_ID_22790;

GEN_TYPE_boolean noval_receiveNewLeader_ID_22790;

GEN_TYPE_MessageFuse receiveFuse_ID_22797;

GEN_TYPE_boolean noval_receiveFuse_ID_22797;

GEN_TYPE_MessageFollower receiveFollowerMessage_ID_22804;

GEN_TYPE_boolean noval_receiveFollowerMessage_ID_22804;

GEN_TYPE_MessagePlatoon receivePlatoonMessage_ID_22811;

GEN_TYPE_boolean noval_receivePlatoonMessage_ID_22811;

GEN_TYPE_MessageLeave receiveLeave_ID_22818;

GEN_TYPE_boolean noval_receiveLeave_ID_22818;

GEN_TYPE_MessageLeaderHB receiveLeaderHB_ID_22825;

GEN_TYPE_boolean noval_receiveLeaderHB_ID_22825;

GEN_TYPE_MessageHandshake receiveHandshake_ID_28255;

GEN_TYPE_boolean noval_receiveHandshake_ID_28255;

GEN_TYPE_MessageSplit receiveSplitOut_ID_22674;

GEN_TYPE_boolean noval_receiveSplitOut_ID_22674;

GEN_TYPE_MessageFollower receiveFollowerMessageOut_ID_22836;

GEN_TYPE_boolean noval_receiveFollowerMessageOut_ID_22836;

GEN_TYPE_MessageFuse receiveFuseOut_ID_22843;

GEN_TYPE_boolean noval_receiveFuseOut_ID_22843;

GEN_TYPE_MessageLeaderHB receiveLeaderHBOut_ID_22850;

GEN_TYPE_boolean noval_receiveLeaderHBOut_ID_22850;

GEN_TYPE_MessageNewLeader receiveNewLeaderOut_ID_22857;

GEN_TYPE_boolean noval_receiveNewLeaderOut_ID_22857;

GEN_TYPE_MessagePlatoon receivePlatoonMessageOut_ID_22864;

GEN_TYPE_boolean noval_receivePlatoonMessageOut_ID_22864;

GEN_TYPE_MessageLeave receiveLeaveOut_ID_22871;

GEN_TYPE_boolean noval_receiveLeaveOut_ID_22871;

GEN_TYPE_MessageHandshake receiveHandshakeOut_ID_28278;

GEN_TYPE_boolean noval_receiveHandshakeOut_ID_28278;

void clear_inputs_V2V_Receive_ID_22660(){
	noval_receiveSplit_ID_22669 = true;
	noval_receiveNewLeader_ID_22790 = true;
	noval_receiveFuse_ID_22797 = true;
	noval_receiveFollowerMessage_ID_22804 = true;
	noval_receivePlatoonMessage_ID_22811 = true;
	noval_receiveLeave_ID_22818 = true;
	noval_receiveLeaderHB_ID_22825 = true;
	noval_receiveHandshake_ID_28255 = true;
}

void clear_outputs_V2V_Receive_ID_22660(){
	noval_receiveSplitOut_ID_22674 = true;
	noval_receiveFollowerMessageOut_ID_22836 = true;
	noval_receiveFuseOut_ID_22843 = true;
	noval_receiveLeaderHBOut_ID_22850 = true;
	noval_receiveNewLeaderOut_ID_22857 = true;
	noval_receivePlatoonMessageOut_ID_22864 = true;
	noval_receiveLeaveOut_ID_22871 = true;
	noval_receiveHandshakeOut_ID_28278 = true;
}

void init_V2V_Receive_ID_22660(){
	noval_receiveSplitOut_ID_22674 = true;
	noval_receiveFollowerMessageOut_ID_22836 = true;
	noval_receiveFuseOut_ID_22843 = true;
	noval_receiveLeaderHBOut_ID_22850 = true;
	noval_receiveNewLeaderOut_ID_22857 = true;
	noval_receivePlatoonMessageOut_ID_22864 = true;
	noval_receiveLeaveOut_ID_22871 = true;
	noval_receiveHandshakeOut_ID_28278 = true;
}

void perform_step_V2V_Receive_ID_22660(){
	clear_outputs_V2V_Receive_ID_22660();
	if (!(noval_receiveSplit_ID_22669 == true)) {
		noval_receiveSplitOut_ID_22674 = noval_receiveSplit_ID_22669;
		if (!noval_receiveSplit_ID_22669) {
			receiveSplitOut_ID_22674 = receiveSplit_ID_22669;
		}
		
	}
	if (!(noval_receiveNewLeader_ID_22790 == true)) {
		noval_receiveNewLeaderOut_ID_22857 = noval_receiveNewLeader_ID_22790;
		if (!noval_receiveNewLeader_ID_22790) {
			receiveNewLeaderOut_ID_22857 = receiveNewLeader_ID_22790;
		}
		
	}
	if (!(noval_receiveFuse_ID_22797 == true)) {
		noval_receiveFuseOut_ID_22843 = noval_receiveFuse_ID_22797;
		if (!noval_receiveFuse_ID_22797) {
			receiveFuseOut_ID_22843 = receiveFuse_ID_22797;
		}
		
	}
	if (!(noval_receiveFollowerMessage_ID_22804 == true)) {
		noval_receiveFollowerMessageOut_ID_22836 = noval_receiveFollowerMessage_ID_22804;
		if (!noval_receiveFollowerMessage_ID_22804) {
			receiveFollowerMessageOut_ID_22836 = receiveFollowerMessage_ID_22804;
		}
		
	}
	if (!(noval_receivePlatoonMessage_ID_22811 == true)) {
		noval_receivePlatoonMessageOut_ID_22864 = noval_receivePlatoonMessage_ID_22811;
		if (!noval_receivePlatoonMessage_ID_22811) {
			receivePlatoonMessageOut_ID_22864 = receivePlatoonMessage_ID_22811;
		}
		
	}
	if (!(noval_receiveLeave_ID_22818 == true)) {
		noval_receiveLeaveOut_ID_22871 = noval_receiveLeave_ID_22818;
		if (!noval_receiveLeave_ID_22818) {
			receiveLeaveOut_ID_22871 = receiveLeave_ID_22818;
		}
		
	}
	if (!(noval_receiveLeaderHB_ID_22825 == true)) {
		noval_receiveLeaderHBOut_ID_22850 = noval_receiveLeaderHB_ID_22825;
		if (!noval_receiveLeaderHB_ID_22825) {
			receiveLeaderHBOut_ID_22850 = receiveLeaderHB_ID_22825;
		}
		
	}
	if (!(noval_receiveHandshake_ID_28255 == true)) {
		noval_receiveHandshakeOut_ID_28278 = noval_receiveHandshake_ID_28255;
		if (!noval_receiveHandshake_ID_28255) {
			receiveHandshakeOut_ID_28278 = receiveHandshake_ID_28255;
		}
		
	}
	return;
	
}
