/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#include "inc-gen/WritePlatoonFile_ID_20010.h"

GEN_TYPE_boolean Shutdown_ID_20020;

GEN_TYPE_boolean noval_Shutdown_ID_20020;

GEN_TYPE_double TargetVelocity_ID_20027;

GEN_TYPE_boolean noval_TargetVelocity_ID_20027;

GEN_TYPE_double MaxAcceleration_ID_20034;

GEN_TYPE_boolean noval_MaxAcceleration_ID_20034;

GEN_TYPE_double Velocity_ID_20041;

GEN_TYPE_boolean noval_Velocity_ID_20041;

GEN_TYPE_double Acceleration_ID_20048;

GEN_TYPE_boolean noval_Acceleration_ID_20048;

GEN_TYPE_double SteeringAngle_ID_20055;

GEN_TYPE_boolean noval_SteeringAngle_ID_20055;

void clear_inputs_WritePlatoonFile_ID_20010(){
	noval_Shutdown_ID_20020 = true;
	noval_TargetVelocity_ID_20027 = true;
	noval_MaxAcceleration_ID_20034 = true;
	noval_Velocity_ID_20041 = true;
	noval_Acceleration_ID_20048 = true;
	noval_SteeringAngle_ID_20055 = true;
}

void clear_outputs_WritePlatoonFile_ID_20010(){
}

void init_WritePlatoonFile_ID_20010(){
}

void perform_step_WritePlatoonFile_ID_20010(){
	clear_outputs_WritePlatoonFile_ID_20010();
	return;
	
}
