/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/Distance_Transformation_ID_16635.h"

GEN_TYPE_double DistanceToFrontLaser_ID_16644;

GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_16644;

GEN_TYPE_double DistanceToFrontUS1_ID_16651;

GEN_TYPE_boolean noval_DistanceToFrontUS1_ID_16651;

GEN_TYPE_double DistanceToFrontUS2_ID_16726;

GEN_TYPE_boolean noval_DistanceToFrontUS2_ID_16726;

GEN_TYPE_double DistanceToFrontLaser_Out_ID_32217;

GEN_TYPE_boolean noval_DistanceToFrontLaser_Out_ID_32217;

GEN_TYPE_double DistanceToFrontUS_Out1_ID_32224;

GEN_TYPE_boolean noval_DistanceToFrontUS_Out1_ID_32224;

GEN_TYPE_double DistanceToFrontUS_Out2_ID_32231;

GEN_TYPE_boolean noval_DistanceToFrontUS_Out2_ID_32231;

void clear_inputs_Distance_Transformation_ID_16635(){
	noval_DistanceToFrontLaser_ID_16644 = true;
	noval_DistanceToFrontUS1_ID_16651 = true;
	noval_DistanceToFrontUS2_ID_16726 = true;
}

void clear_outputs_Distance_Transformation_ID_16635(){
	noval_DistanceToFrontLaser_Out_ID_32217 = true;
	noval_DistanceToFrontUS_Out1_ID_32224 = true;
	noval_DistanceToFrontUS_Out2_ID_32231 = true;
}

void init_Distance_Transformation_ID_16635(){
	noval_DistanceToFrontLaser_Out_ID_32217 = true;
	noval_DistanceToFrontUS_Out1_ID_32224 = true;
	noval_DistanceToFrontUS_Out2_ID_32231 = true;
}

void perform_step_Distance_Transformation_ID_16635(){
	clear_outputs_Distance_Transformation_ID_16635();
	if (!(noval_DistanceToFrontLaser_ID_16644 == true)) {
		noval_DistanceToFrontLaser_Out_ID_32217 = false;
		DistanceToFrontLaser_Out_ID_32217 = (DistanceToFrontLaser_ID_16644 - LASER_CORRECTION()) / 100.0;
		
	}
	else {
		noval_DistanceToFrontLaser_Out_ID_32217 = true;
	}
	if (!(noval_DistanceToFrontUS1_ID_16651 == true)) {
		noval_DistanceToFrontUS_Out1_ID_32224 = false;
		DistanceToFrontUS_Out1_ID_32224 = (DistanceToFrontUS1_ID_16651 - US_CORRECTION()) / 1000.0;
		
	}
	else {
		noval_DistanceToFrontUS_Out1_ID_32224 = true;
	}
	if (!(noval_DistanceToFrontUS2_ID_16726 == true)) {
		noval_DistanceToFrontUS_Out2_ID_32231 = false;
		DistanceToFrontUS_Out2_ID_32231 = (DistanceToFrontUS2_ID_16726 - US_CORRECTION()) / 1000.0;
		
	}
	else {
		noval_DistanceToFrontUS_Out2_ID_32231 = true;
	}
	return;
	
}
