/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/DPadUp_ID_18678.h"

GEN_TYPE_int DPadUpIn_ID_32542;

GEN_TYPE_boolean noval_DPadUpIn_ID_32542;

GEN_TYPE_KeyEvent DPadUpOut_ID_32505;

GEN_TYPE_boolean noval_DPadUpOut_ID_32505;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_18697();

static GEN_TYPE_boolean fire_transition_Release_ID_18699();

static GEN_TYPE_boolean fire_state_Released_ID_18685();

static GEN_TYPE_boolean fire_state_Pressed_ID_18690();

void clear_inputs_DPadUp_ID_18678(){
	noval_DPadUpIn_ID_32542 = true;
}

void clear_outputs_DPadUp_ID_18678(){
	noval_DPadUpOut_ID_32505 = true;
}

void init_DPadUp_ID_18678(){
	noval_DPadUpOut_ID_32505 = true;
	current_state = 18685;
}

void perform_step_DPadUp_ID_18678(){
	clear_outputs_DPadUp_ID_18678();
	if (current_state == 18690) {
		fire_state_Pressed_ID_18690();
	}
	else {
		if (current_state == 18685) {
			fire_state_Released_ID_18685();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_18697(){
	if (noval_DPadUpIn_ID_32542 == false && DPadUpIn_ID_32542 == 1) {
		noval_DPadUpOut_ID_32505 = false;
		DPadUpOut_ID_32505 = pressed();
		
		current_state = 18690;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_18699(){
	if (noval_DPadUpIn_ID_32542 == true || noval_DPadUpIn_ID_32542 == false && DPadUpIn_ID_32542 == 0) {
		noval_DPadUpOut_ID_32505 = false;
		DPadUpOut_ID_32505 = notPressed();
		
		current_state = 18685;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_18685(){
	if (!fire_transition_Press_ID_18697()) {
		noval_DPadUpOut_ID_32505 = false;
		DPadUpOut_ID_32505 = notPressed();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_18690(){
	if (!fire_transition_Release_ID_18699()) {
		noval_DPadUpOut_ID_32505 = false;
		DPadUpOut_ID_32505 = pressed();
		
	}
	return true;
}
