/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/DriveMode_Merge_ID_9317.h"

GEN_TYPE_int ButtonY_ID_13692;

GEN_TYPE_boolean noval_ButtonY_ID_13692;

GEN_TYPE_int ButtonB_ID_13697;

GEN_TYPE_boolean noval_ButtonB_ID_13697;

GEN_TYPE_int ButtonA_ID_13702;

GEN_TYPE_boolean noval_ButtonA_ID_13702;

GEN_TYPE_int ButtonX_ID_13974;

GEN_TYPE_boolean noval_ButtonX_ID_13974;

GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13965;

GEN_TYPE_boolean noval_DriveModeCommands_ID_13965;

void clear_inputs_DriveMode_Merge_ID_9317(){
	noval_ButtonY_ID_13692 = true;
	noval_ButtonB_ID_13697 = true;
	noval_ButtonA_ID_13702 = true;
	noval_ButtonX_ID_13974 = true;
}

void clear_outputs_DriveMode_Merge_ID_9317(){
	noval_DriveModeCommands_ID_13965 = true;
}

void init_DriveMode_Merge_ID_9317(){
	noval_DriveModeCommands_ID_13965 = true;
}

void perform_step_DriveMode_Merge_ID_9317(){
	clear_outputs_DriveMode_Merge_ID_9317();
	if (!(noval_ButtonY_ID_13692 == true) && (noval_ButtonY_ID_13692 == false && ButtonY_ID_13692 == 1)) {
		if (!(noval_ButtonB_ID_13697 == true) && (noval_ButtonB_ID_13697 == false && ButtonB_ID_13697 == 1)) {
			if (!(noval_ButtonA_ID_13702 == true) && (noval_ButtonA_ID_13702 == false && ButtonA_ID_13702 == 1)) {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
			}
			else {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
			}
		}
		else {
			if (!(noval_ButtonA_ID_13702 == true) && (noval_ButtonA_ID_13702 == false && ButtonA_ID_13702 == 1)) {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
			}
			else {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = pressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
			}
		}
	}
	else {
		if (!(noval_ButtonB_ID_13697 == true) && (noval_ButtonB_ID_13697 == false && ButtonB_ID_13697 == 1)) {
			if (!(noval_ButtonA_ID_13702 == true) && (noval_ButtonA_ID_13702 == false && ButtonA_ID_13702 == 1)) {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
			}
			else {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = pressed();
					
					
				}
			}
		}
		else {
			if (!(noval_ButtonA_ID_13702 == true) && (noval_ButtonA_ID_13702 == false && ButtonA_ID_13702 == 1)) {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = pressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
			}
			else {
				if (!(noval_ButtonX_ID_13974 == true) && (noval_ButtonX_ID_13974 == false && ButtonX_ID_13974 == 1)) {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = pressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
				else {
					noval_DriveModeCommands_ID_13965 = false;
					DriveModeCommands_ID_13965.Button1 = notPressed();
					DriveModeCommands_ID_13965.Button4 = notPressed();
					DriveModeCommands_ID_13965.Button3 = notPressed();
					DriveModeCommands_ID_13965.Button2 = notPressed();
					
					
				}
			}
		}
	}
	return;
	
}
