/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:08 CEST 2019 */
#include "inc-gen/History_ID_32.h"

GEN_TYPE_double Output_ID_45025;

GEN_TYPE_boolean noval_Output_ID_45025;

GEN_TYPE_double History_ID_55;

GEN_TYPE_boolean noval_History_ID_55;

void clear_inputs_History_ID_32(){
	noval_Output_ID_45025 = true;
}

void clear_outputs_History_ID_32(){
	noval_History_ID_55 = true;
}

void init_History_ID_32(){
	noval_History_ID_55 = false;
	History_ID_55 = 0;
	
}

void perform_step_History_ID_32(){
	clear_outputs_History_ID_32();
	noval_History_ID_55 = noval_Output_ID_45025;
	if (!noval_Output_ID_45025) {
		History_ID_55 = Output_ID_45025;
	}
	
	return;
	
}
