/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/Lane_Keeping_ID_8424.h"

GEN_TYPE_DriverAssistanceEvents DACommand_ID_8452;

GEN_TYPE_boolean noval_DACommand_ID_8452;

GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_10393;

GEN_TYPE_boolean noval_DA_TurnOff_ID_10393;

GEN_TYPE_On_Off_States laneKeep_ID_8468;

GEN_TYPE_boolean noval_laneKeep_ID_8468;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Pressed_ID_45574();

static GEN_TYPE_boolean fire_transition_Enabled_ID_45578();

static GEN_TYPE_boolean fire_transition_Pressed_ID_45582();

static GEN_TYPE_boolean fire_transition_Disabled_ID_45586();

static GEN_TYPE_boolean fire_transition_ForceOff_ID_45648();

static GEN_TYPE_boolean fire_state_LK_Off_ID_45548();

static GEN_TYPE_boolean fire_state_LK_On_ID_45554();

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45560();

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45566();

void clear_inputs_Lane_Keeping_ID_8424(){
	noval_DACommand_ID_8452 = true;
	noval_DA_TurnOff_ID_10393 = true;
}

void clear_outputs_Lane_Keeping_ID_8424(){
	noval_laneKeep_ID_8468 = true;
}

void init_Lane_Keeping_ID_8424(){
	noval_laneKeep_ID_8468 = true;
	current_state = 45548;
}

void perform_step_Lane_Keeping_ID_8424(){
	clear_outputs_Lane_Keeping_ID_8424();
	if (current_state == 45566) {
		fire_state_Button_unleashed_ID_45566();
	}
	else {
		if (current_state == 45560) {
			fire_state_Button_unleashed_ID_45560();
		}
		else {
			if (current_state == 45554) {
				fire_state_LK_On_ID_45554();
			}
			else {
				if (current_state == 45548) {
					fire_state_LK_Off_ID_45548();
				}
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Pressed_ID_45574(){
	if (!(noval_DACommand_ID_8452 == true) && DACommand_ID_8452.laneKeep == pressed()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = Off();
		
		current_state = 45560;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Enabled_ID_45578(){
	if (!(noval_DACommand_ID_8452 == true) && DACommand_ID_8452.laneKeep == notPressed()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = On();
		
		current_state = 45554;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Pressed_ID_45582(){
	if (!(noval_DACommand_ID_8452 == true) && DACommand_ID_8452.laneKeep == pressed()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = On();
		
		current_state = 45566;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Disabled_ID_45586(){
	if (!(noval_DACommand_ID_8452 == true) && DACommand_ID_8452.laneKeep == notPressed()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = Off();
		
		current_state = 45548;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_ForceOff_ID_45648(){
	if (!(noval_DA_TurnOff_ID_10393 == true) && DA_TurnOff_ID_10393.laneKeep == true) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = Off();
		
		current_state = 45548;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_LK_Off_ID_45548(){
	if (!fire_transition_Pressed_ID_45574()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = Off();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_LK_On_ID_45554(){
	if (!(fire_transition_Pressed_ID_45582() || fire_transition_ForceOff_ID_45648())) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = On();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45560(){
	if (!fire_transition_Enabled_ID_45578()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = Off();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45566(){
	if (!fire_transition_Disabled_ID_45586()) {
		noval_laneKeep_ID_8468 = false;
		laneKeep_ID_8468 = On();
		
	}
	return true;
}
