/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:08 CEST 2019 */
#include "inc-gen/Lane_Warning_Rumble_ID_17219.h"

GEN_TYPE_boolean RumbleLW_ID_17250;

GEN_TYPE_boolean noval_RumbleLW_ID_17250;

GEN_TYPE_int RumbleLW_Out_ID_29215;

GEN_TYPE_boolean noval_RumbleLW_Out_ID_29215;

static GEN_TYPE_int current_state;

static GEN_TYPE_int counter;

static GEN_TYPE_int scratch_paper_counter;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17239();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17241();

static GEN_TYPE_boolean fire_state_Init_ID_17226();

static GEN_TYPE_boolean fire_state_State_ID_17231();

void clear_inputs_Lane_Warning_Rumble_ID_17219(){
	noval_RumbleLW_ID_17250 = true;
}

void clear_outputs_Lane_Warning_Rumble_ID_17219(){
	noval_RumbleLW_Out_ID_29215 = true;
}

void init_Lane_Warning_Rumble_ID_17219(){
	noval_RumbleLW_Out_ID_29215 = true;
	current_state = 17226;
	counter = 0;
	scratch_paper_counter = 0;
}

void perform_step_Lane_Warning_Rumble_ID_17219(){
	clear_outputs_Lane_Warning_Rumble_ID_17219();
	if (current_state == 17231) {
		fire_state_State_ID_17231();
	}
	else {
		if (current_state == 17226) {
			fire_state_Init_ID_17226();
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	counter = scratch_paper_counter;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17239(){
	if (!(noval_RumbleLW_ID_17250 == true) && RumbleLW_ID_17250) {
		noval_RumbleLW_Out_ID_29215 = false;
		RumbleLW_Out_ID_29215 = 0;
		
		current_state = 17231;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_17241(){
	if ((noval_RumbleLW_ID_17250 == true || !RumbleLW_ID_17250) && counter >= 20) {
		noval_RumbleLW_Out_ID_29215 = false;
		RumbleLW_Out_ID_29215 = 0;
		
		current_state = 17226;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_17226(){
	if (!fire_transition_Transition_Segment_ID_17239()) {
		noval_RumbleLW_Out_ID_29215 = false;
		RumbleLW_Out_ID_29215 = 0;
		
		scratch_paper_counter = 0;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_State_ID_17231(){
	if (!fire_transition_Transition_Segment_ID_17241()) {
		noval_RumbleLW_Out_ID_29215 = false;
		RumbleLW_Out_ID_29215 = RUMBLE_MAX();
		
		scratch_paper_counter = counter + 1;
	}
	return true;
}
