/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:08 CEST 2019 */
#include "inc-gen/Last_Error_ID_16099.h"

GEN_TYPE_double LastErrorOut_ID_16128;

GEN_TYPE_boolean noval_LastErrorOut_ID_16128;

GEN_TYPE_double LastErrorIn_ID_16370;

GEN_TYPE_boolean noval_LastErrorIn_ID_16370;

void clear_inputs_Last_Error_ID_16099(){
	noval_LastErrorOut_ID_16128 = true;
}

void clear_outputs_Last_Error_ID_16099(){
	noval_LastErrorIn_ID_16370 = true;
}

void init_Last_Error_ID_16099(){
	noval_LastErrorIn_ID_16370 = true;
}

void perform_step_Last_Error_ID_16099(){
	clear_outputs_Last_Error_ID_16099();
	noval_LastErrorIn_ID_16370 = noval_LastErrorOut_ID_16128;
	if (!noval_LastErrorOut_ID_16128) {
		LastErrorIn_ID_16370 = LastErrorOut_ID_16128;
	}
	
	return;
	
}
