/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/LK_Coordinator_ID_15951.h"

GEN_TYPE_int SteeringCommand_ID_15969;

GEN_TYPE_boolean noval_SteeringCommand_ID_15969;

GEN_TYPE_double SteeringAngleRegulated_ID_15978;

GEN_TYPE_boolean noval_SteeringAngleRegulated_ID_15978;

GEN_TYPE_double Velocity_ID_44989;

GEN_TYPE_boolean noval_Velocity_ID_44989;

GEN_TYPE_double LastSteeringAngle_ID_45010;

GEN_TYPE_boolean noval_LastSteeringAngle_ID_45010;

GEN_TYPE_double SteeringAngle_ID_44999;

GEN_TYPE_boolean noval_SteeringAngle_ID_44999;

void clear_inputs_LK_Coordinator_ID_15951(){
	noval_SteeringCommand_ID_15969 = true;
	noval_SteeringAngleRegulated_ID_15978 = true;
	noval_Velocity_ID_44989 = true;
	noval_LastSteeringAngle_ID_45010 = true;
}

void clear_outputs_LK_Coordinator_ID_15951(){
	noval_SteeringAngle_ID_44999 = true;
}

void init_LK_Coordinator_ID_15951(){
	noval_SteeringAngle_ID_44999 = true;
}

void perform_step_LK_Coordinator_ID_15951(){
	clear_outputs_LK_Coordinator_ID_15951();
	if (noval_SteeringCommand_ID_15969 == true || noval_SteeringAngleRegulated_ID_15978 == true) {
		noval_SteeringAngle_ID_44999 = true;
		return;
	}
	if (noval_SteeringCommand_ID_15969 == false && SteeringCommand_ID_15969 == 1) {
		noval_SteeringAngle_ID_44999 = noval_SteeringAngleRegulated_ID_15978;
		if (!noval_SteeringAngleRegulated_ID_15978) {
			SteeringAngle_ID_44999 = SteeringAngleRegulated_ID_15978;
		}
		
	}
	else {
		if (noval_SteeringCommand_ID_15969 == false && SteeringCommand_ID_15969 == 2) {
			noval_SteeringAngle_ID_44999 = false;
			SteeringAngle_ID_44999 = -1000.0;
			
		}
		else {
			noval_SteeringAngle_ID_44999 = false;
			SteeringAngle_ID_44999 = -2000.0;
			
		}
	}
	return;
	
}
