/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/R1_ID_13442.h"

GEN_TYPE_int ButtonR1In_ID_32557;

GEN_TYPE_boolean noval_ButtonR1In_ID_32557;

GEN_TYPE_KeyEvent ButtonR1Out_ID_32490;

GEN_TYPE_boolean noval_ButtonR1Out_ID_32490;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_13461();

static GEN_TYPE_boolean fire_transition_Release_ID_13463();

static GEN_TYPE_boolean fire_state_Released_ID_13449();

static GEN_TYPE_boolean fire_state_Pressed_ID_13454();

void clear_inputs_R1_ID_13442(){
	noval_ButtonR1In_ID_32557 = true;
}

void clear_outputs_R1_ID_13442(){
	noval_ButtonR1Out_ID_32490 = true;
}

void init_R1_ID_13442(){
	noval_ButtonR1Out_ID_32490 = true;
	current_state = 13449;
}

void perform_step_R1_ID_13442(){
	clear_outputs_R1_ID_13442();
	if (current_state == 13454) {
		fire_state_Pressed_ID_13454();
	}
	else {
		if (current_state == 13449) {
			fire_state_Released_ID_13449();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_13461(){
	if (noval_ButtonR1In_ID_32557 == false && ButtonR1In_ID_32557 == 1) {
		noval_ButtonR1Out_ID_32490 = false;
		ButtonR1Out_ID_32490 = pressed();
		
		current_state = 13454;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_13463(){
	if (noval_ButtonR1In_ID_32557 == true || noval_ButtonR1In_ID_32557 == false && ButtonR1In_ID_32557 == 0) {
		noval_ButtonR1Out_ID_32490 = false;
		ButtonR1Out_ID_32490 = notPressed();
		
		current_state = 13449;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_13449(){
	if (!fire_transition_Press_ID_13461()) {
		noval_ButtonR1Out_ID_32490 = false;
		ButtonR1Out_ID_32490 = notPressed();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_13454(){
	if (!fire_transition_Release_ID_13463()) {
		noval_ButtonR1Out_ID_32490 = false;
		ButtonR1Out_ID_32490 = pressed();
		
	}
	return true;
}
