/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/R2_ID_13554.h"

GEN_TYPE_int In_ID_13579;

GEN_TYPE_boolean noval_In_ID_13579;

GEN_TYPE_int Out_ID_13577;

GEN_TYPE_boolean noval_Out_ID_13577;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_13573();

static GEN_TYPE_boolean fire_transition_Release_ID_13575();

static GEN_TYPE_boolean fire_state_Released_ID_13561();

static GEN_TYPE_boolean fire_state_Pressed_ID_13566();

void clear_inputs_R2_ID_13554(){
	noval_In_ID_13579 = true;
}

void clear_outputs_R2_ID_13554(){
	noval_Out_ID_13577 = true;
}

void init_R2_ID_13554(){
	noval_Out_ID_13577 = true;
	current_state = 13561;
}

void perform_step_R2_ID_13554(){
	clear_outputs_R2_ID_13554();
	if (current_state == 13566) {
		fire_state_Pressed_ID_13566();
	}
	else {
		if (current_state == 13561) {
			fire_state_Released_ID_13561();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_13573(){
	if (noval_In_ID_13579 == false && In_ID_13579 == 1) {
		noval_Out_ID_13577 = false;
		Out_ID_13577 = 1;
		
		current_state = 13566;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_13575(){
	if (noval_In_ID_13579 == true || noval_In_ID_13579 == false && In_ID_13579 == 0) {
		noval_Out_ID_13577 = false;
		Out_ID_13577 = 0;
		
		current_state = 13561;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_13561(){
	if (!fire_transition_Press_ID_13573()) {
		noval_Out_ID_13577 = true;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_13566(){
	if (!fire_transition_Release_ID_13575()) {
		noval_Out_ID_13577 = true;
	}
	return true;
}
