/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:10:07 CEST 2019 */
#include "inc-gen/V2V_Send_ID_22682.h"

GEN_TYPE_MessageFuse sendFuse_ID_22740;

GEN_TYPE_boolean noval_sendFuse_ID_22740;

GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_22747;

GEN_TYPE_boolean noval_sendLeaderHB_ID_22747;

GEN_TYPE_MessageLeave sendLeave_ID_22754;

GEN_TYPE_boolean noval_sendLeave_ID_22754;

GEN_TYPE_MessageNewLeader sendNewLeader_ID_22761;

GEN_TYPE_boolean noval_sendNewLeader_ID_22761;

GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_22768;

GEN_TYPE_boolean noval_sendPlatoonMessage_ID_22768;

GEN_TYPE_MessageSplit sendSplit_ID_22775;

GEN_TYPE_boolean noval_sendSplit_ID_22775;

GEN_TYPE_MessageFollower sendFollowerMessage_ID_22782;

GEN_TYPE_boolean noval_sendFollowerMessage_ID_22782;

GEN_TYPE_MessageHandshake sendHandshake_ID_28271;

GEN_TYPE_boolean noval_sendHandshake_ID_28271;

GEN_TYPE_MessageSplit sendSplitOut_ID_22689;

GEN_TYPE_boolean noval_sendSplitOut_ID_22689;

GEN_TYPE_MessageNewLeader sendNewLeaderOut_ID_22696;

GEN_TYPE_boolean noval_sendNewLeaderOut_ID_22696;

GEN_TYPE_MessageFuse sendFuseOut_ID_22703;

GEN_TYPE_boolean noval_sendFuseOut_ID_22703;

GEN_TYPE_MessageFollower sendFollowerMessageOut_ID_22710;

GEN_TYPE_boolean noval_sendFollowerMessageOut_ID_22710;

GEN_TYPE_MessagePlatoon sendPlatoonMessageOut_ID_22717;

GEN_TYPE_boolean noval_sendPlatoonMessageOut_ID_22717;

GEN_TYPE_MessageLeave sendLeaveOut_ID_22724;

GEN_TYPE_boolean noval_sendLeaveOut_ID_22724;

GEN_TYPE_MessageLeaderHB sendLeaderHBOut_ID_22731;

GEN_TYPE_boolean noval_sendLeaderHBOut_ID_22731;

GEN_TYPE_MessageHandshake sendHandshakeOut_ID_28260;

GEN_TYPE_boolean noval_sendHandshakeOut_ID_28260;

void clear_inputs_V2V_Send_ID_22682(){
	noval_sendFuse_ID_22740 = true;
	noval_sendLeaderHB_ID_22747 = true;
	noval_sendLeave_ID_22754 = true;
	noval_sendNewLeader_ID_22761 = true;
	noval_sendPlatoonMessage_ID_22768 = true;
	noval_sendSplit_ID_22775 = true;
	noval_sendFollowerMessage_ID_22782 = true;
	noval_sendHandshake_ID_28271 = true;
}

void clear_outputs_V2V_Send_ID_22682(){
	noval_sendSplitOut_ID_22689 = true;
	noval_sendNewLeaderOut_ID_22696 = true;
	noval_sendFuseOut_ID_22703 = true;
	noval_sendFollowerMessageOut_ID_22710 = true;
	noval_sendPlatoonMessageOut_ID_22717 = true;
	noval_sendLeaveOut_ID_22724 = true;
	noval_sendLeaderHBOut_ID_22731 = true;
	noval_sendHandshakeOut_ID_28260 = true;
}

void init_V2V_Send_ID_22682(){
	noval_sendSplitOut_ID_22689 = true;
	noval_sendNewLeaderOut_ID_22696 = true;
	noval_sendFuseOut_ID_22703 = true;
	noval_sendFollowerMessageOut_ID_22710 = true;
	noval_sendPlatoonMessageOut_ID_22717 = true;
	noval_sendLeaveOut_ID_22724 = true;
	noval_sendLeaderHBOut_ID_22731 = true;
	noval_sendHandshakeOut_ID_28260 = true;
}

void perform_step_V2V_Send_ID_22682(){
	clear_outputs_V2V_Send_ID_22682();
	if (!(noval_sendFuse_ID_22740 == true)) {
		noval_sendFuseOut_ID_22703 = noval_sendFuse_ID_22740;
		if (!noval_sendFuse_ID_22740) {
			sendFuseOut_ID_22703 = sendFuse_ID_22740;
		}
		
	}
	if (!(noval_sendLeaderHB_ID_22747 == true)) {
		noval_sendLeaderHBOut_ID_22731 = noval_sendLeaderHB_ID_22747;
		if (!noval_sendLeaderHB_ID_22747) {
			sendLeaderHBOut_ID_22731 = sendLeaderHB_ID_22747;
		}
		
	}
	if (!(noval_sendLeave_ID_22754 == true)) {
		noval_sendLeaveOut_ID_22724 = noval_sendLeave_ID_22754;
		if (!noval_sendLeave_ID_22754) {
			sendLeaveOut_ID_22724 = sendLeave_ID_22754;
		}
		
	}
	if (!(noval_sendNewLeader_ID_22761 == true)) {
		noval_sendNewLeaderOut_ID_22696 = noval_sendNewLeader_ID_22761;
		if (!noval_sendNewLeader_ID_22761) {
			sendNewLeaderOut_ID_22696 = sendNewLeader_ID_22761;
		}
		
	}
	if (!(noval_sendPlatoonMessage_ID_22768 == true)) {
		noval_sendPlatoonMessageOut_ID_22717 = noval_sendPlatoonMessage_ID_22768;
		if (!noval_sendPlatoonMessage_ID_22768) {
			sendPlatoonMessageOut_ID_22717 = sendPlatoonMessage_ID_22768;
		}
		
	}
	if (!(noval_sendSplit_ID_22775 == true)) {
		noval_sendSplitOut_ID_22689 = noval_sendSplit_ID_22775;
		if (!noval_sendSplit_ID_22775) {
			sendSplitOut_ID_22689 = sendSplit_ID_22775;
		}
		
	}
	if (!(noval_sendFollowerMessage_ID_22782 == true)) {
		noval_sendFollowerMessageOut_ID_22710 = noval_sendFollowerMessage_ID_22782;
		if (!noval_sendFollowerMessage_ID_22782) {
			sendFollowerMessageOut_ID_22710 = sendFollowerMessage_ID_22782;
		}
		
	}
	if (!(noval_sendHandshake_ID_28271 == true)) {
		noval_sendHandshakeOut_ID_28260 = noval_sendHandshake_ID_28271;
		if (!noval_sendHandshake_ID_28271) {
			sendHandshakeOut_ID_28260 = sendHandshake_ID_28271;
		}
		
	}
	return;
	
}
