/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_ACC_Error_Adjustment_ID_44627_h
#define __HEADER_ACC_Error_Adjustment_ID_44627_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Error_ID_44636;

extern GEN_TYPE_boolean noval_Error_ID_44636;

extern GEN_TYPE_double Error_adjusted_ID_44641;

extern GEN_TYPE_boolean noval_Error_adjusted_ID_44641;

extern void clear_inputs_ACC_Error_Adjustment_ID_44627();

extern void clear_outputs_ACC_Error_Adjustment_ID_44627();

extern void init_ACC_Error_Adjustment_ID_44627();

extern void perform_step_ACC_Error_Adjustment_ID_44627();

#endif // __HEADER_ACC_Error_Adjustment_ID_44627_h
