/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Aggregate_ID_8429_h
#define __HEADER_Aggregate_ID_8429_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_On_Off_States acc_ID_8461;

extern GEN_TYPE_boolean noval_acc_ID_8461;

extern GEN_TYPE_On_Off_States laneKeep_ID_8470;

extern GEN_TYPE_boolean noval_laneKeep_ID_8470;

extern GEN_TYPE_DriverAssistanceEvents DACommand_ID_44167;

extern GEN_TYPE_boolean noval_DACommand_ID_44167;

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_8606;

extern GEN_TYPE_boolean noval_DA_States_ID_8606;

extern void clear_inputs_Aggregate_ID_8429();

extern void clear_outputs_Aggregate_ID_8429();

extern void init_Aggregate_ID_8429();

extern void perform_step_Aggregate_ID_8429();

#endif // __HEADER_Aggregate_ID_8429_h
