/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_BackLightController_ID_19416_h
#define __HEADER_BackLightController_ID_19416_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double BrakePedal_ID_19466;

extern GEN_TYPE_boolean noval_BrakePedal_ID_19466;

extern GEN_TYPE_RGBColor BlinkLeft_ID_19539;

extern GEN_TYPE_boolean noval_BlinkLeft_ID_19539;

extern GEN_TYPE_RGBColor BlinkRight_ID_19544;

extern GEN_TYPE_boolean noval_BlinkRight_ID_19544;

extern GEN_TYPE_RGBColor ColorBackLeft_ID_19483;

extern GEN_TYPE_boolean noval_ColorBackLeft_ID_19483;

extern GEN_TYPE_RGBColor ColorBackRight_ID_19488;

extern GEN_TYPE_boolean noval_ColorBackRight_ID_19488;

extern void clear_inputs_BackLightController_ID_19416();

extern void clear_outputs_BackLightController_ID_19416();

extern void init_BackLightController_ID_19416();

extern void perform_step_BackLightController_ID_19416();

#endif // __HEADER_BackLightController_ID_19416_h
