/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Boundary_check_ID_7172_h
#define __HEADER_Boundary_check_ID_7172_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Value_ID_7188;

extern GEN_TYPE_boolean noval_Value_ID_7188;

extern GEN_TYPE_double MinValue_ID_19737;

extern GEN_TYPE_boolean noval_MinValue_ID_19737;

extern GEN_TYPE_double MaxValue_ID_19742;

extern GEN_TYPE_boolean noval_MaxValue_ID_19742;

extern GEN_TYPE_double TargetVelocity_ID_19717;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_19717;

extern GEN_TYPE_boolean Shutdown_ID_19722;

extern GEN_TYPE_boolean noval_Shutdown_ID_19722;

extern GEN_TYPE_double OutputValue_ID_19730;

extern GEN_TYPE_boolean noval_OutputValue_ID_19730;

extern void clear_inputs_Boundary_check_ID_7172();

extern void clear_outputs_Boundary_check_ID_7172();

extern void init_Boundary_check_ID_7172();

extern void perform_step_Boundary_check_ID_7172();

#endif // __HEADER_Boundary_check_ID_7172_h
