/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_CheckMode_ID_53842_h
#define __HEADER_CheckMode_ID_53842_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceCommands DA_StatesIn_ID_53850;

extern GEN_TYPE_boolean noval_DA_StatesIn_ID_53850;

extern GEN_TYPE_boolean platooningOff_ID_53857;

extern GEN_TYPE_boolean noval_platooningOff_ID_53857;

extern GEN_TYPE_DriverAssistanceCommands DA_StatesOut_ID_53874;

extern GEN_TYPE_boolean noval_DA_StatesOut_ID_53874;

extern void clear_inputs_CheckMode_ID_53842();

extern void clear_outputs_CheckMode_ID_53842();

extern void init_CheckMode_ID_53842();

extern void perform_step_CheckMode_ID_53842();

#endif // __HEADER_CheckMode_ID_53842_h
