/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Computation_ID_45034_h
#define __HEADER_Computation_ID_45034_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double History_ID_45042;

extern GEN_TYPE_boolean noval_History_ID_45042;

extern GEN_TYPE_double Input_ID_45044;

extern GEN_TYPE_boolean noval_Input_ID_45044;

extern GEN_TYPE_double Weight_Current_ID_45046;

extern GEN_TYPE_boolean noval_Weight_Current_ID_45046;

extern GEN_TYPE_double Output_ID_45040;

extern GEN_TYPE_boolean noval_Output_ID_45040;

extern void clear_inputs_Computation_ID_45034();

extern void clear_outputs_Computation_ID_45034();

extern void init_Computation_ID_45034();

extern void perform_step_Computation_ID_45034();

#endif // __HEADER_Computation_ID_45034_h
