/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Delay_ID_31910_h
#define __HEADER_Delay_ID_31910_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAccelerationAD_ID_31919;

extern GEN_TYPE_boolean noval_MaxAccelerationAD_ID_31919;

extern GEN_TYPE_boolean Platooning_EB_Triggered_ID_31926;

extern GEN_TYPE_boolean noval_Platooning_EB_Triggered_ID_31926;

extern GEN_TYPE_boolean platooningOff_ID_31933;

extern GEN_TYPE_boolean noval_platooningOff_ID_31933;

extern GEN_TYPE_boolean platooningOff_out_ID_31940;

extern GEN_TYPE_boolean noval_platooningOff_out_ID_31940;

extern GEN_TYPE_boolean Platooning_EB_Triggered_out_ID_31949;

extern GEN_TYPE_boolean noval_Platooning_EB_Triggered_out_ID_31949;

extern GEN_TYPE_double MaxAccelerationAD_out_ID_31958;

extern GEN_TYPE_boolean noval_MaxAccelerationAD_out_ID_31958;

extern void clear_inputs_Delay_ID_31910();

extern void clear_outputs_Delay_ID_31910();

extern void init_Delay_ID_31910();

extern void perform_step_Delay_ID_31910();

#endif // __HEADER_Delay_ID_31910_h
