/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_DriveModeFusion_ID_13838_h
#define __HEADER_DriveModeFusion_ID_13838_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int DriveModeIn_ID_13862;

extern GEN_TYPE_boolean noval_DriveModeIn_ID_13862;

extern GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13888;

extern GEN_TYPE_boolean noval_DriveModeCommands_ID_13888;

extern GEN_TYPE_DriveModeSettings DriveModeOut_ID_13866;

extern GEN_TYPE_boolean noval_DriveModeOut_ID_13866;

extern void clear_inputs_DriveModeFusion_ID_13838();

extern void clear_outputs_DriveModeFusion_ID_13838();

extern void init_DriveModeFusion_ID_13838();

extern void perform_step_DriveModeFusion_ID_13838();

#endif // __HEADER_DriveModeFusion_ID_13838_h
