/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_EB_Memory_ID_15316_h
#define __HEADER_EB_Memory_ID_15316_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Activated_ID_15341;

extern GEN_TYPE_boolean noval_Activated_ID_15341;

extern GEN_TYPE_double MaxAccelerationEB_ID_15380;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_15380;

extern GEN_TYPE_boolean RumbleEB_ID_17262;

extern GEN_TYPE_boolean noval_RumbleEB_ID_17262;

extern void clear_inputs_EB_Memory_ID_15316();

extern void clear_outputs_EB_Memory_ID_15316();

extern void init_EB_Memory_ID_15316();

extern void perform_step_EB_Memory_ID_15316();

#endif // __HEADER_EB_Memory_ID_15316_h
