/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Home_ID_13373_h
#define __HEADER_Home_ID_13373_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonHomeIn_ID_32562;

extern GEN_TYPE_boolean noval_ButtonHomeIn_ID_32562;

extern GEN_TYPE_KeyEvent ButtonHomeOut_ID_32485;

extern GEN_TYPE_boolean noval_ButtonHomeOut_ID_32485;

extern void clear_inputs_Home_ID_13373();

extern void clear_outputs_Home_ID_13373();

extern void init_Home_ID_13373();

extern void perform_step_Home_ID_13373();

#endif // __HEADER_Home_ID_13373_h
