/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Lane_Warning_ID_15516_h
#define __HEADER_Lane_Warning_ID_15516_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_LDCameraData LDCameraData_ID_15525;

extern GEN_TYPE_boolean noval_LDCameraData_ID_15525;

extern GEN_TYPE_DriveModeSettings DriveMode_ID_15622;

extern GEN_TYPE_boolean noval_DriveMode_ID_15622;

extern GEN_TYPE_double SteeringWheel_ID_16864;

extern GEN_TYPE_boolean noval_SteeringWheel_ID_16864;

extern GEN_TYPE_boolean RumbleLW_ID_15530;

extern GEN_TYPE_boolean noval_RumbleLW_ID_15530;

extern void clear_inputs_Lane_Warning_ID_15516();

extern void clear_outputs_Lane_Warning_ID_15516();

extern void init_Lane_Warning_ID_15516();

extern void perform_step_Lane_Warning_ID_15516();

#endif // __HEADER_Lane_Warning_ID_15516_h
