/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Last_Street_Width_ID_29276_h
#define __HEADER_Last_Street_Width_ID_29276_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double StreetWidthOut_ID_29289;

extern GEN_TYPE_boolean noval_StreetWidthOut_ID_29289;

extern GEN_TYPE_double StreetWidthIn_ID_29301;

extern GEN_TYPE_boolean noval_StreetWidthIn_ID_29301;

extern void clear_inputs_Last_Street_Width_ID_29276();

extern void clear_outputs_Last_Street_Width_ID_29276();

extern void init_Last_Street_Width_ID_29276();

extern void perform_step_Last_Street_Width_ID_29276();

#endif // __HEADER_Last_Street_Width_ID_29276_h
