/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Last_Error_ID_16099_h
#define __HEADER_Last_Error_ID_16099_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double LastErrorOut_ID_16128;

extern GEN_TYPE_boolean noval_LastErrorOut_ID_16128;

extern GEN_TYPE_double LastErrorIn_ID_16370;

extern GEN_TYPE_boolean noval_LastErrorIn_ID_16370;

extern void clear_inputs_Last_Error_ID_16099();

extern void clear_outputs_Last_Error_ID_16099();

extern void init_Last_Error_ID_16099();

extern void perform_step_Last_Error_ID_16099();

#endif // __HEADER_Last_Error_ID_16099_h
