/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_LastSensor_Memory_ID_7683_h
#define __HEADER_LastSensor_Memory_ID_7683_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double LastDistanceFrontOut_ID_6965;

extern GEN_TYPE_boolean noval_LastDistanceFrontOut_ID_6965;

extern GEN_TYPE_double LastVelocityDiffOut_ID_7777;

extern GEN_TYPE_boolean noval_LastVelocityDiffOut_ID_7777;

extern GEN_TYPE_double LastDistanceFrontIn_ID_7688;

extern GEN_TYPE_boolean noval_LastDistanceFrontIn_ID_7688;

extern GEN_TYPE_double LastVelocityDiffIn_ID_7784;

extern GEN_TYPE_boolean noval_LastVelocityDiffIn_ID_7784;

extern void clear_inputs_LastSensor_Memory_ID_7683();

extern void clear_outputs_LastSensor_Memory_ID_7683();

extern void init_LastSensor_Memory_ID_7683();

extern void perform_step_LastSensor_Memory_ID_7683();

#endif // __HEADER_LastSensor_Memory_ID_7683_h
