/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Mapping_ID_6657_h
#define __HEADER_Mapping_ID_6657_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double DistanceToFrontLaser_ID_24653;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_24653;

extern GEN_TYPE_double ButtonL2_ID_14962;

extern GEN_TYPE_boolean noval_ButtonL2_ID_14962;

extern GEN_TYPE_KeyEvent ButtonR1_ID_13363;

extern GEN_TYPE_boolean noval_ButtonR1_ID_13363;

extern GEN_TYPE_double ButtonR2_ID_14969;

extern GEN_TYPE_boolean noval_ButtonR2_ID_14969;

extern GEN_TYPE_double LeftStick_X_ID_11980;

extern GEN_TYPE_boolean noval_LeftStick_X_ID_11980;

extern GEN_TYPE_double RightStick_X_ID_11985;

extern GEN_TYPE_boolean noval_RightStick_X_ID_11985;

extern GEN_TYPE_double RightStick_Y_ID_11990;

extern GEN_TYPE_boolean noval_RightStick_Y_ID_11990;

extern GEN_TYPE_KeyEvent ButtonL1_ID_13349;

extern GEN_TYPE_boolean noval_ButtonL1_ID_13349;

extern GEN_TYPE_double VelocityIn_ID_31865;

extern GEN_TYPE_boolean noval_VelocityIn_ID_31865;

extern GEN_TYPE_boolean FrontObstacleCommand_ID_10653;

extern GEN_TYPE_boolean noval_FrontObstacleCommand_ID_10653;

extern GEN_TYPE_double DistanceToFrontObstacle_ID_10660;

extern GEN_TYPE_boolean noval_DistanceToFrontObstacle_ID_10660;

extern GEN_TYPE_KeyEvent ButtonHome_ID_14630;

extern GEN_TYPE_boolean noval_ButtonHome_ID_14630;

extern GEN_TYPE_KeyEvent ButtonSelect_ID_14639;

extern GEN_TYPE_boolean noval_ButtonSelect_ID_14639;

extern GEN_TYPE_double LeftStick_Y_ID_14675;

extern GEN_TYPE_boolean noval_LeftStick_Y_ID_14675;

extern GEN_TYPE_double LD_Distance_Left_filtered_ID_45081;

extern GEN_TYPE_boolean noval_LD_Distance_Left_filtered_ID_45081;

extern GEN_TYPE_double LD_Distance_Right_filtered_ID_45086;

extern GEN_TYPE_boolean noval_LD_Distance_Right_filtered_ID_45086;

extern GEN_TYPE_boolean LD_present_left_ID_15769;

extern GEN_TYPE_boolean noval_LD_present_left_ID_15769;

extern GEN_TYPE_boolean LD_present_right_ID_15776;

extern GEN_TYPE_boolean noval_LD_present_right_ID_15776;

extern GEN_TYPE_double LD_Orientation_ID_15783;

extern GEN_TYPE_boolean noval_LD_Orientation_ID_15783;

extern GEN_TYPE_double DistanceToFrontUS_ID_24660;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_ID_24660;

extern GEN_TYPE_KeyEvent DPadLeft_ID_18663;

extern GEN_TYPE_boolean noval_DPadLeft_ID_18663;

extern GEN_TYPE_KeyEvent DPadRight_ID_18670;

extern GEN_TYPE_boolean noval_DPadRight_ID_18670;

extern GEN_TYPE_KeyEvent DPadUp_ID_19940;

extern GEN_TYPE_boolean noval_DPadUp_ID_19940;

extern GEN_TYPE_KeyEvent DPadDown_ID_19947;

extern GEN_TYPE_boolean noval_DPadDown_ID_19947;

extern GEN_TYPE_boolean LD_server_connected_ID_31291;

extern GEN_TYPE_boolean noval_LD_server_connected_ID_31291;

extern GEN_TYPE_int LD_server_lastupdate_ID_31298;

extern GEN_TYPE_boolean noval_LD_server_lastupdate_ID_31298;

extern GEN_TYPE_boolean LD_curve_detected_ID_31305;

extern GEN_TYPE_boolean noval_LD_curve_detected_ID_31305;

extern GEN_TYPE_double LD_curve_radius_ID_31312;

extern GEN_TYPE_boolean noval_LD_curve_radius_ID_31312;

extern GEN_TYPE_boolean LD_rover_detected_ID_31319;

extern GEN_TYPE_boolean noval_LD_rover_detected_ID_31319;

extern GEN_TYPE_int LD_rover_id_ID_31326;

extern GEN_TYPE_boolean noval_LD_rover_id_ID_31326;

extern GEN_TYPE_int LD_rover_distance_ID_31333;

extern GEN_TYPE_boolean noval_LD_rover_distance_ID_31333;

extern GEN_TYPE_KeyEvent ButtonStart_ID_44452;

extern GEN_TYPE_boolean noval_ButtonStart_ID_44452;

extern GEN_TYPE_double LD_Distance_Left_ID_45340;

extern GEN_TYPE_boolean noval_LD_Distance_Left_ID_45340;

extern GEN_TYPE_double LD_Distance_Right_ID_45347;

extern GEN_TYPE_boolean noval_LD_Distance_Right_ID_45347;

extern GEN_TYPE_double SteeringWheel_ID_6665;

extern GEN_TYPE_boolean noval_SteeringWheel_ID_6665;

extern GEN_TYPE_int GearShift_ID_15027;

extern GEN_TYPE_boolean noval_GearShift_ID_15027;

extern GEN_TYPE_double BrakePedal_ID_6693;

extern GEN_TYPE_boolean noval_BrakePedal_ID_6693;

extern GEN_TYPE_double GasPedal_ID_6700;

extern GEN_TYPE_boolean noval_GasPedal_ID_6700;

extern GEN_TYPE_double DistanceFront_ID_6707;

extern GEN_TYPE_boolean noval_DistanceFront_ID_6707;

extern GEN_TYPE_double Velocity_ID_6714;

extern GEN_TYPE_boolean noval_Velocity_ID_6714;

extern GEN_TYPE_double AccelerationOut_ID_6721;

extern GEN_TYPE_boolean noval_AccelerationOut_ID_6721;

extern GEN_TYPE_DriverAssistanceEvents DACommand_ID_8662;

extern GEN_TYPE_boolean noval_DACommand_ID_8662;

extern GEN_TYPE_LDCameraData LDCameraData_ID_15459;

extern GEN_TYPE_boolean noval_LDCameraData_ID_15459;

extern GEN_TYPE_KeyEvent ButtonEBOff_ID_17707;

extern GEN_TYPE_boolean noval_ButtonEBOff_ID_17707;

extern GEN_TYPE_boolean EnableRightSignal_ID_18596;

extern GEN_TYPE_boolean noval_EnableRightSignal_ID_18596;

extern GEN_TYPE_boolean EnableLeftSignal_ID_18603;

extern GEN_TYPE_boolean noval_EnableLeftSignal_ID_18603;

extern GEN_TYPE_AutonomousDrivingEvents ADCommand_ID_19966;

extern GEN_TYPE_boolean noval_ADCommand_ID_19966;

extern void clear_inputs_Mapping_ID_6657();

extern void clear_outputs_Mapping_ID_6657();

extern void init_Mapping_ID_6657();

extern void perform_step_Mapping_ID_6657();

#endif // __HEADER_Mapping_ID_6657_h
