/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Max_Velocity_Diff_ID_7820_h
#define __HEADER_Max_Velocity_Diff_ID_7820_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAcceleration_ID_7829;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_7829;

extern GEN_TYPE_double MaxVelocityDiff_ID_11049;

extern GEN_TYPE_boolean noval_MaxVelocityDiff_ID_11049;

extern void clear_inputs_Max_Velocity_Diff_ID_7820();

extern void clear_outputs_Max_Velocity_Diff_ID_7820();

extern void init_Max_Velocity_Diff_ID_7820();

extern void perform_step_Max_Velocity_Diff_ID_7820();

#endif // __HEADER_Max_Velocity_Diff_ID_7820_h
