/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Mem_ID_12576_h
#define __HEADER_Mem_ID_12576_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriveMode StateNew_ID_12587;

extern GEN_TYPE_boolean noval_StateNew_ID_12587;

extern GEN_TYPE_DriveMode StateOld_ID_12594;

extern GEN_TYPE_boolean noval_StateOld_ID_12594;

extern void clear_inputs_Mem_ID_12576();

extern void clear_outputs_Mem_ID_12576();

extern void init_Mem_ID_12576();

extern void perform_step_Mem_ID_12576();

#endif // __HEADER_Mem_ID_12576_h
