/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_merge_TurnOffs_ID_16204_h
#define __HEADER_merge_TurnOffs_ID_16204_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean ACC_TurnOff_ID_16220;

extern GEN_TYPE_boolean noval_ACC_TurnOff_ID_16220;

extern GEN_TYPE_boolean LK_TurnOff_ID_16229;

extern GEN_TYPE_boolean noval_LK_TurnOff_ID_16229;

extern GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_16211;

extern GEN_TYPE_boolean noval_DA_TurnOff_ID_16211;

extern void clear_inputs_merge_TurnOffs_ID_16204();

extern void clear_outputs_merge_TurnOffs_ID_16204();

extern void init_merge_TurnOffs_ID_16204();

extern void perform_step_merge_TurnOffs_ID_16204();

#endif // __HEADER_merge_TurnOffs_ID_16204_h
