/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Message_Sender_ID_46097_h
#define __HEADER_Message_Sender_ID_46097_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_PlatoonInformation platoonInfo_ID_47361;

extern GEN_TYPE_boolean noval_platoonInfo_ID_47361;

extern GEN_TYPE_Message_Type sendMessageType_ID_47366;

extern GEN_TYPE_boolean noval_sendMessageType_ID_47366;

extern GEN_TYPE_int OldCount_ID_54375;

extern GEN_TYPE_boolean noval_OldCount_ID_54375;

extern GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_46111;

extern GEN_TYPE_boolean noval_sendPlatoonMessage_ID_46111;

extern GEN_TYPE_MessageFuse sendFuse_ID_47011;

extern GEN_TYPE_boolean noval_sendFuse_ID_47011;

extern GEN_TYPE_MessageHandshake sendHandshake_ID_48439;

extern GEN_TYPE_boolean noval_sendHandshake_ID_48439;

extern GEN_TYPE_MessageSplit sendSplit_ID_50500;

extern GEN_TYPE_boolean noval_sendSplit_ID_50500;

extern GEN_TYPE_MessageLeave sendLeave_ID_50507;

extern GEN_TYPE_boolean noval_sendLeave_ID_50507;

extern GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_54029;

extern GEN_TYPE_boolean noval_sendLeaderHB_ID_54029;

extern GEN_TYPE_int NewCount_ID_54366;

extern GEN_TYPE_boolean noval_NewCount_ID_54366;

extern GEN_TYPE_MessageNewLeader sendNewLeader_ID_57722;

extern GEN_TYPE_boolean noval_sendNewLeader_ID_57722;

extern GEN_TYPE_MessageFollower sendFollowerMessage_ID_57780;

extern GEN_TYPE_boolean noval_sendFollowerMessage_ID_57780;

extern void clear_inputs_Message_Sender_ID_46097();

extern void clear_outputs_Message_Sender_ID_46097();

extern void init_Message_Sender_ID_46097();

extern void perform_step_Message_Sender_ID_46097();

#endif // __HEADER_Message_Sender_ID_46097_h
