/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Message_Handler_ID_45890_h
#define __HEADER_Message_Handler_ID_45890_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_MessagePlatoon receivePlatoonMessage_ID_45898;

extern GEN_TYPE_boolean noval_receivePlatoonMessage_ID_45898;

extern GEN_TYPE_MessageFuse receiveFuse_ID_46447;

extern GEN_TYPE_boolean noval_receiveFuse_ID_46447;

extern GEN_TYPE_MessageHandshake receiveHandshake_ID_48434;

extern GEN_TYPE_boolean noval_receiveHandshake_ID_48434;

extern GEN_TYPE_MessageLeave receiveLeave_ID_50488;

extern GEN_TYPE_boolean noval_receiveLeave_ID_50488;

extern GEN_TYPE_MessageSplit receiveSplit_ID_50495;

extern GEN_TYPE_boolean noval_receiveSplit_ID_50495;

extern GEN_TYPE_MessageLeaderHB receiveLeaderHB_ID_54024;

extern GEN_TYPE_boolean noval_receiveLeaderHB_ID_54024;

extern GEN_TYPE_MessageNewLeader receiveNewLeader_ID_57717;

extern GEN_TYPE_boolean noval_receiveNewLeader_ID_57717;

extern GEN_TYPE_MessageFollower receiveFollowerMessage_ID_57769;

extern GEN_TYPE_boolean noval_receiveFollowerMessage_ID_57769;

extern GEN_TYPE_Message_Type receiveMessageType_ID_45904;

extern GEN_TYPE_boolean noval_receiveMessageType_ID_45904;

extern GEN_TYPE_PlatoonInformation platoonInfoOut_ID_46426;

extern GEN_TYPE_boolean noval_platoonInfoOut_ID_46426;

extern void clear_inputs_Message_Handler_ID_45890();

extern void clear_outputs_Message_Handler_ID_45890();

extern void init_Message_Handler_ID_45890();

extern void perform_step_Message_Handler_ID_45890();

#endif // __HEADER_Message_Handler_ID_45890_h
