/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_PlatoonInfoMem_ID_49039_h
#define __HEADER_PlatoonInfoMem_ID_49039_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_PlatoonInformation platoonStoredNew_ID_49058;

extern GEN_TYPE_boolean noval_platoonStoredNew_ID_49058;

extern GEN_TYPE_listParticipants fuseListNew_ID_54530;

extern GEN_TYPE_boolean noval_fuseListNew_ID_54530;

extern GEN_TYPE_PlatoonInformation platoonStoredOld_ID_49047;

extern GEN_TYPE_boolean noval_platoonStoredOld_ID_49047;

extern GEN_TYPE_PlatoonInformation platoonInfoOut_ID_52674;

extern GEN_TYPE_boolean noval_platoonInfoOut_ID_52674;

extern GEN_TYPE_listParticipants fuseListOld_ID_54537;

extern GEN_TYPE_boolean noval_fuseListOld_ID_54537;

extern void clear_inputs_PlatoonInfoMem_ID_49039();

extern void clear_outputs_PlatoonInfoMem_ID_49039();

extern void init_PlatoonInfoMem_ID_49039();

extern void perform_step_PlatoonInfoMem_ID_49039();

#endif // __HEADER_PlatoonInfoMem_ID_49039_h
