/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Platoon_States_ID_46545_h
#define __HEADER_Platoon_States_ID_46545_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_ADOnOffCommands Control_AD_ID_46587;

extern GEN_TYPE_boolean noval_Control_AD_ID_46587;

extern GEN_TYPE_Message_Type receiveMessageType_ID_47574;

extern GEN_TYPE_boolean noval_receiveMessageType_ID_47574;

extern GEN_TYPE_int countOld_ID_50466;

extern GEN_TYPE_boolean noval_countOld_ID_50466;

extern GEN_TYPE_boolean IsLeader_ID_53002;

extern GEN_TYPE_boolean noval_IsLeader_ID_53002;

extern GEN_TYPE_int status_ID_47693;

extern GEN_TYPE_boolean noval_status_ID_47693;

extern GEN_TYPE_PlatoonState platoonState_ID_61170;

extern GEN_TYPE_boolean noval_platoonState_ID_61170;

extern GEN_TYPE_int countNew_ID_50473;

extern GEN_TYPE_boolean noval_countNew_ID_50473;

extern GEN_TYPE_PlatoonState platoonStateCorr_ID_61177;

extern GEN_TYPE_boolean noval_platoonStateCorr_ID_61177;

extern void clear_inputs_Platoon_States_ID_46545();

extern void clear_outputs_Platoon_States_ID_46545();

extern void init_Platoon_States_ID_46545();

extern void perform_step_Platoon_States_ID_46545();

#endif // __HEADER_Platoon_States_ID_46545_h
