/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_R2_ID_13554_h
#define __HEADER_R2_ID_13554_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int In_ID_13579;

extern GEN_TYPE_boolean noval_In_ID_13579;

extern GEN_TYPE_int Out_ID_13577;

extern GEN_TYPE_boolean noval_Out_ID_13577;

extern void clear_inputs_R2_ID_13554();

extern void clear_outputs_R2_ID_13554();

extern void init_R2_ID_13554();

extern void perform_step_R2_ID_13554();

#endif // __HEADER_R2_ID_13554_h
