/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_REMOVED_ID_44654_h
#define __HEADER_REMOVED_ID_44654_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityFrontObstacleIn_ID_44670;

extern GEN_TYPE_boolean noval_VelocityFrontObstacleIn_ID_44670;

extern GEN_TYPE_double VelocityFrontObstacle_ID_44661;

extern GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_44661;

extern void clear_inputs_REMOVED_ID_44654();

extern void clear_outputs_REMOVED_ID_44654();

extern void init_REMOVED_ID_44654();

extern void perform_step_REMOVED_ID_44654();

#endif // __HEADER_REMOVED_ID_44654_h
