/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_RGB_Adapter_ID_19000_h
#define __HEADER_RGB_Adapter_ID_19000_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_RGBColor ColorBackLeft_ID_19148;

extern GEN_TYPE_boolean noval_ColorBackLeft_ID_19148;

extern GEN_TYPE_RGBColor ColorBackRight_ID_19155;

extern GEN_TYPE_boolean noval_ColorBackRight_ID_19155;

extern GEN_TYPE_int Red_Left_ID_19162;

extern GEN_TYPE_boolean noval_Red_Left_ID_19162;

extern GEN_TYPE_int Green_Left_ID_19171;

extern GEN_TYPE_boolean noval_Green_Left_ID_19171;

extern GEN_TYPE_int Blue_Left_ID_19180;

extern GEN_TYPE_boolean noval_Blue_Left_ID_19180;

extern GEN_TYPE_int Red_Right_ID_19189;

extern GEN_TYPE_boolean noval_Red_Right_ID_19189;

extern GEN_TYPE_int Green_Right_ID_19198;

extern GEN_TYPE_boolean noval_Green_Right_ID_19198;

extern GEN_TYPE_int Blue_Right_ID_19207;

extern GEN_TYPE_boolean noval_Blue_Right_ID_19207;

extern void clear_inputs_RGB_Adapter_ID_19000();

extern void clear_outputs_RGB_Adapter_ID_19000();

extern void init_RGB_Adapter_ID_19000();

extern void perform_step_RGB_Adapter_ID_19000();

#endif // __HEADER_RGB_Adapter_ID_19000_h
