/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Rumble_Delay_ID_15596_h
#define __HEADER_Rumble_Delay_ID_15596_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean RumbleLKIn_ID_30784;

extern GEN_TYPE_boolean noval_RumbleLKIn_ID_30784;

extern GEN_TYPE_boolean RumbleLK_ID_15603;

extern GEN_TYPE_boolean noval_RumbleLK_ID_15603;

extern void clear_inputs_Rumble_Delay_ID_15596();

extern void clear_outputs_Rumble_Delay_ID_15596();

extern void init_Rumble_Delay_ID_15596();

extern void perform_step_Rumble_Delay_ID_15596();

#endif // __HEADER_Rumble_Delay_ID_15596_h
