/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Speed_Change_ID_43293_h
#define __HEADER_Speed_Change_ID_43293_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_53834;

extern GEN_TYPE_boolean noval_DA_States_ID_53834;

extern GEN_TYPE_int SpeedChange_ID_44189;

extern GEN_TYPE_boolean noval_SpeedChange_ID_44189;

extern void clear_inputs_Speed_Change_ID_43293();

extern void clear_outputs_Speed_Change_ID_43293();

extern void init_Speed_Change_ID_43293();

extern void perform_step_Speed_Change_ID_43293();

#endif // __HEADER_Speed_Change_ID_43293_h
