/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Start_ID_44398_h
#define __HEADER_Start_ID_44398_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonStartIn_ID_44431;

extern GEN_TYPE_boolean noval_ButtonStartIn_ID_44431;

extern GEN_TYPE_KeyEvent ButtonStartOut_ID_44436;

extern GEN_TYPE_boolean noval_ButtonStartOut_ID_44436;

extern void clear_inputs_Start_ID_44398();

extern void clear_outputs_Start_ID_44398();

extern void init_Start_ID_44398();

extern void perform_step_Start_ID_44398();

#endif // __HEADER_Start_ID_44398_h
