/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Tick_Counter_ID_46205_h
#define __HEADER_Tick_Counter_ID_46205_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int NewCount_ID_54368;

extern GEN_TYPE_boolean noval_NewCount_ID_54368;

extern GEN_TYPE_int OldCount_ID_54373;

extern GEN_TYPE_boolean noval_OldCount_ID_54373;

extern void clear_inputs_Tick_Counter_ID_46205();

extern void clear_outputs_Tick_Counter_ID_46205();

extern void init_Tick_Counter_ID_46205();

extern void perform_step_Tick_Counter_ID_46205();

#endif // __HEADER_Tick_Counter_ID_46205_h
