/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Time_Change_ID_44217_h
#define __HEADER_Time_Change_ID_44217_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_53829;

extern GEN_TYPE_boolean noval_DA_States_ID_53829;

extern GEN_TYPE_int TimeChange_ID_44288;

extern GEN_TYPE_boolean noval_TimeChange_ID_44288;

extern void clear_inputs_Time_Change_ID_44217();

extern void clear_outputs_Time_Change_ID_44217();

extern void init_Time_Change_ID_44217();

extern void perform_step_Time_Change_ID_44217();

#endif // __HEADER_Time_Change_ID_44217_h
