/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Transit_for_Testing_ID_45252_h
#define __HEADER_Transit_for_Testing_ID_45252_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double LD_Distance_Left_ID_45262;

extern GEN_TYPE_boolean noval_LD_Distance_Left_ID_45262;

extern GEN_TYPE_double LD_Distance_Right_ID_45269;

extern GEN_TYPE_boolean noval_LD_Distance_Right_ID_45269;

extern GEN_TYPE_double LD_Left_ID_45276;

extern GEN_TYPE_boolean noval_LD_Left_ID_45276;

extern GEN_TYPE_double LD_Right_ID_45285;

extern GEN_TYPE_boolean noval_LD_Right_ID_45285;

extern void clear_inputs_Transit_for_Testing_ID_45252();

extern void clear_outputs_Transit_for_Testing_ID_45252();

extern void init_Transit_for_Testing_ID_45252();

extern void perform_step_Transit_for_Testing_ID_45252();

#endif // __HEADER_Transit_for_Testing_ID_45252_h
