/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_V2V_Send_ID_22682_h
#define __HEADER_V2V_Send_ID_22682_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_MessageFuse sendFuse_ID_22740;

extern GEN_TYPE_boolean noval_sendFuse_ID_22740;

extern GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_22747;

extern GEN_TYPE_boolean noval_sendLeaderHB_ID_22747;

extern GEN_TYPE_MessageLeave sendLeave_ID_22754;

extern GEN_TYPE_boolean noval_sendLeave_ID_22754;

extern GEN_TYPE_MessageNewLeader sendNewLeader_ID_22761;

extern GEN_TYPE_boolean noval_sendNewLeader_ID_22761;

extern GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_22768;

extern GEN_TYPE_boolean noval_sendPlatoonMessage_ID_22768;

extern GEN_TYPE_MessageSplit sendSplit_ID_22775;

extern GEN_TYPE_boolean noval_sendSplit_ID_22775;

extern GEN_TYPE_MessageFollower sendFollowerMessage_ID_22782;

extern GEN_TYPE_boolean noval_sendFollowerMessage_ID_22782;

extern GEN_TYPE_MessageHandshake sendHandshake_ID_28271;

extern GEN_TYPE_boolean noval_sendHandshake_ID_28271;

extern GEN_TYPE_MessageSplit sendSplitOut_ID_22689;

extern GEN_TYPE_boolean noval_sendSplitOut_ID_22689;

extern GEN_TYPE_MessageNewLeader sendNewLeaderOut_ID_22696;

extern GEN_TYPE_boolean noval_sendNewLeaderOut_ID_22696;

extern GEN_TYPE_MessageFuse sendFuseOut_ID_22703;

extern GEN_TYPE_boolean noval_sendFuseOut_ID_22703;

extern GEN_TYPE_MessageFollower sendFollowerMessageOut_ID_22710;

extern GEN_TYPE_boolean noval_sendFollowerMessageOut_ID_22710;

extern GEN_TYPE_MessagePlatoon sendPlatoonMessageOut_ID_22717;

extern GEN_TYPE_boolean noval_sendPlatoonMessageOut_ID_22717;

extern GEN_TYPE_MessageLeave sendLeaveOut_ID_22724;

extern GEN_TYPE_boolean noval_sendLeaveOut_ID_22724;

extern GEN_TYPE_MessageLeaderHB sendLeaderHBOut_ID_22731;

extern GEN_TYPE_boolean noval_sendLeaderHBOut_ID_22731;

extern GEN_TYPE_MessageHandshake sendHandshakeOut_ID_28260;

extern GEN_TYPE_boolean noval_sendHandshakeOut_ID_28260;

extern void clear_inputs_V2V_Send_ID_22682();

extern void clear_outputs_V2V_Send_ID_22682();

extern void init_V2V_Send_ID_22682();

extern void perform_step_V2V_Send_ID_22682();

#endif // __HEADER_V2V_Send_ID_22682_h
