/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#ifndef __HEADER_Velocity_Memory_ID_7729_h
#define __HEADER_Velocity_Memory_ID_7729_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double LastVelocityOut_ID_7740;

extern GEN_TYPE_boolean noval_LastVelocityOut_ID_7740;

extern GEN_TYPE_double LastVelocityIn_ID_7747;

extern GEN_TYPE_boolean noval_LastVelocityIn_ID_7747;

extern void clear_inputs_Velocity_Memory_ID_7729();

extern void clear_outputs_Velocity_Memory_ID_7729();

extern void init_Velocity_Memory_ID_7729();

extern void perform_step_Velocity_Memory_ID_7729();

#endif // __HEADER_Velocity_Memory_ID_7729_h
