/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/ACC_Time_Gap_ID_44268.h"

GEN_TYPE_int TimeChange_ID_44290;

GEN_TYPE_boolean noval_TimeChange_ID_44290;

GEN_TYPE_double LastTimeGap_ID_44285;

GEN_TYPE_boolean noval_LastTimeGap_ID_44285;

GEN_TYPE_boolean platooningOff_ID_50178;

GEN_TYPE_boolean noval_platooningOff_ID_50178;

GEN_TYPE_double TimeGap_ID_44677;

GEN_TYPE_boolean noval_TimeGap_ID_44677;

void clear_inputs_ACC_Time_Gap_ID_44268(){
	noval_TimeChange_ID_44290 = true;
	noval_LastTimeGap_ID_44285 = true;
	noval_platooningOff_ID_50178 = true;
}

void clear_outputs_ACC_Time_Gap_ID_44268(){
	noval_TimeGap_ID_44677 = true;
}

void init_ACC_Time_Gap_ID_44268(){
	noval_TimeGap_ID_44677 = true;
}

void perform_step_ACC_Time_Gap_ID_44268(){
	clear_outputs_ACC_Time_Gap_ID_44268();
	if (noval_LastTimeGap_ID_44285 == true) {
		noval_TimeGap_ID_44677 = false;
		TimeGap_ID_44677 = ACC_BUFFER_FACTOR();
		
	}
	else {
		if (LastTimeGap_ID_44285 + TimeChange_ID_44290 * 0.1 < 1.0) {
			noval_TimeGap_ID_44677 = false;
			TimeGap_ID_44677 = 4.0;
			
		}
		else {
			noval_TimeGap_ID_44677 = false;
			TimeGap_ID_44677 = LastTimeGap_ID_44285 + TimeChange_ID_44290 * 0.1;
			
		}
		if (!(noval_platooningOff_ID_50178 == true) && (noval_platooningOff_ID_50178 == false && platooningOff_ID_50178 == false)) {
			noval_TimeGap_ID_44677 = false;
			TimeGap_ID_44677 = 4.0;
			
		}
	}
	return;
	
}
