/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Adaptive_Cruise_Control_ID_8419.h"

GEN_TYPE_DriverAssistanceEvents DACommand_ID_8445;

GEN_TYPE_boolean noval_DACommand_ID_8445;

GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_10398;

GEN_TYPE_boolean noval_DA_TurnOff_ID_10398;

GEN_TYPE_On_Off_States acc_ID_8459;

GEN_TYPE_boolean noval_acc_ID_8459;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Pressed_ID_45486();

static GEN_TYPE_boolean fire_transition_Enabled_ID_45489();

static GEN_TYPE_boolean fire_transition_Pressed_ID_45492();

static GEN_TYPE_boolean fire_transition_Disabled_ID_45495();

static GEN_TYPE_boolean fire_transition_ForceOff_ID_45642();

static GEN_TYPE_boolean fire_state_ACC_Off_ID_45464();

static GEN_TYPE_boolean fire_state_ACC_On_ID_45469();

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45474();

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45479();

void clear_inputs_Adaptive_Cruise_Control_ID_8419(){
	noval_DACommand_ID_8445 = true;
	noval_DA_TurnOff_ID_10398 = true;
}

void clear_outputs_Adaptive_Cruise_Control_ID_8419(){
	noval_acc_ID_8459 = true;
}

void init_Adaptive_Cruise_Control_ID_8419(){
	noval_acc_ID_8459 = true;
	current_state = 45464;
}

void perform_step_Adaptive_Cruise_Control_ID_8419(){
	clear_outputs_Adaptive_Cruise_Control_ID_8419();
	if (current_state == 45479) {
		fire_state_Button_unleashed_ID_45479();
	}
	else {
		if (current_state == 45474) {
			fire_state_Button_unleashed_ID_45474();
		}
		else {
			if (current_state == 45469) {
				fire_state_ACC_On_ID_45469();
			}
			else {
				if (current_state == 45464) {
					fire_state_ACC_Off_ID_45464();
				}
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Pressed_ID_45486(){
	if (!(noval_DACommand_ID_8445 == true) && DACommand_ID_8445.acc == pressed()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = Off();
		
		current_state = 45474;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Enabled_ID_45489(){
	if (!(noval_DACommand_ID_8445 == true) && DACommand_ID_8445.acc == notPressed()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = On();
		
		current_state = 45469;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Pressed_ID_45492(){
	if (!(noval_DACommand_ID_8445 == true) && DACommand_ID_8445.acc == pressed()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = On();
		
		current_state = 45479;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Disabled_ID_45495(){
	if (!(noval_DACommand_ID_8445 == true) && DACommand_ID_8445.acc == notPressed()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = Off();
		
		current_state = 45464;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_ForceOff_ID_45642(){
	if (!(noval_DA_TurnOff_ID_10398 == true) && DA_TurnOff_ID_10398.acc == true) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = Off();
		
		current_state = 45464;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_ACC_Off_ID_45464(){
	if (!fire_transition_Pressed_ID_45486()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = Off();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_ACC_On_ID_45469(){
	if (!(fire_transition_Pressed_ID_45492() || fire_transition_ForceOff_ID_45642())) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = On();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45474(){
	if (!fire_transition_Enabled_ID_45489()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = Off();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Button_unleashed_ID_45479(){
	if (!fire_transition_Disabled_ID_45495()) {
		noval_acc_ID_8459 = false;
		acc_ID_8459 = On();
		
	}
	return true;
}
