/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/BlinkRight_ID_19411.h"

GEN_TYPE_boolean EnableRightSignal_ID_19501;

GEN_TYPE_boolean noval_EnableRightSignal_ID_19501;

GEN_TYPE_int CountTickInRight_ID_19555;

GEN_TYPE_boolean noval_CountTickInRight_ID_19555;

GEN_TYPE_RGBColor BlinkRight_ID_19542;

GEN_TYPE_boolean noval_BlinkRight_ID_19542;

GEN_TYPE_int CountTickOutRight_ID_19553;

GEN_TYPE_boolean noval_CountTickOutRight_ID_19553;

void clear_inputs_BlinkRight_ID_19411(){
	noval_EnableRightSignal_ID_19501 = true;
	noval_CountTickInRight_ID_19555 = true;
}

void clear_outputs_BlinkRight_ID_19411(){
	noval_BlinkRight_ID_19542 = true;
	noval_CountTickOutRight_ID_19553 = true;
}

void init_BlinkRight_ID_19411(){
	noval_BlinkRight_ID_19542 = true;
	noval_CountTickOutRight_ID_19553 = false;
	CountTickOutRight_ID_19553 = 0;
	
}

void perform_step_BlinkRight_ID_19411(){
	clear_outputs_BlinkRight_ID_19411();
	if (noval_CountTickInRight_ID_19555 == false && CountTickInRight_ID_19555 == 0) {
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 0;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 0;
		
		
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = 0;
		
	}
	if ((noval_EnableRightSignal_ID_19501 == false && EnableRightSignal_ID_19501 == true) && (noval_CountTickInRight_ID_19555 == false && CountTickInRight_ID_19555 == 0)) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 255;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 129;
		
		
	}
	if (CountTickInRight_ID_19555 >= 1 && CountTickInRight_ID_19555 <= 21) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 255;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 129;
		
		
	}
	if (CountTickInRight_ID_19555 >= 22 && CountTickInRight_ID_19555 <= 42) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 0;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 0;
		
		
	}
	if (CountTickInRight_ID_19555 >= 43 && CountTickInRight_ID_19555 <= 63) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 255;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 129;
		
		
	}
	if (CountTickInRight_ID_19555 >= 64 && CountTickInRight_ID_19555 <= 84) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 0;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 0;
		
		
	}
	if (CountTickInRight_ID_19555 >= 85 && CountTickInRight_ID_19555 <= 105) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 255;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 129;
		
		
	}
	if (CountTickInRight_ID_19555 >= 106 && CountTickInRight_ID_19555 <= 126) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = CountTickInRight_ID_19555 + 1;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 0;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 0;
		
		
	}
	if (CountTickInRight_ID_19555 >= 127) {
		noval_CountTickOutRight_ID_19553 = false;
		CountTickOutRight_ID_19553 = 0;
		
		noval_BlinkRight_ID_19542 = false;
		BlinkRight_ID_19542.R = 0;
		BlinkRight_ID_19542.B = 0;
		BlinkRight_ID_19542.G = 0;
		
		
	}
	return;
	
}
