/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/BlinkLeft_ID_19399.h"

GEN_TYPE_boolean EnableLeftSignal_ID_19496;

GEN_TYPE_boolean noval_EnableLeftSignal_ID_19496;

GEN_TYPE_int CountTickInLeft_ID_19526;

GEN_TYPE_boolean noval_CountTickInLeft_ID_19526;

GEN_TYPE_int CountTickOutLeft_ID_19524;

GEN_TYPE_boolean noval_CountTickOutLeft_ID_19524;

GEN_TYPE_RGBColor BlinkLeft_ID_19537;

GEN_TYPE_boolean noval_BlinkLeft_ID_19537;

void clear_inputs_BlinkLeft_ID_19399(){
	noval_EnableLeftSignal_ID_19496 = true;
	noval_CountTickInLeft_ID_19526 = true;
}

void clear_outputs_BlinkLeft_ID_19399(){
	noval_CountTickOutLeft_ID_19524 = true;
	noval_BlinkLeft_ID_19537 = true;
}

void init_BlinkLeft_ID_19399(){
	noval_CountTickOutLeft_ID_19524 = false;
	CountTickOutLeft_ID_19524 = 0;
	
	noval_BlinkLeft_ID_19537 = true;
}

void perform_step_BlinkLeft_ID_19399(){
	clear_outputs_BlinkLeft_ID_19399();
	if (noval_CountTickInLeft_ID_19526 == false && CountTickInLeft_ID_19526 == 0) {
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 0;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 0;
		
		
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = 0;
		
	}
	if ((noval_EnableLeftSignal_ID_19496 == false && EnableLeftSignal_ID_19496 == true) && (noval_CountTickInLeft_ID_19526 == false && CountTickInLeft_ID_19526 == 0)) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 255;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 129;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 1 && CountTickInLeft_ID_19526 <= 21) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 255;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 129;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 22 && CountTickInLeft_ID_19526 <= 42) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 0;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 0;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 43 && CountTickInLeft_ID_19526 <= 63) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 255;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 129;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 64 && CountTickInLeft_ID_19526 <= 84) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 0;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 0;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 85 && CountTickInLeft_ID_19526 <= 105) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 255;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 129;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 106 && CountTickInLeft_ID_19526 <= 126) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = CountTickInLeft_ID_19526 + 1;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 0;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 0;
		
		
	}
	if (CountTickInLeft_ID_19526 >= 127) {
		noval_CountTickOutLeft_ID_19524 = false;
		CountTickOutLeft_ID_19524 = 0;
		
		noval_BlinkLeft_ID_19537 = false;
		BlinkLeft_ID_19537.R = 0;
		BlinkLeft_ID_19537.B = 0;
		BlinkLeft_ID_19537.G = 0;
		
		
	}
	return;
	
}
