/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Computation_ID_27.h"

GEN_TYPE_double History_ID_57;

GEN_TYPE_boolean noval_History_ID_57;

GEN_TYPE_double Input_ID_45022;

GEN_TYPE_boolean noval_Input_ID_45022;

GEN_TYPE_double Weight_Current_ID_84;

GEN_TYPE_boolean noval_Weight_Current_ID_84;

GEN_TYPE_double Output_ID_45391;

GEN_TYPE_boolean noval_Output_ID_45391;

void clear_inputs_Computation_ID_27(){
	noval_History_ID_57 = true;
	noval_Input_ID_45022 = true;
	noval_Weight_Current_ID_84 = true;
}

void clear_outputs_Computation_ID_27(){
	noval_Output_ID_45391 = true;
}

void init_Computation_ID_27(){
	noval_Output_ID_45391 = true;
}

void perform_step_Computation_ID_27(){
	clear_outputs_Computation_ID_27();
	noval_Output_ID_45391 = false;
	Output_ID_45391 = Weight_Current_ID_84 * Input_ID_45022 + (1 - Weight_Current_ID_84) * History_ID_57;
	
	return;
	
}
