/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Coordinator_ID_29204.h"

GEN_TYPE_int RumbleLW_In_ID_30662;

GEN_TYPE_boolean noval_RumbleLW_In_ID_30662;

GEN_TYPE_int RumbleLK_In_ID_29222;

GEN_TYPE_boolean noval_RumbleLK_In_ID_29222;

GEN_TYPE_int RumbleWeak_Out_ID_29233;

GEN_TYPE_boolean noval_RumbleWeak_Out_ID_29233;

void clear_inputs_Coordinator_ID_29204(){
	noval_RumbleLW_In_ID_30662 = true;
	noval_RumbleLK_In_ID_29222 = true;
}

void clear_outputs_Coordinator_ID_29204(){
	noval_RumbleWeak_Out_ID_29233 = true;
}

void init_Coordinator_ID_29204(){
	noval_RumbleWeak_Out_ID_29233 = true;
}

void perform_step_Coordinator_ID_29204(){
	clear_outputs_Coordinator_ID_29204();
	if (noval_RumbleLW_In_ID_30662 == false && RumbleLW_In_ID_30662 == RUMBLE_MAX() || noval_RumbleLK_In_ID_29222 == false && RumbleLK_In_ID_29222 == RUMBLE_MAX()) {
		noval_RumbleWeak_Out_ID_29233 = false;
		RumbleWeak_Out_ID_29233 = RUMBLE_MAX();
		
	}
	else {
		noval_RumbleWeak_Out_ID_29233 = false;
		RumbleWeak_Out_ID_29233 = 0;
		
	}
	return;
	
}
