/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/data_dictionary.h"

GEN_TYPE_Message_Type platoon(){
	return platoon_ID_46451;
}

GEN_TYPE_Message_Type fuse(){
	return fuse_ID_46453;
}

GEN_TYPE_Message_Type no_message(){
	return no_message_ID_46460;
}

GEN_TYPE_Message_Type handshake(){
	return handshake_ID_47920;
}

GEN_TYPE_Message_Type split(){
	return split_ID_50354;
}

GEN_TYPE_Message_Type leave(){
	return leave_ID_50355;
}

GEN_TYPE_Message_Type heartbeat(){
	return heartbeat_ID_51359;
}

GEN_TYPE_Message_Type newLeader(){
	return newLeader_ID_57755;
}

char* Message_TypeToString(GEN_TYPE_Message_Type value){
	if (value == platoon_ID_46451) {
		return "platoon()";
	}
	if (value == fuse_ID_46453) {
		return "fuse()";
	}
	if (value == no_message_ID_46460) {
		return "no_message()";
	}
	if (value == handshake_ID_47920) {
		return "handshake()";
	}
	if (value == split_ID_50354) {
		return "split()";
	}
	if (value == leave_ID_50355) {
		return "leave()";
	}
	if (value == heartbeat_ID_51359) {
		return "heartbeat()";
	}
	if (value == newLeader_ID_57755) {
		return "newLeader()";
	}
	return "null";
	
}

GEN_TYPE_PlatoonState off(){
	return off_ID_48498;
}

GEN_TYPE_PlatoonState follower(){
	return follower_ID_48499;
}

GEN_TYPE_PlatoonState leader(){
	return leader_ID_48500;
}

GEN_TYPE_PlatoonState fuseStarter(){
	return fuseStarter_ID_48501;
}

GEN_TYPE_PlatoonState fusing(){
	return fusing_ID_50309;
}

GEN_TYPE_PlatoonState leaving(){
	return leaving_ID_50634;
}

GEN_TYPE_PlatoonState splitting(){
	return splitting_ID_50635;
}

GEN_TYPE_PlatoonState handshaking(){
	return handshaking_ID_56096;
}

char* PlatoonStateToString(GEN_TYPE_PlatoonState value){
	if (value == off_ID_48498) {
		return "off()";
	}
	if (value == follower_ID_48499) {
		return "follower()";
	}
	if (value == leader_ID_48500) {
		return "leader()";
	}
	if (value == fuseStarter_ID_48501) {
		return "fuseStarter()";
	}
	if (value == fusing_ID_50309) {
		return "fusing()";
	}
	if (value == leaving_ID_50634) {
		return "leaving()";
	}
	if (value == splitting_ID_50635) {
		return "splitting()";
	}
	if (value == handshaking_ID_56096) {
		return "handshaking()";
	}
	return "null";
	
}

GEN_TYPE_On_Off_States Off(){
	return Off_ID_7966;
}

GEN_TYPE_On_Off_States On(){
	return On_ID_7967;
}

char* On_Off_StatesToString(GEN_TYPE_On_Off_States value){
	if (value == Off_ID_7966) {
		return "Off()";
	}
	if (value == On_ID_7967) {
		return "On()";
	}
	return "null";
	
}

GEN_TYPE_DriveMode Parking(){
	return Parking_ID_9643;
}

GEN_TYPE_DriveMode Forward(){
	return Forward_ID_6274;
}

GEN_TYPE_DriveMode Backward(){
	return Backward_ID_6278;
}

GEN_TYPE_DriveMode Change(){
	return Change_ID_6614;
}

char* DriveModeToString(GEN_TYPE_DriveMode value){
	if (value == Parking_ID_9643) {
		return "Parking()";
	}
	if (value == Forward_ID_6274) {
		return "Forward()";
	}
	if (value == Backward_ID_6278) {
		return "Backward()";
	}
	if (value == Change_ID_6614) {
		return "Change()";
	}
	return "null";
	
}

GEN_TYPE_AD_Commands KeepCurrentStateAD(){
	return KeepCurrentStateAD_ID_24110;
}

GEN_TYPE_AD_Commands OffAD(){
	return OffAD_ID_24111;
}

GEN_TYPE_AD_Commands OnAD(){
	return OnAD_ID_24112;
}

char* AD_CommandsToString(GEN_TYPE_AD_Commands value){
	if (value == KeepCurrentStateAD_ID_24110) {
		return "KeepCurrentStateAD()";
	}
	if (value == OffAD_ID_24111) {
		return "OffAD()";
	}
	if (value == OnAD_ID_24112) {
		return "OnAD()";
	}
	return "null";
	
}

GEN_TYPE_EngineMode NoOp(){
	return NoOp_ID_9641;
}

GEN_TYPE_EngineMode Switch(){
	return Switch_ID_9642;
}

char* EngineModeToString(GEN_TYPE_EngineMode value){
	if (value == NoOp_ID_9641) {
		return "NoOp()";
	}
	if (value == Switch_ID_9642) {
		return "Switch()";
	}
	return "null";
	
}

GEN_TYPE_KeyEvent pressed(){
	return pressed_ID_98;
}

GEN_TYPE_KeyEvent notPressed(){
	return notPressed_ID_100;
}

char* KeyEventToString(GEN_TYPE_KeyEvent value){
	if (value == pressed_ID_98) {
		return "pressed()";
	}
	if (value == notPressed_ID_100) {
		return "notPressed()";
	}
	return "null";
	
}

GEN_TYPE_double myabs(GEN_TYPE_double _V){
	return _V * sgn(_V);
}

GEN_TYPE_double arctan(GEN_TYPE_double _V){
	if (myabs(_V) <= 1.0) {
		return _V / (1 + (0.28 * _V) * _V);
	}
	else {
		if (_V > 1) {
			return pi() / 2.0 - _V / (_V * _V + 0.28);
		}
		else {
			return -(pi() / 2.0) - _V / (_V * _V + 0.28);
		}
	}
}

GEN_TYPE_double e(){
	return 2.718281828459;
}

GEN_TYPE_double exp(GEN_TYPE_double _V){
	return ((((1 + _V) + (_V * _V) / 2) + ((_V * _V) * _V) / 6) + (((_V * _V) * _V) * _V) / 24) + ((((_V * _V) * _V) * _V) * _V) / 120;
}

GEN_TYPE_double ln(GEN_TYPE_double _V){
	if (_V <= 0) {
		return 0;
	}
	else {
		return ((((_V - 1.0) - ((_V - 1.0) * (_V - 1.0)) / 2.0) + (((_V - 1) * (_V - 1)) * (_V - 1)) / 3.0) - ((((_V - 1) * (_V - 1)) * (_V - 1)) * (_V - 1)) / 4.0) + (((((_V - 1) * (_V - 1)) * (_V - 1)) * (_V - 1)) * (_V - 1)) / 5.0;
	}
}

GEN_TYPE_double pi(){
	return 3.14159265;
}

GEN_TYPE_double sgn(GEN_TYPE_double _V){
	if (_V < 0) {
		return -1;
	}
	else {
		if (_V == 0) {
			return 0;
		}
		else {
			return 1;
		}
	}
}

GEN_TYPE_double sqrt(GEN_TYPE_double _V){
	if (_V <= 0) {
		return 0;
	}
	else {
		return _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, _sqrt(_V, ((_V + 1.0) / 2.0)))))))))));
	}
}

GEN_TYPE_double _sqrt(GEN_TYPE_double _X,GEN_TYPE_double _V){
	return 0.5 * (_V + _X / _V);
}

GEN_TYPE_double pow(GEN_TYPE_double _V,GEN_TYPE_double _N){
	if (_N == 0) {
		return 1;
	}
	else {
		if (_N < 0) {
			if (_V == 0) {
				return 0;
			}
			else {
				return 1.0 / pow(_V, (-_N));
			}
		}
		else {
			if (_N == 1) {
				return _V;
			}
			else {
				return _V * pow(_V, (_N - 1));
			}
		}
	}
}

GEN_TYPE_double min(GEN_TYPE_double _a,GEN_TYPE_double _b){
	if (_a < _b) {
		return _a;
	}
	return _b;
}

GEN_TYPE_double max(GEN_TYPE_double _a,GEN_TYPE_double _b){
	if (_a > _b) {
		return _a;
	}
	return _b;
}

GEN_TYPE_double rad2deg(GEN_TYPE_double _A){
	return (_A / pi()) * 180.0;
}

GEN_TYPE_double deg2rad(GEN_TYPE_double _A){
	return (_A / 180.0) * pi();
}

GEN_TYPE_double MAX_BRAKE_VALUE(){
	return -25.0;
}

GEN_TYPE_int EMERGENCY_TIME(){
	return 2;
}

GEN_TYPE_double linConvert(GEN_TYPE_double input,GEN_TYPE_double inputMax,GEN_TYPE_double inputMin,GEN_TYPE_double outputMax,GEN_TYPE_double outputMin){
	if (inputMax == inputMin) {
		return outputMin;
	}
	else {
		return ((outputMax - outputMin) / (inputMax - inputMin)) * (input - inputMin) + outputMin;
	}
}

GEN_TYPE_double STEERING_ANGLE_STRAIGHT_MIN(){
	return 0.0;
}

GEN_TYPE_double STEERING_VALUE_LEFT_MIN(){
	return 6000.0;
}

GEN_TYPE_double STEERING_VALUE_STRAIGHT_MAX(){
	return 6000.0;
}

GEN_TYPE_double STEERING_VALUE_LEFT_MAX(){
	return 4200.0;
}

GEN_TYPE_double STEERING_VALUE_RIGHT_MAX(){
	return 7800.0;
}

GEN_TYPE_double STEERING_VALUE_RIGHT_MIN(){
	return 6000.0;
}

GEN_TYPE_double STEERING_ANGLE_LEFT_MAX(){
	return -pi() / 4.0;
}

GEN_TYPE_double STEERING_ANGLE_LEFT_MIN(){
	return -pi() / 180.0;
}

GEN_TYPE_double STEERING_ANGLE_RIGHT_MAX(){
	return pi() / 4.0;
}

GEN_TYPE_double STEERING_ANGLE_RIGHT_MIN(){
	return pi() / 180.0;
}

GEN_TYPE_double STEERING_ANGLE_STRAIGHT_MAX(){
	return 0.0;
}

GEN_TYPE_double STEERING_VALUE_STRAIGHT_MIN(){
	return 6000.0;
}

GEN_TYPE_double STEERING_ANGLE_MIN(){
	return -pi() / 4.0;
}

GEN_TYPE_double STEERING_ANGLE_MAX(){
	return pi() / 4.0;
}

GEN_TYPE_double COEFFICIENT_CONTROLLER_I(){
	return 0.0;
}

GEN_TYPE_double COEFFICIENT_CONTROLLER_P(){
	return 0.0;
}

GEN_TYPE_double COEFFICIENT_CONTROLLER_D(){
	return 0.0;
}

GEN_TYPE_double COEFFICIENT_CONTROLLER_MAX_ERROR_SUM(){
	return 100.0;
}

GEN_TYPE_double SAMPLING_TIME_DISTANCE(){
	return 1.0 * TICK_TIME();
}

GEN_TYPE_double TICK_TIME(){
	return 0.033;
}

GEN_TYPE_double SAMPLING_TIME_VELOCITY(){
	return 1.0;
}

GEN_TYPE_double ERRORSUM_ADAPTATION(){
	return 0.1;
}

GEN_TYPE_double NATURAL_ACCELERATION(){
	return 20.0;
}

GEN_TYPE_double COEFFICIENT_CONTROLLER_F(){
	return 1.0;
}

GEN_TYPE_double MAX_EXPECTED_BRAKE_VALUE(){
	return -30.0;
}

GEN_TYPE_double EB_BUFFER_FACTOR(){
	return 0.65;
}

GEN_TYPE_double BRAKE_DEADZONE(){
	return 0.025;
}

GEN_TYPE_double gear1(GEN_TYPE_double _X){
	return (_X * myabs(_X)) * 0.1;
}

GEN_TYPE_double gear2(GEN_TYPE_double _X){
	return pow(_X, 2) * 0.25;
}

GEN_TYPE_double gear3(GEN_TYPE_double _X){
	return _X * 0.4;
}

GEN_TYPE_double gear4(GEN_TYPE_double _X){
	return _X * 0.6;
}

GEN_TYPE_double gear5(GEN_TYPE_double _X){
	return _X * 0.8;
}

GEN_TYPE_double gear6(GEN_TYPE_double _X){
	return _X;
}

GEN_TYPE_double MAX_SPEED(){
	return 28;
}

GEN_TYPE_double VELOCITY_DEADZONE(){
	return 0.01;
}

GEN_TYPE_double EB_VELOCITY(){
	return 0.0;
}

GEN_TYPE_double PRE_BOUNDARIES_FACTOR(){
	return 4.0 / TICK_TIME();
}

GEN_TYPE_double MOTOR_VALUE_MIN(){
	return -30.0;
}

GEN_TYPE_double MOTOR_VALUE_STILL_MIN(){
	return 0.0;
}

GEN_TYPE_double MOTOR_VALUE_BACKWARD_MAX(){
	return -20.0;
}

GEN_TYPE_double MOTOR_VALUE_MAX(){
	return 60.0;
}

GEN_TYPE_double MOTOR_VALUE_FORWARD_MAX(){
	return 15.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_STILL_MIN(){
	return 6000.0;
}

GEN_TYPE_double MOTOR_VALUE_FORWARD_MIN(){
	return 0.0;
}

GEN_TYPE_double MOTOR_VALUE_BACKWARD_MIN(){
	return 0.0;
}

GEN_TYPE_double MOTOR_VALUE_STILL_MAX(){
	return 0.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_STILL_MAX(){
	return 6000.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_BACKWARD_MAX(){
	return 4200.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_FORWARD_MIN(){
	return 6000.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_FORWARD_MAX(){
	return 7800.0;
}

GEN_TYPE_double MOTOR_VALUE_OUT_BACKWARD_MIN(){
	return 6000.0;
}

GEN_TYPE_double STICK_INPUT_SCALING(){
	return 1.0 / 32768.0;
}

GEN_TYPE_double scaleSteering(GEN_TYPE_double _V){
	return 1 - 0.9 * (_V / MAX_SPEED());
}

GEN_TYPE_double INACCURACY(){
	return 0.1;
}

GEN_TYPE_double STICK_THRESHOLD(){
	return 0.8;
}

GEN_TYPE_double ROVER_WIDTH(){
	return 0.285;
}

GEN_TYPE_double STEERING_DEADZONE(){
	return 3 * (pi() / 180.0);
}

GEN_TYPE_double COEFFICIENT_LK_CONTROLLER_P(){
	return 0.05;
}

GEN_TYPE_double COEFFICIENT_LK_CONTROLLER_D(){
	return 0.001;
}

GEN_TYPE_double COEFFICIENT_LK_CONTROLLER_I(){
	return 0.0;
}

GEN_TYPE_double LD_DISTANCE_ERROR_DEADZONE(){
	return 0.01;
}

GEN_TYPE_double ACC_CONTROLLER_P(){
	return 0.5;
}

GEN_TYPE_double ACC_BUFFER_FACTOR(){
	return 1.8;
}

GEN_TYPE_double Z_INPUT_SCALING(){
	return 1.0 / 1024.0;
}

GEN_TYPE_int RUMBLE_MAX(){
	return 32768;
}

GEN_TYPE_double ACC_MIN_DISTANCE(){
	return 0.15;
}

GEN_TYPE_double platooning_clearance(GEN_TYPE_double _V){
	if (_V < 0.5) {
		return 0.5 * _V + PLATOONING_MINOFFSET();
	}
	return 0.5 * _V;
}

GEN_TYPE_double PLATOONING_MINOFFSET(){
	return 0.2;
}

GEN_TYPE_double PLATOONING_TIMEGAP(){
	return 0.5;
}

GEN_TYPE_double COEFFICIENT_PLATOONING_PCONTROLLER(){
	return 0.4;
}

GEN_TYPE_double LASER_CORRECTION(){
	return 30.0;
}

GEN_TYPE_double US_CORRECTION(){
	return 70.0;
}

GEN_TYPE_int CounterFollowerMessage(GEN_TYPE_boolean _V){
	return 0;
}

GEN_TYPE_int roverID(){
	return 999111999;
}

GEN_TYPE_double platooning_relative_distance_error(GEN_TYPE_double _a,GEN_TYPE_double _b){
	return (_a - _b) / _a;
}

GEN_TYPE_double PLATOONING_DISTANCE_TOLERANCE(){
	return 1.0;
}

GEN_TYPE_double acc_targetdistance(GEN_TYPE_double _VelocityFrontObstacle,GEN_TYPE_double _Velocity,GEN_TYPE_double _Buffer){
	return max(ACC_MIN_DISTANCE(), (((-0.5 * pow(_Velocity, 2.0)) / MAX_BRAKE_VALUE() + pow(_Velocity, EB_BUFFER_POW()) * _Buffer) - (-0.5 * pow(_VelocityFrontObstacle, 2.0)) / MAX_EXPECTED_BRAKE_VALUE()));
}

GEN_TYPE_double LK_Activation_Threshold(){
	return 0.9;
}

GEN_TYPE_double LW_Distance_Min(){
	return 0;
}

GEN_TYPE_double ASSUMED_STREET_WIDTH(){
	return 50.0;
}

GEN_TYPE_double COEFFICIENT_LK_FEED_FORWARD(){
	return -0.15;
}

GEN_TYPE_double TIMEOUT_TIME(){
	return 2 / TICK_TIME();
}

GEN_TYPE_double TEN_HZ_CYCLES(){
	return 0.1 / TICK_TIME();
}

GEN_TYPE_double ONE_HZ_CYCLES(){
	return 1 / TICK_TIME();
}

GEN_TYPE_double EB_BUFFER_FACTOR_FOLLOW(){
	return 0.5;
}

GEN_TYPE_double LASER_MAX_INVALID(){
	return 0.05 - LASER_CORRECTION() / 100.0;
}

GEN_TYPE_double LASER_ZERO_MIN_VALUE(){
	return 0.2 - LASER_CORRECTION() / 100.0;
}

GEN_TYPE_double LASER_MIN(){
	return 0.0;
}

GEN_TYPE_double LASER_MAX(){
	return 5.0;
}

GEN_TYPE_boolean NO_WRONG_WAY_DRIVER(){
	return true;
}

GEN_TYPE_double US_MAX(){
	return 1.0;
}

GEN_TYPE_double US_MIN(){
	return 0.0;
}

GEN_TYPE_double EB_BUFFER_POW(){
	return 1.0;
}

GEN_TYPE_double ACC_DEFAULT_VELOCITY(){
	return 0.7;
}

GEN_TYPE_double MAX_END_SPEED(){
	return 1.5;
}

GEN_TYPE_double ACC_MAX_ACCELERATION(){
	return 2.0;
}

GEN_TYPE_double ACC_MAX_DECELERATION(){
	return -2.0;
}

GEN_TYPE_double LK_FILTER_WEIGHT(){
	return 0.5;
}

GEN_TYPE_int get_nof_participants(GEN_TYPE_listParticipants participants){
	if ((participants.content)[0] == 0) {
		return 0;
	}
	if ((participants.content)[1] == 0) {
		return 1;
	}
	if ((participants.content)[2] == 0) {
		return 2;
	}
	if ((participants.content)[3] == 0) {
		return 3;
	}
	if ((participants.content)[4] == 0) {
		return 4;
	}
	else {
		return 5;
	}
}

GEN_TYPE_listParticipants fuse_participants(GEN_TYPE_listParticipants fuseListParticipants,GEN_TYPE_listParticipants platoonListParticipants){
	if (get_nof_participants(platoonListParticipants) == 1) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (fuseListParticipants.content)[0];
		(__ret__value__.content)[2] = (fuseListParticipants.content)[1];
		(__ret__value__.content)[3] = (fuseListParticipants.content)[2];
		(__ret__value__.content)[4] = (fuseListParticipants.content)[3];
		return __ret__value__;
		
	}
	if (get_nof_participants(platoonListParticipants) == 2) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (fuseListParticipants.content)[0];
		(__ret__value__.content)[3] = (fuseListParticipants.content)[1];
		(__ret__value__.content)[4] = (fuseListParticipants.content)[2];
		return __ret__value__;
		
	}
	if (get_nof_participants(platoonListParticipants) == 3) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[2];
		(__ret__value__.content)[3] = (fuseListParticipants.content)[0];
		(__ret__value__.content)[4] = (fuseListParticipants.content)[1];
		return __ret__value__;
		
	}
	if (get_nof_participants(platoonListParticipants) == 4) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[2];
		(__ret__value__.content)[3] = (platoonListParticipants.content)[3];
		(__ret__value__.content)[4] = (fuseListParticipants.content)[0];
		return __ret__value__;
		
	}
	return platoonListParticipants;
}

GEN_TYPE_int get_position(GEN_TYPE_listParticipants participants,GEN_TYPE_int id){
	if ((participants.content)[0] == id) {
		return 1;
	}
	if ((participants.content)[1] == id) {
		return 2;
	}
	if ((participants.content)[2] == id) {
		return 3;
	}
	if ((participants.content)[3] == id) {
		return 4;
	}
	if ((participants.content)[4] == id) {
		return 5;
	}
	return -1;
}

GEN_TYPE_listParticipants split_participants(GEN_TYPE_listParticipants splitList,GEN_TYPE_int splitPos){
	if (splitPos == 2) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[1];
		(__ret__value__.content)[1] = (splitList.content)[2];
		(__ret__value__.content)[2] = (splitList.content)[3];
		(__ret__value__.content)[3] = (splitList.content)[4];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 3) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[2];
		(__ret__value__.content)[1] = (splitList.content)[3];
		(__ret__value__.content)[2] = (splitList.content)[4];
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 4) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[3];
		(__ret__value__.content)[1] = (splitList.content)[4];
		(__ret__value__.content)[2] = 0;
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 5) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[4];
		(__ret__value__.content)[1] = 0;
		(__ret__value__.content)[2] = 0;
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	return splitList;
}

GEN_TYPE_int get_tailID(GEN_TYPE_listParticipants participants){
	if ((participants.content)[0] == 0) {
		return 0;
	}
	if ((participants.content)[1] == 0) {
		return (participants.content)[0];
	}
	if ((participants.content)[2] == 0) {
		return (participants.content)[1];
	}
	if ((participants.content)[3] == 0) {
		return (participants.content)[2];
	}
	if ((participants.content)[4] == 0) {
		return (participants.content)[3];
	}
	return (participants.content)[4];
}

GEN_TYPE_listParticipants split_participantsLeader(GEN_TYPE_listParticipants splitList,GEN_TYPE_int splitPos){
	if (splitPos == 2) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[0];
		(__ret__value__.content)[1] = 0;
		(__ret__value__.content)[2] = 0;
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 3) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[0];
		(__ret__value__.content)[1] = (splitList.content)[1];
		(__ret__value__.content)[2] = 0;
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 4) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[0];
		(__ret__value__.content)[1] = (splitList.content)[1];
		(__ret__value__.content)[2] = (splitList.content)[2];
		(__ret__value__.content)[3] = 0;
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (splitPos == 5) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (splitList.content)[0];
		(__ret__value__.content)[1] = (splitList.content)[1];
		(__ret__value__.content)[2] = (splitList.content)[2];
		(__ret__value__.content)[3] = (splitList.content)[3];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	return splitList;
}

GEN_TYPE_listParticipants leave_participants(GEN_TYPE_listParticipants platoonListParticipants,GEN_TYPE_int id){
	if (get_position(platoonListParticipants, id) == 2) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[2];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[3];
		(__ret__value__.content)[3] = (platoonListParticipants.content)[4];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (get_position(platoonListParticipants, id) == 3) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[3];
		(__ret__value__.content)[3] = (platoonListParticipants.content)[4];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (get_position(platoonListParticipants, id) == 4) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[2];
		(__ret__value__.content)[3] = (platoonListParticipants.content)[4];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	if (get_position(platoonListParticipants, id) == 5) {
		GEN_TYPE_listParticipants  __ret__value__;
		(__ret__value__.content)[0] = (platoonListParticipants.content)[0];
		(__ret__value__.content)[1] = (platoonListParticipants.content)[1];
		(__ret__value__.content)[2] = (platoonListParticipants.content)[2];
		(__ret__value__.content)[3] = (platoonListParticipants.content)[3];
		(__ret__value__.content)[4] = 0;
		return __ret__value__;
		
	}
	return platoonListParticipants;
}
