/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/DPadLeft_ID_18705.h"

GEN_TYPE_int DPadLeftIn_ID_32537;

GEN_TYPE_boolean noval_DPadLeftIn_ID_32537;

GEN_TYPE_KeyEvent DPadLeftOut_ID_32510;

GEN_TYPE_boolean noval_DPadLeftOut_ID_32510;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_18724();

static GEN_TYPE_boolean fire_transition_Release_ID_18726();

static GEN_TYPE_boolean fire_state_Released_ID_18712();

static GEN_TYPE_boolean fire_state_Pressed_ID_18717();

void clear_inputs_DPadLeft_ID_18705(){
	noval_DPadLeftIn_ID_32537 = true;
}

void clear_outputs_DPadLeft_ID_18705(){
	noval_DPadLeftOut_ID_32510 = true;
}

void init_DPadLeft_ID_18705(){
	noval_DPadLeftOut_ID_32510 = true;
	current_state = 18712;
}

void perform_step_DPadLeft_ID_18705(){
	clear_outputs_DPadLeft_ID_18705();
	if (current_state == 18717) {
		fire_state_Pressed_ID_18717();
	}
	else {
		if (current_state == 18712) {
			fire_state_Released_ID_18712();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_18724(){
	if (noval_DPadLeftIn_ID_32537 == false && DPadLeftIn_ID_32537 == 1) {
		noval_DPadLeftOut_ID_32510 = false;
		DPadLeftOut_ID_32510 = pressed();
		
		current_state = 18717;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_18726(){
	if (noval_DPadLeftIn_ID_32537 == true || noval_DPadLeftIn_ID_32537 == false && DPadLeftIn_ID_32537 == 0) {
		noval_DPadLeftOut_ID_32510 = false;
		DPadLeftOut_ID_32510 = notPressed();
		
		current_state = 18712;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_18712(){
	if (!fire_transition_Press_ID_18724()) {
		noval_DPadLeftOut_ID_32510 = false;
		DPadLeftOut_ID_32510 = notPressed();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_18717(){
	if (!fire_transition_Release_ID_18726()) {
		noval_DPadLeftOut_ID_32510 = false;
		DPadLeftOut_ID_32510 = notPressed();
		
	}
	return true;
}
