/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/EngineMode_ID_9757.h"

GEN_TYPE_DriveModeSettings DriveMode_ID_12235;

GEN_TYPE_boolean noval_DriveMode_ID_12235;

GEN_TYPE_double MaxAcceleration_ID_5881;

GEN_TYPE_boolean noval_MaxAcceleration_ID_5881;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_sport_ID_5868();

static GEN_TYPE_boolean fire_transition_eco_ID_10020();

static GEN_TYPE_boolean fire_transition_released_ID_10031();

static GEN_TYPE_boolean fire_transition_released_ID_10037();

static GEN_TYPE_boolean fire_state_Eco2_ID_5828();

static GEN_TYPE_boolean fire_state_Sport1_ID_5833();

static GEN_TYPE_boolean fire_state_Sport2_ID_10012();

static GEN_TYPE_boolean fire_state_Eco1_ID_10015();

void clear_inputs_EngineMode_ID_9757(){
	noval_DriveMode_ID_12235 = true;
}

void clear_outputs_EngineMode_ID_9757(){
	noval_MaxAcceleration_ID_5881 = true;
}

void init_EngineMode_ID_9757(){
	noval_MaxAcceleration_ID_5881 = true;
	current_state = 5828;
}

void perform_step_EngineMode_ID_9757(){
	clear_outputs_EngineMode_ID_9757();
	if (current_state == 10015) {
		fire_state_Eco1_ID_10015();
	}
	else {
		if (current_state == 10012) {
			fire_state_Sport2_ID_10012();
		}
		else {
			if (current_state == 5833) {
				fire_state_Sport1_ID_5833();
			}
			else {
				if (current_state == 5828) {
					fire_state_Eco2_ID_5828();
				}
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_sport_ID_5868(){
	if (!(noval_DriveMode_ID_12235 == true) && DriveMode_ID_12235.EngineMode == Switch()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 4.0;
		
		current_state = 5833;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_eco_ID_10020(){
	if (!(noval_DriveMode_ID_12235 == true) && DriveMode_ID_12235.EngineMode == Switch()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 2.0;
		
		current_state = 10015;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_released_ID_10031(){
	if (!(noval_DriveMode_ID_12235 == true) && DriveMode_ID_12235.EngineMode == NoOp()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 4.0;
		
		current_state = 10012;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_released_ID_10037(){
	if (!(noval_DriveMode_ID_12235 == true) && DriveMode_ID_12235.EngineMode == NoOp()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 2;
		
		current_state = 5828;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Eco2_ID_5828(){
	if (!fire_transition_sport_ID_5868()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 2.0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Sport1_ID_5833(){
	if (!fire_transition_released_ID_10031()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 4.0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Sport2_ID_10012(){
	if (!fire_transition_eco_ID_10020()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 4.0;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Eco1_ID_10015(){
	if (!fire_transition_released_ID_10037()) {
		noval_MaxAcceleration_ID_5881 = false;
		MaxAcceleration_ID_5881 = 2.0;
		
	}
	return true;
}
