/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/I_term_ID_16014.h"

GEN_TYPE_double Error_ID_16073;

GEN_TYPE_boolean noval_Error_ID_16073;

GEN_TYPE_double ErrorSumIn_ID_16119;

GEN_TYPE_boolean noval_ErrorSumIn_ID_16119;

GEN_TYPE_boolean BoundariesActive_ID_16354;

GEN_TYPE_boolean noval_BoundariesActive_ID_16354;

GEN_TYPE_double Coef_I_ID_16037;

GEN_TYPE_boolean noval_Coef_I_ID_16037;

GEN_TYPE_double ErrorSumOut_ID_16108;

GEN_TYPE_boolean noval_ErrorSumOut_ID_16108;

void clear_inputs_I_term_ID_16014(){
	noval_Error_ID_16073 = true;
	noval_ErrorSumIn_ID_16119 = true;
	noval_BoundariesActive_ID_16354 = true;
}

void clear_outputs_I_term_ID_16014(){
	noval_Coef_I_ID_16037 = true;
	noval_ErrorSumOut_ID_16108 = true;
}

void init_I_term_ID_16014(){
	noval_Coef_I_ID_16037 = true;
	noval_ErrorSumOut_ID_16108 = true;
}

void perform_step_I_term_ID_16014(){
	clear_outputs_I_term_ID_16014();
	if (noval_Error_ID_16073 == true || noval_Error_ID_16073 == false && Error_ID_16073 == 0.0) {
		noval_Coef_I_ID_16037 = false;
		Coef_I_ID_16037 = 0.0;
		
		noval_ErrorSumOut_ID_16108 = false;
		ErrorSumOut_ID_16108 = 0.0;
		
	}
	else {
		noval_Coef_I_ID_16037 = false;
		Coef_I_ID_16037 = (COEFFICIENT_LK_CONTROLLER_I() * TICK_TIME()) * ErrorSumIn_ID_16119;
		
		if (BoundariesActive_ID_16354) {
			noval_ErrorSumOut_ID_16108 = noval_ErrorSumIn_ID_16119;
			if (!noval_ErrorSumIn_ID_16119) {
				ErrorSumOut_ID_16108 = ErrorSumIn_ID_16119;
			}
			
		}
		else {
			noval_ErrorSumOut_ID_16108 = false;
			ErrorSumOut_ID_16108 = ErrorSumIn_ID_16119 + Error_ID_16073;
			
		}
	}
	return;
	
}
