/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Lane_Keeping_Rumble_ID_30647.h"

GEN_TYPE_boolean RumbleLK_ID_30655;

GEN_TYPE_boolean noval_RumbleLK_ID_30655;

GEN_TYPE_int RumbleLK_Out_ID_30657;

GEN_TYPE_boolean noval_RumbleLK_Out_ID_30657;

static GEN_TYPE_int current_state;

static GEN_TYPE_int counter;

static GEN_TYPE_int scratch_paper_counter;

static void copy_scratch_paper();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_24840();

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_24844();

static GEN_TYPE_boolean fire_state_Init_ID_30652();

static GEN_TYPE_boolean fire_state_State_ID_24835();

void clear_inputs_Lane_Keeping_Rumble_ID_30647(){
	noval_RumbleLK_ID_30655 = true;
}

void clear_outputs_Lane_Keeping_Rumble_ID_30647(){
	noval_RumbleLK_Out_ID_30657 = true;
}

void init_Lane_Keeping_Rumble_ID_30647(){
	noval_RumbleLK_Out_ID_30657 = true;
	current_state = 30652;
	counter = 0;
	scratch_paper_counter = 0;
}

void perform_step_Lane_Keeping_Rumble_ID_30647(){
	clear_outputs_Lane_Keeping_Rumble_ID_30647();
	if (current_state == 24835) {
		fire_state_State_ID_24835();
	}
	else {
		if (current_state == 30652) {
			fire_state_Init_ID_30652();
		}
	}
	copy_scratch_paper();
}

static void copy_scratch_paper(){
	counter = scratch_paper_counter;
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_24840(){
	if (!(noval_RumbleLK_ID_30655 == true) && RumbleLK_ID_30655) {
		noval_RumbleLK_Out_ID_30657 = false;
		RumbleLK_Out_ID_30657 = 0;
		
		current_state = 24835;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Transition_Segment_ID_24844(){
	if ((noval_RumbleLK_ID_30655 == true || !RumbleLK_ID_30655) && counter >= 20) {
		noval_RumbleLK_Out_ID_30657 = false;
		RumbleLK_Out_ID_30657 = 0;
		
		current_state = 30652;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Init_ID_30652(){
	if (!fire_transition_Transition_Segment_ID_24840()) {
		noval_RumbleLK_Out_ID_30657 = false;
		RumbleLK_Out_ID_30657 = 0;
		
		scratch_paper_counter = 0;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_State_ID_24835(){
	if (!fire_transition_Transition_Segment_ID_24844()) {
		noval_RumbleLK_Out_ID_30657 = false;
		RumbleLK_Out_ID_30657 = RUMBLE_MAX();
		
		scratch_paper_counter = counter + 1;
	}
	return true;
}
