/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/LastSensor_Memory_ID_7683.h"

GEN_TYPE_double LastDistanceFrontOut_ID_6965;

GEN_TYPE_boolean noval_LastDistanceFrontOut_ID_6965;

GEN_TYPE_double LastVelocityDiffOut_ID_7777;

GEN_TYPE_boolean noval_LastVelocityDiffOut_ID_7777;

GEN_TYPE_double LastDistanceFrontIn_ID_7688;

GEN_TYPE_boolean noval_LastDistanceFrontIn_ID_7688;

GEN_TYPE_double LastVelocityDiffIn_ID_7784;

GEN_TYPE_boolean noval_LastVelocityDiffIn_ID_7784;

void clear_inputs_LastSensor_Memory_ID_7683(){
	noval_LastDistanceFrontOut_ID_6965 = true;
	noval_LastVelocityDiffOut_ID_7777 = true;
}

void clear_outputs_LastSensor_Memory_ID_7683(){
	noval_LastDistanceFrontIn_ID_7688 = true;
	noval_LastVelocityDiffIn_ID_7784 = true;
}

void init_LastSensor_Memory_ID_7683(){
	noval_LastDistanceFrontIn_ID_7688 = true;
	noval_LastVelocityDiffIn_ID_7784 = true;
}

void perform_step_LastSensor_Memory_ID_7683(){
	clear_outputs_LastSensor_Memory_ID_7683();
	noval_LastDistanceFrontIn_ID_7688 = noval_LastDistanceFrontOut_ID_6965;
	if (!noval_LastDistanceFrontOut_ID_6965) {
		LastDistanceFrontIn_ID_7688 = LastDistanceFrontOut_ID_6965;
	}
	
	noval_LastVelocityDiffIn_ID_7784 = noval_LastVelocityDiffOut_ID_7777;
	if (!noval_LastVelocityDiffOut_ID_7777) {
		LastVelocityDiffIn_ID_7784 = LastVelocityDiffOut_ID_7777;
	}
	
	return;
	
}
