/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Last_Steering_ID_44992.h"

GEN_TYPE_double SteeringAngle_ID_45001;

GEN_TYPE_boolean noval_SteeringAngle_ID_45001;

GEN_TYPE_double LastSteeringAngle_ID_45008;

GEN_TYPE_boolean noval_LastSteeringAngle_ID_45008;

void clear_inputs_Last_Steering_ID_44992(){
	noval_SteeringAngle_ID_45001 = true;
}

void clear_outputs_Last_Steering_ID_44992(){
	noval_LastSteeringAngle_ID_45008 = true;
}

void init_Last_Steering_ID_44992(){
	noval_LastSteeringAngle_ID_45008 = true;
}

void perform_step_Last_Steering_ID_44992(){
	clear_outputs_Last_Steering_ID_44992();
	noval_LastSteeringAngle_ID_45008 = noval_SteeringAngle_ID_45001;
	if (!noval_SteeringAngle_ID_45001) {
		LastSteeringAngle_ID_45008 = SteeringAngle_ID_45001;
	}
	
	return;
	
}
