/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Mapping_ID_6657.h"

GEN_TYPE_double DistanceToFrontLaser_ID_24653;

GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_24653;

GEN_TYPE_double ButtonL2_ID_14962;

GEN_TYPE_boolean noval_ButtonL2_ID_14962;

GEN_TYPE_KeyEvent ButtonR1_ID_13363;

GEN_TYPE_boolean noval_ButtonR1_ID_13363;

GEN_TYPE_double ButtonR2_ID_14969;

GEN_TYPE_boolean noval_ButtonR2_ID_14969;

GEN_TYPE_double LeftStick_X_ID_11980;

GEN_TYPE_boolean noval_LeftStick_X_ID_11980;

GEN_TYPE_double RightStick_X_ID_11985;

GEN_TYPE_boolean noval_RightStick_X_ID_11985;

GEN_TYPE_double RightStick_Y_ID_11990;

GEN_TYPE_boolean noval_RightStick_Y_ID_11990;

GEN_TYPE_KeyEvent ButtonL1_ID_13349;

GEN_TYPE_boolean noval_ButtonL1_ID_13349;

GEN_TYPE_double VelocityIn_ID_31865;

GEN_TYPE_boolean noval_VelocityIn_ID_31865;

GEN_TYPE_boolean FrontObstacleCommand_ID_10653;

GEN_TYPE_boolean noval_FrontObstacleCommand_ID_10653;

GEN_TYPE_double DistanceToFrontObstacle_ID_10660;

GEN_TYPE_boolean noval_DistanceToFrontObstacle_ID_10660;

GEN_TYPE_KeyEvent ButtonHome_ID_14630;

GEN_TYPE_boolean noval_ButtonHome_ID_14630;

GEN_TYPE_KeyEvent ButtonSelect_ID_14639;

GEN_TYPE_boolean noval_ButtonSelect_ID_14639;

GEN_TYPE_double LeftStick_Y_ID_14675;

GEN_TYPE_boolean noval_LeftStick_Y_ID_14675;

GEN_TYPE_double LD_Distance_Left_filtered_ID_45081;

GEN_TYPE_boolean noval_LD_Distance_Left_filtered_ID_45081;

GEN_TYPE_double LD_Distance_Right_filtered_ID_45086;

GEN_TYPE_boolean noval_LD_Distance_Right_filtered_ID_45086;

GEN_TYPE_boolean LD_present_left_ID_15769;

GEN_TYPE_boolean noval_LD_present_left_ID_15769;

GEN_TYPE_boolean LD_present_right_ID_15776;

GEN_TYPE_boolean noval_LD_present_right_ID_15776;

GEN_TYPE_double LD_Orientation_ID_15783;

GEN_TYPE_boolean noval_LD_Orientation_ID_15783;

GEN_TYPE_double DistanceToFrontUS_ID_24660;

GEN_TYPE_boolean noval_DistanceToFrontUS_ID_24660;

GEN_TYPE_KeyEvent DPadLeft_ID_18663;

GEN_TYPE_boolean noval_DPadLeft_ID_18663;

GEN_TYPE_KeyEvent DPadRight_ID_18670;

GEN_TYPE_boolean noval_DPadRight_ID_18670;

GEN_TYPE_KeyEvent DPadUp_ID_19940;

GEN_TYPE_boolean noval_DPadUp_ID_19940;

GEN_TYPE_KeyEvent DPadDown_ID_19947;

GEN_TYPE_boolean noval_DPadDown_ID_19947;

GEN_TYPE_boolean LD_server_connected_ID_31291;

GEN_TYPE_boolean noval_LD_server_connected_ID_31291;

GEN_TYPE_int LD_server_lastupdate_ID_31298;

GEN_TYPE_boolean noval_LD_server_lastupdate_ID_31298;

GEN_TYPE_boolean LD_curve_detected_ID_31305;

GEN_TYPE_boolean noval_LD_curve_detected_ID_31305;

GEN_TYPE_double LD_curve_radius_ID_31312;

GEN_TYPE_boolean noval_LD_curve_radius_ID_31312;

GEN_TYPE_boolean LD_rover_detected_ID_31319;

GEN_TYPE_boolean noval_LD_rover_detected_ID_31319;

GEN_TYPE_int LD_rover_id_ID_31326;

GEN_TYPE_boolean noval_LD_rover_id_ID_31326;

GEN_TYPE_int LD_rover_distance_ID_31333;

GEN_TYPE_boolean noval_LD_rover_distance_ID_31333;

GEN_TYPE_KeyEvent ButtonStart_ID_44452;

GEN_TYPE_boolean noval_ButtonStart_ID_44452;

GEN_TYPE_double LD_Distance_Left_ID_45340;

GEN_TYPE_boolean noval_LD_Distance_Left_ID_45340;

GEN_TYPE_double LD_Distance_Right_ID_45347;

GEN_TYPE_boolean noval_LD_Distance_Right_ID_45347;

GEN_TYPE_double SteeringWheel_ID_6665;

GEN_TYPE_boolean noval_SteeringWheel_ID_6665;

GEN_TYPE_int GearShift_ID_15027;

GEN_TYPE_boolean noval_GearShift_ID_15027;

GEN_TYPE_double BrakePedal_ID_6693;

GEN_TYPE_boolean noval_BrakePedal_ID_6693;

GEN_TYPE_double GasPedal_ID_6700;

GEN_TYPE_boolean noval_GasPedal_ID_6700;

GEN_TYPE_double DistanceFront_ID_6707;

GEN_TYPE_boolean noval_DistanceFront_ID_6707;

GEN_TYPE_double Velocity_ID_6714;

GEN_TYPE_boolean noval_Velocity_ID_6714;

GEN_TYPE_double AccelerationOut_ID_6721;

GEN_TYPE_boolean noval_AccelerationOut_ID_6721;

GEN_TYPE_DriverAssistanceEvents DACommand_ID_8662;

GEN_TYPE_boolean noval_DACommand_ID_8662;

GEN_TYPE_LDCameraData LDCameraData_ID_15459;

GEN_TYPE_boolean noval_LDCameraData_ID_15459;

GEN_TYPE_KeyEvent ButtonEBOff_ID_17707;

GEN_TYPE_boolean noval_ButtonEBOff_ID_17707;

GEN_TYPE_boolean EnableRightSignal_ID_18596;

GEN_TYPE_boolean noval_EnableRightSignal_ID_18596;

GEN_TYPE_boolean EnableLeftSignal_ID_18603;

GEN_TYPE_boolean noval_EnableLeftSignal_ID_18603;

GEN_TYPE_AutonomousDrivingEvents ADCommand_ID_19966;

GEN_TYPE_boolean noval_ADCommand_ID_19966;

void clear_inputs_Mapping_ID_6657(){
	noval_DistanceToFrontLaser_ID_24653 = true;
	noval_ButtonL2_ID_14962 = true;
	noval_ButtonR1_ID_13363 = true;
	noval_ButtonR2_ID_14969 = true;
	noval_LeftStick_X_ID_11980 = true;
	noval_RightStick_X_ID_11985 = true;
	noval_RightStick_Y_ID_11990 = true;
	noval_ButtonL1_ID_13349 = true;
	noval_VelocityIn_ID_31865 = true;
	noval_FrontObstacleCommand_ID_10653 = true;
	noval_DistanceToFrontObstacle_ID_10660 = true;
	noval_ButtonHome_ID_14630 = true;
	noval_ButtonSelect_ID_14639 = true;
	noval_LeftStick_Y_ID_14675 = true;
	noval_LD_Distance_Left_filtered_ID_45081 = true;
	noval_LD_Distance_Right_filtered_ID_45086 = true;
	noval_LD_present_left_ID_15769 = true;
	noval_LD_present_right_ID_15776 = true;
	noval_LD_Orientation_ID_15783 = true;
	noval_DistanceToFrontUS_ID_24660 = true;
	noval_DPadLeft_ID_18663 = true;
	noval_DPadRight_ID_18670 = true;
	noval_DPadUp_ID_19940 = true;
	noval_DPadDown_ID_19947 = true;
	noval_LD_server_connected_ID_31291 = true;
	noval_LD_server_lastupdate_ID_31298 = true;
	noval_LD_curve_detected_ID_31305 = true;
	noval_LD_curve_radius_ID_31312 = true;
	noval_LD_rover_detected_ID_31319 = true;
	noval_LD_rover_id_ID_31326 = true;
	noval_LD_rover_distance_ID_31333 = true;
	noval_ButtonStart_ID_44452 = true;
	noval_LD_Distance_Left_ID_45340 = true;
	noval_LD_Distance_Right_ID_45347 = true;
}

void clear_outputs_Mapping_ID_6657(){
	noval_SteeringWheel_ID_6665 = true;
	noval_GearShift_ID_15027 = true;
	noval_BrakePedal_ID_6693 = true;
	noval_GasPedal_ID_6700 = true;
	noval_DistanceFront_ID_6707 = true;
	noval_Velocity_ID_6714 = true;
	noval_AccelerationOut_ID_6721 = true;
	noval_DACommand_ID_8662 = true;
	noval_LDCameraData_ID_15459 = true;
	noval_ButtonEBOff_ID_17707 = true;
	noval_EnableRightSignal_ID_18596 = true;
	noval_EnableLeftSignal_ID_18603 = true;
	noval_ADCommand_ID_19966 = true;
}

void init_Mapping_ID_6657(){
	noval_SteeringWheel_ID_6665 = true;
	noval_GearShift_ID_15027 = true;
	noval_BrakePedal_ID_6693 = true;
	noval_GasPedal_ID_6700 = true;
	noval_DistanceFront_ID_6707 = true;
	noval_Velocity_ID_6714 = true;
	noval_AccelerationOut_ID_6721 = true;
	noval_DACommand_ID_8662 = true;
	noval_LDCameraData_ID_15459 = true;
	noval_ButtonEBOff_ID_17707 = true;
	noval_EnableRightSignal_ID_18596 = true;
	noval_EnableLeftSignal_ID_18603 = true;
	noval_ADCommand_ID_19966 = true;
}

void perform_step_Mapping_ID_6657(){
	clear_outputs_Mapping_ID_6657();
	noval_ButtonEBOff_ID_17707 = noval_ButtonHome_ID_14630;
	if (!noval_ButtonHome_ID_14630) {
		ButtonEBOff_ID_17707 = ButtonHome_ID_14630;
	}
	
	noval_AccelerationOut_ID_6721 = true;
	noval_Velocity_ID_6714 = noval_VelocityIn_ID_31865;
	if (!noval_VelocityIn_ID_31865) {
		Velocity_ID_6714 = VelocityIn_ID_31865;
	}
	
	if (LD_server_connected_ID_31291 && LD_server_lastupdate_ID_31298 < 150) {
		noval_LDCameraData_ID_15459 = false;
		LDCameraData_ID_15459.present_left = LD_present_left_ID_15769;
		LDCameraData_ID_15459.orientation = LD_Orientation_ID_15783;
		LDCameraData_ID_15459.server_ok = true;
		LDCameraData_ID_15459.curve_detected = LD_curve_detected_ID_31305;
		LDCameraData_ID_15459.rover_distance = LD_rover_distance_ID_31333;
		LDCameraData_ID_15459.present_right = LD_present_right_ID_15776;
		LDCameraData_ID_15459.distance_right = LD_Distance_Right_ID_45347;
		LDCameraData_ID_15459.distance_left = LD_Distance_Left_ID_45340;
		LDCameraData_ID_15459.movement = VelocityIn_ID_31865;
		LDCameraData_ID_15459.rover_detected = LD_rover_detected_ID_31319;
		LDCameraData_ID_15459.rover_id = LD_rover_id_ID_31326;
		LDCameraData_ID_15459.curve_radius = LD_curve_radius_ID_31312;
		
		
	}
	else {
		noval_LDCameraData_ID_15459 = false;
		LDCameraData_ID_15459.present_left = LD_present_left_ID_15769;
		LDCameraData_ID_15459.orientation = LD_Orientation_ID_15783;
		LDCameraData_ID_15459.server_ok = false;
		LDCameraData_ID_15459.curve_detected = LD_curve_detected_ID_31305;
		LDCameraData_ID_15459.rover_distance = LD_rover_distance_ID_31333;
		LDCameraData_ID_15459.present_right = LD_present_right_ID_15776;
		LDCameraData_ID_15459.distance_right = LD_Distance_Right_ID_45347;
		LDCameraData_ID_15459.distance_left = LD_Distance_Left_ID_45340;
		LDCameraData_ID_15459.movement = VelocityIn_ID_31865;
		LDCameraData_ID_15459.rover_detected = LD_rover_detected_ID_31319;
		LDCameraData_ID_15459.rover_id = LD_rover_id_ID_31326;
		LDCameraData_ID_15459.curve_radius = LD_curve_radius_ID_31312;
		
		
	}
	if (!(noval_FrontObstacleCommand_ID_10653 == true) && FrontObstacleCommand_ID_10653) {
		noval_DistanceFront_ID_6707 = noval_DistanceToFrontObstacle_ID_10660;
		if (!noval_DistanceToFrontObstacle_ID_10660) {
			DistanceFront_ID_6707 = DistanceToFrontObstacle_ID_10660;
		}
		
	}
	else {
		if (noval_DistanceToFrontLaser_ID_24653 == true && noval_DistanceToFrontUS_ID_24660 == true) {
			noval_DistanceFront_ID_6707 = true;
		}
		else {
			if (!(noval_DistanceToFrontUS_ID_24660 == true) && (noval_DistanceToFrontLaser_ID_24653 == true || DistanceToFrontUS_ID_24660 <= DistanceToFrontLaser_ID_24653)) {
				noval_DistanceFront_ID_6707 = noval_DistanceToFrontUS_ID_24660;
				if (!noval_DistanceToFrontUS_ID_24660) {
					DistanceFront_ID_6707 = DistanceToFrontUS_ID_24660;
				}
				
			}
			else {
				noval_DistanceFront_ID_6707 = noval_DistanceToFrontLaser_ID_24653;
				if (!noval_DistanceToFrontLaser_ID_24653) {
					DistanceFront_ID_6707 = DistanceToFrontLaser_ID_24653;
				}
				
			}
		}
	}
	if (noval_ButtonR2_ID_14969 == true || ButtonR2_ID_14969 <= 0.0) {
		noval_GasPedal_ID_6700 = false;
		GasPedal_ID_6700 = 0.0;
		
	}
	else {
		noval_GasPedal_ID_6700 = noval_ButtonR2_ID_14969;
		if (!noval_ButtonR2_ID_14969) {
			GasPedal_ID_6700 = ButtonR2_ID_14969;
		}
		
	}
	if (noval_ButtonL2_ID_14962 == true || ButtonL2_ID_14962 <= 0.0) {
		noval_BrakePedal_ID_6693 = false;
		BrakePedal_ID_6693 = 0.0;
		
	}
	else {
		noval_BrakePedal_ID_6693 = noval_ButtonL2_ID_14962;
		if (!noval_ButtonL2_ID_14962) {
			BrakePedal_ID_6693 = ButtonL2_ID_14962;
		}
		
	}
	noval_GearShift_ID_15027 = true;
	if (!(noval_ButtonR1_ID_13363 == true) && (noval_ButtonR1_ID_13363 == false && ButtonR1_ID_13363 == pressed())) {
		noval_GearShift_ID_15027 = false;
		GearShift_ID_15027 = 1;
		
	}
	if (!(noval_ButtonL1_ID_13349 == true) && (noval_ButtonL1_ID_13349 == false && ButtonL1_ID_13349 == pressed())) {
		noval_GearShift_ID_15027 = false;
		GearShift_ID_15027 = -1;
		
	}
	noval_SteeringWheel_ID_6665 = false;
	SteeringWheel_ID_6665 = LeftStick_X_ID_11980 * STEERING_ANGLE_MAX();
	
	if (!(noval_RightStick_Y_ID_11990 == true) && RightStick_Y_ID_11990 < -STICK_THRESHOLD()) {
		noval_DACommand_ID_8662 = false;
		DACommand_ID_8662.acc = ButtonSelect_ID_14639;
		DACommand_ID_8662.laneKeep = ButtonStart_ID_44452;
		DACommand_ID_8662.speedMinus = notPressed();
		DACommand_ID_8662.speedPlus = pressed();
		DACommand_ID_8662.timePlus = notPressed();
		DACommand_ID_8662.timeMinus = notPressed();
		
		
	}
	else {
		if (!(noval_RightStick_Y_ID_11990 == true) && RightStick_Y_ID_11990 > STICK_THRESHOLD()) {
			noval_DACommand_ID_8662 = false;
			DACommand_ID_8662.acc = ButtonSelect_ID_14639;
			DACommand_ID_8662.laneKeep = ButtonStart_ID_44452;
			DACommand_ID_8662.speedMinus = pressed();
			DACommand_ID_8662.speedPlus = notPressed();
			DACommand_ID_8662.timePlus = notPressed();
			DACommand_ID_8662.timeMinus = notPressed();
			
			
		}
		else {
			if (!(noval_RightStick_X_ID_11985 == true) && RightStick_X_ID_11985 > STICK_THRESHOLD()) {
				noval_DACommand_ID_8662 = false;
				DACommand_ID_8662.acc = ButtonSelect_ID_14639;
				DACommand_ID_8662.laneKeep = ButtonStart_ID_44452;
				DACommand_ID_8662.speedMinus = notPressed();
				DACommand_ID_8662.speedPlus = notPressed();
				DACommand_ID_8662.timePlus = pressed();
				DACommand_ID_8662.timeMinus = notPressed();
				
				
			}
			else {
				if (!(noval_RightStick_X_ID_11985 == true) && RightStick_X_ID_11985 < -STICK_THRESHOLD()) {
					noval_DACommand_ID_8662 = false;
					DACommand_ID_8662.acc = ButtonSelect_ID_14639;
					DACommand_ID_8662.laneKeep = ButtonStart_ID_44452;
					DACommand_ID_8662.speedMinus = notPressed();
					DACommand_ID_8662.speedPlus = notPressed();
					DACommand_ID_8662.timePlus = notPressed();
					DACommand_ID_8662.timeMinus = pressed();
					
					
				}
				else {
					noval_DACommand_ID_8662 = false;
					DACommand_ID_8662.acc = ButtonSelect_ID_14639;
					DACommand_ID_8662.laneKeep = ButtonStart_ID_44452;
					DACommand_ID_8662.speedMinus = notPressed();
					DACommand_ID_8662.speedPlus = notPressed();
					DACommand_ID_8662.timePlus = notPressed();
					DACommand_ID_8662.timeMinus = notPressed();
					
					
				}
			}
		}
	}
	noval_ADCommand_ID_19966 = false;
	ADCommand_ID_19966.fusePlatoon = DPadRight_ID_18670;
	ADCommand_ID_19966.splitPlatoon = DPadDown_ID_19947;
	ADCommand_ID_19966.platooning = DPadUp_ID_19940;
	
	
	
}
