/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Message_Sender_ID_46097.h"

GEN_TYPE_PlatoonInformation platoonInfo_ID_47361;

GEN_TYPE_boolean noval_platoonInfo_ID_47361;

GEN_TYPE_Message_Type sendMessageType_ID_47366;

GEN_TYPE_boolean noval_sendMessageType_ID_47366;

GEN_TYPE_int OldCount_ID_54375;

GEN_TYPE_boolean noval_OldCount_ID_54375;

GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_46111;

GEN_TYPE_boolean noval_sendPlatoonMessage_ID_46111;

GEN_TYPE_MessageFuse sendFuse_ID_47011;

GEN_TYPE_boolean noval_sendFuse_ID_47011;

GEN_TYPE_MessageHandshake sendHandshake_ID_48439;

GEN_TYPE_boolean noval_sendHandshake_ID_48439;

GEN_TYPE_MessageSplit sendSplit_ID_50500;

GEN_TYPE_boolean noval_sendSplit_ID_50500;

GEN_TYPE_MessageLeave sendLeave_ID_50507;

GEN_TYPE_boolean noval_sendLeave_ID_50507;

GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_54029;

GEN_TYPE_boolean noval_sendLeaderHB_ID_54029;

GEN_TYPE_int NewCount_ID_54366;

GEN_TYPE_boolean noval_NewCount_ID_54366;

GEN_TYPE_MessageNewLeader sendNewLeader_ID_57722;

GEN_TYPE_boolean noval_sendNewLeader_ID_57722;

GEN_TYPE_MessageFollower sendFollowerMessage_ID_57780;

GEN_TYPE_boolean noval_sendFollowerMessage_ID_57780;

void clear_inputs_Message_Sender_ID_46097(){
	noval_platoonInfo_ID_47361 = true;
	noval_sendMessageType_ID_47366 = true;
	noval_OldCount_ID_54375 = true;
}

void clear_outputs_Message_Sender_ID_46097(){
	noval_sendPlatoonMessage_ID_46111 = true;
	noval_sendFuse_ID_47011 = true;
	noval_sendHandshake_ID_48439 = true;
	noval_sendSplit_ID_50500 = true;
	noval_sendLeave_ID_50507 = true;
	noval_sendLeaderHB_ID_54029 = true;
	noval_NewCount_ID_54366 = true;
	noval_sendNewLeader_ID_57722 = true;
	noval_sendFollowerMessage_ID_57780 = true;
}

void init_Message_Sender_ID_46097(){
	noval_sendPlatoonMessage_ID_46111 = true;
	noval_sendFuse_ID_47011 = true;
	noval_sendHandshake_ID_48439 = true;
	noval_sendSplit_ID_50500 = true;
	noval_sendLeave_ID_50507 = true;
	noval_sendLeaderHB_ID_54029 = true;
	noval_NewCount_ID_54366 = true;
	noval_sendNewLeader_ID_57722 = true;
	noval_sendFollowerMessage_ID_57780 = true;
}

void perform_step_Message_Sender_ID_46097(){
	clear_outputs_Message_Sender_ID_46097();
	if (!(noval_platoonInfo_ID_47361 == true) && !(noval_sendMessageType_ID_47366 == true)) {
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == platoon()) {
			if (!(noval_OldCount_ID_54375 == true) && OldCount_ID_54375 >= 10) {
				noval_sendLeaderHB_ID_54029 = false;
				sendLeaderHB_ID_54029.isLeader = true;
				sendLeaderHB_ID_54029.id = platoonInfo_ID_47361.id;
				sendLeaderHB_ID_54029.vehicleID = roverID();
				sendLeaderHB_ID_54029.EB = false;
				sendLeaderHB_ID_54029.listParticipants = platoonInfo_ID_47361.participants;
				
				
				noval_NewCount_ID_54366 = false;
				NewCount_ID_54366 = 0;
				
			}
			else {
				noval_sendPlatoonMessage_ID_46111 = false;
				sendPlatoonMessage_ID_46111.tailID = platoonInfo_ID_47361.tailID;
				sendPlatoonMessage_ID_46111.platoonID = platoonInfo_ID_47361.id;
				sendPlatoonMessage_ID_46111.id = platoonInfo_ID_47361.id;
				sendPlatoonMessage_ID_46111.leaderID = platoonInfo_ID_47361.leaderID;
				
				
				noval_NewCount_ID_54366 = noval_OldCount_ID_54375;
				if (!noval_OldCount_ID_54375) {
					NewCount_ID_54366 = OldCount_ID_54375;
				}
				
			}
		}
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == newLeader()) {
			noval_sendNewLeader_ID_57722 = false;
			sendNewLeader_ID_57722.senderID = platoonInfo_ID_47361.leaderID;
			sendNewLeader_ID_57722.newLeaderID = platoonInfo_ID_47361.leaderID;
			sendNewLeader_ID_57722.id = platoonInfo_ID_47361.id;
			sendNewLeader_ID_57722.oldLeaderID = platoonInfo_ID_47361.oldLeaderID;
			
			
		}
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == fuse()) {
			noval_sendFuse_ID_47011 = false;
			sendFuse_ID_47011.targetLeaderID = platoonInfo_ID_47361.id;
			sendFuse_ID_47011.id = platoonInfo_ID_47361.id;
			sendFuse_ID_47011.listSenderPlatoonMembers = platoonInfo_ID_47361.participants;
			sendFuse_ID_47011.senderLeaderID = platoonInfo_ID_47361.leaderID;
			
			
		}
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == handshake()) {
			noval_sendHandshake_ID_48439 = false;
			sendHandshake_ID_48439.senderID = roverID();
			sendHandshake_ID_48439.action = 0;
			sendHandshake_ID_48439.id = platoonInfo_ID_47361.id;
			
			
		}
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == split()) {
			noval_sendSplit_ID_50500 = false;
			sendSplit_ID_50500.newLeaderID = roverID();
			sendSplit_ID_50500.id = platoonInfo_ID_47361.id;
			
			
		}
		if (noval_sendMessageType_ID_47366 == false && sendMessageType_ID_47366 == leave()) {
			noval_sendLeave_ID_50507 = false;
			sendLeave_ID_50507.id = platoonInfo_ID_47361.id;
			sendLeave_ID_50507.vehicleID = roverID();
			
			
		}
	}
	return;
	
}
