/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/Message_Handler_ID_45890.h"

GEN_TYPE_MessagePlatoon receivePlatoonMessage_ID_45898;

GEN_TYPE_boolean noval_receivePlatoonMessage_ID_45898;

GEN_TYPE_MessageFuse receiveFuse_ID_46447;

GEN_TYPE_boolean noval_receiveFuse_ID_46447;

GEN_TYPE_MessageHandshake receiveHandshake_ID_48434;

GEN_TYPE_boolean noval_receiveHandshake_ID_48434;

GEN_TYPE_MessageLeave receiveLeave_ID_50488;

GEN_TYPE_boolean noval_receiveLeave_ID_50488;

GEN_TYPE_MessageSplit receiveSplit_ID_50495;

GEN_TYPE_boolean noval_receiveSplit_ID_50495;

GEN_TYPE_MessageLeaderHB receiveLeaderHB_ID_54024;

GEN_TYPE_boolean noval_receiveLeaderHB_ID_54024;

GEN_TYPE_MessageNewLeader receiveNewLeader_ID_57717;

GEN_TYPE_boolean noval_receiveNewLeader_ID_57717;

GEN_TYPE_MessageFollower receiveFollowerMessage_ID_57769;

GEN_TYPE_boolean noval_receiveFollowerMessage_ID_57769;

GEN_TYPE_Message_Type receiveMessageType_ID_45904;

GEN_TYPE_boolean noval_receiveMessageType_ID_45904;

GEN_TYPE_PlatoonInformation platoonInfoOut_ID_46426;

GEN_TYPE_boolean noval_platoonInfoOut_ID_46426;

void clear_inputs_Message_Handler_ID_45890(){
	noval_receivePlatoonMessage_ID_45898 = true;
	noval_receiveFuse_ID_46447 = true;
	noval_receiveHandshake_ID_48434 = true;
	noval_receiveLeave_ID_50488 = true;
	noval_receiveSplit_ID_50495 = true;
	noval_receiveLeaderHB_ID_54024 = true;
	noval_receiveNewLeader_ID_57717 = true;
	noval_receiveFollowerMessage_ID_57769 = true;
}

void clear_outputs_Message_Handler_ID_45890(){
	noval_receiveMessageType_ID_45904 = true;
	noval_platoonInfoOut_ID_46426 = true;
}

void init_Message_Handler_ID_45890(){
	noval_receiveMessageType_ID_45904 = true;
	noval_platoonInfoOut_ID_46426 = true;
}

void perform_step_Message_Handler_ID_45890(){
	clear_outputs_Message_Handler_ID_45890();
	if (!(noval_receivePlatoonMessage_ID_45898 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = platoon();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = receivePlatoonMessage_ID_45898.tailID;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receivePlatoonMessage_ID_45898.platoonID;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receivePlatoonMessage_ID_45898.leaderID;
		platoonInfoOut_ID_46426.myPosition = 0;
		(platoonInfoOut_ID_46426.participants.content)[0] = 0;
		(platoonInfoOut_ID_46426.participants.content)[1] = 0;
		(platoonInfoOut_ID_46426.participants.content)[2] = 0;
		(platoonInfoOut_ID_46426.participants.content)[3] = 0;
		(platoonInfoOut_ID_46426.participants.content)[4] = 0;
		
		
		
	}
	if (!(noval_receiveFuse_ID_46447 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = fuse();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receiveFuse_ID_46447.targetLeaderID;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receiveFuse_ID_46447.senderLeaderID;
		platoonInfoOut_ID_46426.myPosition = 0;
		platoonInfoOut_ID_46426.participants = receiveFuse_ID_46447.listSenderPlatoonMembers;
		
		
	}
	if (!(noval_receiveHandshake_ID_48434 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = handshake();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receiveHandshake_ID_48434.id;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receiveHandshake_ID_48434.senderID;
		platoonInfoOut_ID_46426.myPosition = 0;
		(platoonInfoOut_ID_46426.participants.content)[0] = 0;
		(platoonInfoOut_ID_46426.participants.content)[1] = 0;
		(platoonInfoOut_ID_46426.participants.content)[2] = 0;
		(platoonInfoOut_ID_46426.participants.content)[3] = 0;
		(platoonInfoOut_ID_46426.participants.content)[4] = 0;
		
		
		
	}
	if (!(noval_receiveSplit_ID_50495 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = split();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = 0;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receiveSplit_ID_50495.newLeaderID;
		platoonInfoOut_ID_46426.myPosition = 0;
		(platoonInfoOut_ID_46426.participants.content)[0] = 0;
		(platoonInfoOut_ID_46426.participants.content)[1] = 0;
		(platoonInfoOut_ID_46426.participants.content)[2] = 0;
		(platoonInfoOut_ID_46426.participants.content)[3] = 0;
		(platoonInfoOut_ID_46426.participants.content)[4] = 0;
		
		
		
	}
	if (!(noval_receiveLeave_ID_50488 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = leave();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receiveLeave_ID_50488.id;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receiveLeave_ID_50488.vehicleID;
		platoonInfoOut_ID_46426.myPosition = 0;
		(platoonInfoOut_ID_46426.participants.content)[0] = 0;
		(platoonInfoOut_ID_46426.participants.content)[1] = 0;
		(platoonInfoOut_ID_46426.participants.content)[2] = 0;
		(platoonInfoOut_ID_46426.participants.content)[3] = 0;
		(platoonInfoOut_ID_46426.participants.content)[4] = 0;
		
		
		
	}
	if (!(noval_receiveLeaderHB_ID_54024 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = heartbeat();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receiveLeaderHB_ID_54024.id;
		platoonInfoOut_ID_46426.oldLeaderID = 0;
		platoonInfoOut_ID_46426.leaderID = receiveLeaderHB_ID_54024.vehicleID;
		platoonInfoOut_ID_46426.myPosition = 0;
		platoonInfoOut_ID_46426.participants = receiveLeaderHB_ID_54024.listParticipants;
		
		
	}
	if (!(noval_receiveNewLeader_ID_57717 == true)) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = newLeader();
		
		noval_platoonInfoOut_ID_46426 = false;
		platoonInfoOut_ID_46426.tailID = 0;
		platoonInfoOut_ID_46426.amount = 0;
		platoonInfoOut_ID_46426.id = receiveNewLeader_ID_57717.id;
		platoonInfoOut_ID_46426.oldLeaderID = receiveNewLeader_ID_57717.oldLeaderID;
		platoonInfoOut_ID_46426.leaderID = receiveNewLeader_ID_57717.newLeaderID;
		platoonInfoOut_ID_46426.myPosition = 0;
		(platoonInfoOut_ID_46426.participants.content)[0] = 0;
		(platoonInfoOut_ID_46426.participants.content)[1] = 0;
		(platoonInfoOut_ID_46426.participants.content)[2] = 0;
		(platoonInfoOut_ID_46426.participants.content)[3] = 0;
		(platoonInfoOut_ID_46426.participants.content)[4] = 0;
		
		
		
	}
	if ((((noval_receivePlatoonMessage_ID_45898 == true && noval_receiveFuse_ID_46447 == true) && noval_receiveHandshake_ID_48434 == true) && noval_receiveSplit_ID_50495 == true) && noval_receiveLeave_ID_50488 == true) {
		noval_receiveMessageType_ID_45904 = false;
		receiveMessageType_ID_45904 = no_message();
		
	}
	
}
