/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/REMOVED_ID_44654.h"

GEN_TYPE_double VelocityFrontObstacleIn_ID_44670;

GEN_TYPE_boolean noval_VelocityFrontObstacleIn_ID_44670;

GEN_TYPE_double VelocityFrontObstacle_ID_44661;

GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_44661;

void clear_inputs_REMOVED_ID_44654(){
	noval_VelocityFrontObstacleIn_ID_44670 = true;
}

void clear_outputs_REMOVED_ID_44654(){
	noval_VelocityFrontObstacle_ID_44661 = true;
}

void init_REMOVED_ID_44654(){
	noval_VelocityFrontObstacle_ID_44661 = true;
}

void perform_step_REMOVED_ID_44654(){
	clear_outputs_REMOVED_ID_44654();
	noval_VelocityFrontObstacle_ID_44661 = false;
	VelocityFrontObstacle_ID_44661 = 0.0;
	
	return;
	
}
