/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#include "inc-gen/SumUpControl_ID_24113.h"

GEN_TYPE_AD_Commands platooning_ID_24126;

GEN_TYPE_boolean noval_platooning_ID_24126;

GEN_TYPE_boolean fuseIn_ID_27245;

GEN_TYPE_boolean noval_fuseIn_ID_27245;

GEN_TYPE_boolean splitIn_ID_27254;

GEN_TYPE_boolean noval_splitIn_ID_27254;

GEN_TYPE_ADOnOffCommands Control_AD_ID_24135;

GEN_TYPE_boolean noval_Control_AD_ID_24135;

GEN_TYPE_int HERETOCHECK_ID_24150;

GEN_TYPE_boolean noval_HERETOCHECK_ID_24150;

void clear_inputs_SumUpControl_ID_24113(){
	noval_platooning_ID_24126 = true;
	noval_fuseIn_ID_27245 = true;
	noval_splitIn_ID_27254 = true;
}

void clear_outputs_SumUpControl_ID_24113(){
	noval_Control_AD_ID_24135 = true;
	noval_HERETOCHECK_ID_24150 = true;
}

void init_SumUpControl_ID_24113(){
	noval_Control_AD_ID_24135 = true;
	noval_HERETOCHECK_ID_24150 = true;
}

void perform_step_SumUpControl_ID_24113(){
	clear_outputs_SumUpControl_ID_24113();
	noval_Control_AD_ID_24135 = false;
	Control_AD_ID_24135.fuse = fuseIn_ID_27245;
	Control_AD_ID_24135.split = splitIn_ID_27254;
	Control_AD_ID_24135.platooning = platooning_ID_24126;
	
	
	return;
	
}
