/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_ACC_Error_ID_44576_h
#define __HEADER_ACC_Error_ID_44576_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetDistance_ID_44585;

extern GEN_TYPE_boolean noval_TargetDistance_ID_44585;

extern GEN_TYPE_double DistanceFront_ID_44592;

extern GEN_TYPE_boolean noval_DistanceFront_ID_44592;

extern GEN_TYPE_double Error_ID_44634;

extern GEN_TYPE_boolean noval_Error_ID_44634;

extern void clear_inputs_ACC_Error_ID_44576();

extern void clear_outputs_ACC_Error_ID_44576();

extern void init_ACC_Error_ID_44576();

extern void perform_step_ACC_Error_ID_44576();

#endif // __HEADER_ACC_Error_ID_44576_h
