/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Control_States_ID_45920_h
#define __HEADER_Control_States_ID_45920_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetVelocity_ID_47833;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_47833;

extern GEN_TYPE_double MaxAcceleration_ID_47842;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_47842;

extern GEN_TYPE_double SteeringAngle_ID_47851;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_47851;

extern GEN_TYPE_PlatoonState platoonState_ID_50203;

extern GEN_TYPE_boolean noval_platoonState_ID_50203;

extern GEN_TYPE_double TargetVelocityAD_ID_47801;

extern GEN_TYPE_boolean noval_TargetVelocityAD_ID_47801;

extern GEN_TYPE_double MaxAccelerationAD_ID_47808;

extern GEN_TYPE_boolean noval_MaxAccelerationAD_ID_47808;

extern GEN_TYPE_double SteeringAngleAD_ID_47815;

extern GEN_TYPE_boolean noval_SteeringAngleAD_ID_47815;

extern GEN_TYPE_boolean platooningOff_ID_50155;

extern GEN_TYPE_boolean noval_platooningOff_ID_50155;

extern void clear_inputs_Control_States_ID_45920();

extern void clear_outputs_Control_States_ID_45920();

extern void init_Control_States_ID_45920();

extern void perform_step_Control_States_ID_45920();

#endif // __HEADER_Control_States_ID_45920_h
