/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Coordinator_ID_29204_h
#define __HEADER_Coordinator_ID_29204_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int RumbleLW_In_ID_30662;

extern GEN_TYPE_boolean noval_RumbleLW_In_ID_30662;

extern GEN_TYPE_int RumbleLK_In_ID_29222;

extern GEN_TYPE_boolean noval_RumbleLK_In_ID_29222;

extern GEN_TYPE_int RumbleWeak_Out_ID_29233;

extern GEN_TYPE_boolean noval_RumbleWeak_Out_ID_29233;

extern void clear_inputs_Coordinator_ID_29204();

extern void clear_outputs_Coordinator_ID_29204();

extern void init_Coordinator_ID_29204();

extern void perform_step_Coordinator_ID_29204();

#endif // __HEADER_Coordinator_ID_29204_h
