/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_DA_Plausibilization_Test_ID_10270_h
#define __HEADER_DA_Plausibilization_Test_ID_10270_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_16169;

extern GEN_TYPE_boolean noval_DA_States_ID_16169;

extern GEN_TYPE_double MaxAccelerationMD_ID_10287;

extern GEN_TYPE_boolean noval_MaxAccelerationMD_ID_10287;

extern GEN_TYPE_double MaxAccelerationEB_ID_29313;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29313;

extern GEN_TYPE_double TargetVelocityMD_ID_10301;

extern GEN_TYPE_boolean noval_TargetVelocityMD_ID_10301;

extern GEN_TYPE_double TargetVelocityDA_ID_10308;

extern GEN_TYPE_boolean noval_TargetVelocityDA_ID_10308;

extern GEN_TYPE_double SteeringAngleDA_ID_16188;

extern GEN_TYPE_boolean noval_SteeringAngleDA_ID_16188;

extern GEN_TYPE_double SteeringAngleMD_ID_16902;

extern GEN_TYPE_boolean noval_SteeringAngleMD_ID_16902;

extern GEN_TYPE_boolean Platooning_IsLeader_ID_29659;

extern GEN_TYPE_boolean noval_Platooning_IsLeader_ID_29659;

extern GEN_TYPE_boolean platooningOff_ID_29668;

extern GEN_TYPE_boolean noval_platooningOff_ID_29668;

extern GEN_TYPE_boolean ForceEBOff_ID_44971;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_44971;

extern GEN_TYPE_PlatoonState platoonState_ID_61160;

extern GEN_TYPE_boolean noval_platoonState_ID_61160;

extern GEN_TYPE_boolean ACC_On_Correct_ID_16267;

extern GEN_TYPE_boolean noval_ACC_On_Correct_ID_16267;

extern GEN_TYPE_boolean Shutdown_ID_17990;

extern GEN_TYPE_boolean noval_Shutdown_ID_17990;

extern GEN_TYPE_boolean ACC_TurnOff_ID_16218;

extern GEN_TYPE_boolean noval_ACC_TurnOff_ID_16218;

extern GEN_TYPE_boolean LK_On_Correct_ID_16193;

extern GEN_TYPE_boolean noval_LK_On_Correct_ID_16193;

extern GEN_TYPE_boolean LK_TurnOff_ID_16227;

extern GEN_TYPE_boolean noval_LK_TurnOff_ID_16227;

extern void clear_inputs_DA_Plausibilization_Test_ID_10270();

extern void clear_outputs_DA_Plausibilization_Test_ID_10270();

extern void init_DA_Plausibilization_Test_ID_10270();

extern void perform_step_DA_Plausibilization_Test_ID_10270();

#endif // __HEADER_DA_Plausibilization_Test_ID_10270_h
