/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_DPadRight_ID_18732_h
#define __HEADER_DPadRight_ID_18732_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int DPadRightIn_ID_32532;

extern GEN_TYPE_boolean noval_DPadRightIn_ID_32532;

extern GEN_TYPE_KeyEvent DPadRightOut_ID_32515;

extern GEN_TYPE_boolean noval_DPadRightOut_ID_32515;

extern void clear_inputs_DPadRight_ID_18732();

extern void clear_outputs_DPadRight_ID_18732();

extern void init_DPadRight_ID_18732();

extern void perform_step_DPadRight_ID_18732();

#endif // __HEADER_DPadRight_ID_18732_h
