/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_DriveMode_Merge_ID_9317_h
#define __HEADER_DriveMode_Merge_ID_9317_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonY_ID_13692;

extern GEN_TYPE_boolean noval_ButtonY_ID_13692;

extern GEN_TYPE_int ButtonB_ID_13697;

extern GEN_TYPE_boolean noval_ButtonB_ID_13697;

extern GEN_TYPE_int ButtonA_ID_13702;

extern GEN_TYPE_boolean noval_ButtonA_ID_13702;

extern GEN_TYPE_int ButtonX_ID_13974;

extern GEN_TYPE_boolean noval_ButtonX_ID_13974;

extern GEN_TYPE_DriveModeCommands DriveModeCommands_ID_13965;

extern GEN_TYPE_boolean noval_DriveModeCommands_ID_13965;

extern void clear_inputs_DriveMode_Merge_ID_9317();

extern void clear_outputs_DriveMode_Merge_ID_9317();

extern void init_DriveMode_Merge_ID_9317();

extern void perform_step_DriveMode_Merge_ID_9317();

#endif // __HEADER_DriveMode_Merge_ID_9317_h
