/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_EB_Coordinator_ID_15303_h
#define __HEADER_EB_Coordinator_ID_15303_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriveModeSettings DriveMode_ID_31968;

extern GEN_TYPE_boolean noval_DriveMode_ID_31968;

extern GEN_TYPE_boolean CriticalSituation_ID_15314;

extern GEN_TYPE_boolean noval_CriticalSituation_ID_15314;

extern GEN_TYPE_boolean FirstCritTick_Old_ID_32322;

extern GEN_TYPE_boolean noval_FirstCritTick_Old_ID_32322;

extern GEN_TYPE_boolean Activated_ID_15312;

extern GEN_TYPE_boolean noval_Activated_ID_15312;

extern GEN_TYPE_boolean FirstCritTick_ID_32329;

extern GEN_TYPE_boolean noval_FirstCritTick_ID_32329;

extern void clear_inputs_EB_Coordinator_ID_15303();

extern void clear_outputs_EB_Coordinator_ID_15303();

extern void init_EB_Coordinator_ID_15303();

extern void perform_step_EB_Coordinator_ID_15303();

#endif // __HEADER_EB_Coordinator_ID_15303_h
