/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_EngineMode_ID_9757_h
#define __HEADER_EngineMode_ID_9757_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DriveModeSettings DriveMode_ID_12235;

extern GEN_TYPE_boolean noval_DriveMode_ID_12235;

extern GEN_TYPE_double MaxAcceleration_ID_5881;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_5881;

extern void clear_inputs_EngineMode_ID_9757();

extern void clear_outputs_EngineMode_ID_9757();

extern void init_EngineMode_ID_9757();

extern void perform_step_EngineMode_ID_9757();

#endif // __HEADER_EngineMode_ID_9757_h
