/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Error_Sum_ID_16094_h
#define __HEADER_Error_Sum_ID_16094_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double ErrorSumOut_ID_16110;

extern GEN_TYPE_boolean noval_ErrorSumOut_ID_16110;

extern GEN_TYPE_double ErrorSumIn_ID_16117;

extern GEN_TYPE_boolean noval_ErrorSumIn_ID_16117;

extern void clear_inputs_Error_Sum_ID_16094();

extern void clear_outputs_Error_Sum_ID_16094();

extern void init_Error_Sum_ID_16094();

extern void perform_step_Error_Sum_ID_16094();

#endif // __HEADER_Error_Sum_ID_16094_h
