/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Fuse_Split_ID_27169_h
#define __HEADER_Fuse_Split_ID_27169_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_AutonomousDrivingEvents ADCommand_ID_27226;

extern GEN_TYPE_boolean noval_ADCommand_ID_27226;

extern GEN_TYPE_boolean fuse_ID_27243;

extern GEN_TYPE_boolean noval_fuse_ID_27243;

extern GEN_TYPE_boolean split_ID_27252;

extern GEN_TYPE_boolean noval_split_ID_27252;

extern void clear_inputs_Fuse_Split_ID_27169();

extern void clear_outputs_Fuse_Split_ID_27169();

extern void init_Fuse_Split_ID_27169();

extern void perform_step_Fuse_Split_ID_27169();

#endif // __HEADER_Fuse_Split_ID_27169_h
