/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_GearShift_ID_15020_h
#define __HEADER_GearShift_ID_15020_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int GearShiftIn_ID_15029;

extern GEN_TYPE_boolean noval_GearShiftIn_ID_15029;

extern GEN_TYPE_int GearShift_ID_15034;

extern GEN_TYPE_boolean noval_GearShift_ID_15034;

extern void clear_inputs_GearShift_ID_15020();

extern void clear_outputs_GearShift_ID_15020();

extern void init_GearShift_ID_15020();

extern void perform_step_GearShift_ID_15020();

#endif // __HEADER_GearShift_ID_15020_h
