/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Platooning_EB_Overwrite_ID_29192_h
#define __HEADER_Platooning_EB_Overwrite_ID_29192_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean ForceEBOff_In_ID_29208;

extern GEN_TYPE_boolean noval_ForceEBOff_In_ID_29208;

extern GEN_TYPE_double MaxAccelerationEB_In_ID_29256;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_In_ID_29256;

extern GEN_TYPE_boolean platooningOff_ID_31942;

extern GEN_TYPE_boolean noval_platooningOff_ID_31942;

extern GEN_TYPE_boolean Platooning_EB_Triggered_ID_31951;

extern GEN_TYPE_boolean noval_Platooning_EB_Triggered_ID_31951;

extern GEN_TYPE_double MaxAccelerationAD_ID_31960;

extern GEN_TYPE_boolean noval_MaxAccelerationAD_ID_31960;

extern GEN_TYPE_boolean ForceEBOff_ID_44969;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_44969;

extern GEN_TYPE_double MaxAccelerationEB_ID_29311;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29311;

extern GEN_TYPE_boolean platooningOffOut_ID_29705;

extern GEN_TYPE_boolean noval_platooningOffOut_ID_29705;

extern void clear_inputs_Platooning_EB_Overwrite_ID_29192();

extern void clear_outputs_Platooning_EB_Overwrite_ID_29192();

extern void init_Platooning_EB_Overwrite_ID_29192();

extern void perform_step_Platooning_EB_Overwrite_ID_29192();

#endif // __HEADER_Platooning_EB_Overwrite_ID_29192_h
