/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Platooning_TurnOnOff_ID_20320_h
#define __HEADER_Platooning_TurnOnOff_ID_20320_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_AutonomousDrivingEvents ADCommand_ID_20336;

extern GEN_TYPE_boolean noval_ADCommand_ID_20336;

extern GEN_TYPE_AD_TurnOffCommands ADTurnOff_ID_27208;

extern GEN_TYPE_boolean noval_ADTurnOff_ID_27208;

extern GEN_TYPE_AD_Commands platooning_ID_24124;

extern GEN_TYPE_boolean noval_platooning_ID_24124;

extern void clear_inputs_Platooning_TurnOnOff_ID_20320();

extern void clear_outputs_Platooning_TurnOnOff_ID_20320();

extern void init_Platooning_TurnOnOff_ID_20320();

extern void perform_step_Platooning_TurnOnOff_ID_20320();

#endif // __HEADER_Platooning_TurnOnOff_ID_20320_h
