/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Prevent_cycle_ID_10366_h
#define __HEADER_Prevent_cycle_ID_10366_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_In_ID_16213;

extern GEN_TYPE_boolean noval_DA_TurnOff_In_ID_16213;

extern GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_Out_ID_10382;

extern GEN_TYPE_boolean noval_DA_TurnOff_Out_ID_10382;

extern void clear_inputs_Prevent_cycle_ID_10366();

extern void clear_outputs_Prevent_cycle_ID_10366();

extern void init_Prevent_cycle_ID_10366();

extern void perform_step_Prevent_cycle_ID_10366();

#endif // __HEADER_Prevent_cycle_ID_10366_h
