/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Return_ID_31841_h
#define __HEADER_Return_ID_31841_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityIn_ID_31850;

extern GEN_TYPE_boolean noval_VelocityIn_ID_31850;

extern GEN_TYPE_double VelocityReturn_ID_31857;

extern GEN_TYPE_boolean noval_VelocityReturn_ID_31857;

extern GEN_TYPE_double Velocity_ID_31863;

extern GEN_TYPE_boolean noval_Velocity_ID_31863;

extern void clear_inputs_Return_ID_31841();

extern void clear_outputs_Return_ID_31841();

extern void init_Return_ID_31841();

extern void perform_step_Return_ID_31841();

#endif // __HEADER_Return_ID_31841_h
