/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Scale_ID_10083_h
#define __HEADER_Scale_ID_10083_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double SteeringWheel_ID_12250;

extern GEN_TYPE_boolean noval_SteeringWheel_ID_12250;

extern GEN_TYPE_double Velocity_ID_12162;

extern GEN_TYPE_boolean noval_Velocity_ID_12162;

extern GEN_TYPE_double SteeringAngleMD_ID_12258;

extern GEN_TYPE_boolean noval_SteeringAngleMD_ID_12258;

extern void clear_inputs_Scale_ID_10083();

extern void clear_outputs_Scale_ID_10083();

extern void init_Scale_ID_10083();

extern void perform_step_Scale_ID_10083();

#endif // __HEADER_Scale_ID_10083_h
