/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_TargetDistance_ID_16386_h
#define __HEADER_TargetDistance_ID_16386_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityFrontObstacle_ID_16425;

extern GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_16425;

extern GEN_TYPE_double DistanceFront_ID_16430;

extern GEN_TYPE_boolean noval_DistanceFront_ID_16430;

extern GEN_TYPE_double Velocity_ID_16435;

extern GEN_TYPE_boolean noval_Velocity_ID_16435;

extern GEN_TYPE_double TimeGap_ID_44311;

extern GEN_TYPE_boolean noval_TimeGap_ID_44311;

extern GEN_TYPE_double TargetDistance_ID_44691;

extern GEN_TYPE_boolean noval_TargetDistance_ID_44691;

extern void clear_inputs_TargetDistance_ID_16386();

extern void clear_outputs_TargetDistance_ID_16386();

extern void init_TargetDistance_ID_16386();

extern void perform_step_TargetDistance_ID_16386();

#endif // __HEADER_TargetDistance_ID_16386_h
