/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Target_Velocity_ID_6883_h
#define __HEADER_Target_Velocity_ID_6883_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetVelocityMD_ID_16274;

extern GEN_TYPE_boolean noval_TargetVelocityMD_ID_16274;

extern GEN_TYPE_double TargetVelocityDA_ID_16279;

extern GEN_TYPE_boolean noval_TargetVelocityDA_ID_16279;

extern GEN_TYPE_boolean ACC_On_Correct_ID_16264;

extern GEN_TYPE_boolean noval_ACC_On_Correct_ID_16264;

extern GEN_TYPE_double MaxAccelerationEB_ID_29298;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29298;

extern GEN_TYPE_boolean ForceEBOff_ID_29244;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_29244;

extern GEN_TYPE_double TargetVelocityAD_ID_20266;

extern GEN_TYPE_boolean noval_TargetVelocityAD_ID_20266;

extern GEN_TYPE_boolean Platooning_IsLeader_ID_29679;

extern GEN_TYPE_boolean noval_Platooning_IsLeader_ID_29679;

extern GEN_TYPE_boolean platooningOff_ID_29686;

extern GEN_TYPE_boolean noval_platooningOff_ID_29686;

extern GEN_TYPE_double TargetVelocity_ID_6902;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_6902;

extern void clear_inputs_Target_Velocity_ID_6883();

extern void clear_outputs_Target_Velocity_ID_6883();

extern void init_Target_Velocity_ID_6883();

extern void perform_step_Target_Velocity_ID_6883();

#endif // __HEADER_Target_Velocity_ID_6883_h
