/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_ThrottleFusion_ID_5874_h
#define __HEADER_ThrottleFusion_ID_5874_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAcceleration_ID_5883;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_5883;

extern GEN_TYPE_double BrakePedal_ID_12255;

extern GEN_TYPE_boolean noval_BrakePedal_ID_12255;

extern GEN_TYPE_double ThrottleManual_ID_9751;

extern GEN_TYPE_boolean noval_ThrottleManual_ID_9751;

extern GEN_TYPE_double Velocity_ID_12160;

extern GEN_TYPE_boolean noval_Velocity_ID_12160;

extern GEN_TYPE_double ThrottleAutomatic_ID_11460;

extern GEN_TYPE_boolean noval_ThrottleAutomatic_ID_11460;

extern GEN_TYPE_boolean Automatic_On_ID_12471;

extern GEN_TYPE_boolean noval_Automatic_On_ID_12471;

extern GEN_TYPE_int GearManual_ID_12651;

extern GEN_TYPE_boolean noval_GearManual_ID_12651;

extern GEN_TYPE_int GearAutomatic_ID_12698;

extern GEN_TYPE_boolean noval_GearAutomatic_ID_12698;

extern GEN_TYPE_double MaxAccelerationMD_ID_12263;

extern GEN_TYPE_boolean noval_MaxAccelerationMD_ID_12263;

extern GEN_TYPE_double TargetVelocityMD_ID_12268;

extern GEN_TYPE_boolean noval_TargetVelocityMD_ID_12268;

extern GEN_TYPE_int Gear_ID_12662;

extern GEN_TYPE_boolean noval_Gear_ID_12662;

extern void clear_inputs_ThrottleFusion_ID_5874();

extern void clear_outputs_ThrottleFusion_ID_5874();

extern void init_ThrottleFusion_ID_5874();

extern void perform_step_ThrottleFusion_ID_5874();

#endif // __HEADER_ThrottleFusion_ID_5874_h
