/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_TickCounter_ID_50455_h
#define __HEADER_TickCounter_ID_50455_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int countNew_ID_50475;

extern GEN_TYPE_boolean noval_countNew_ID_50475;

extern GEN_TYPE_int countOld_ID_50464;

extern GEN_TYPE_boolean noval_countOld_ID_50464;

extern void clear_inputs_TickCounter_ID_50455();

extern void clear_outputs_TickCounter_ID_50455();

extern void init_TickCounter_ID_50455();

extern void perform_step_TickCounter_ID_50455();

#endif // __HEADER_TickCounter_ID_50455_h
