/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Transform_Input_ID_12045_h
#define __HEADER_Transform_Input_ID_12045_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double LeftStick_XIn_ID_11995;

extern GEN_TYPE_boolean noval_LeftStick_XIn_ID_11995;

extern GEN_TYPE_double RightStick_XIn_ID_12000;

extern GEN_TYPE_boolean noval_RightStick_XIn_ID_12000;

extern GEN_TYPE_double RightStick_YIn_ID_12005;

extern GEN_TYPE_boolean noval_RightStick_YIn_ID_12005;

extern GEN_TYPE_double LeftStick_YIn_ID_14666;

extern GEN_TYPE_boolean noval_LeftStick_YIn_ID_14666;

extern GEN_TYPE_double ButtonL2In_ID_14976;

extern GEN_TYPE_boolean noval_ButtonL2In_ID_14976;

extern GEN_TYPE_double ButtonR2In_ID_14983;

extern GEN_TYPE_boolean noval_ButtonR2In_ID_14983;

extern GEN_TYPE_double LeftStick_X_ID_11978;

extern GEN_TYPE_boolean noval_LeftStick_X_ID_11978;

extern GEN_TYPE_double RightStick_X_ID_11983;

extern GEN_TYPE_boolean noval_RightStick_X_ID_11983;

extern GEN_TYPE_double RightStick_Y_ID_11988;

extern GEN_TYPE_boolean noval_RightStick_Y_ID_11988;

extern GEN_TYPE_double LeftStick_Y_ID_14673;

extern GEN_TYPE_boolean noval_LeftStick_Y_ID_14673;

extern GEN_TYPE_double ButtonL2_ID_14960;

extern GEN_TYPE_boolean noval_ButtonL2_ID_14960;

extern GEN_TYPE_double ButtonR2_ID_14967;

extern GEN_TYPE_boolean noval_ButtonR2_ID_14967;

extern void clear_inputs_Transform_Input_ID_12045();

extern void clear_outputs_Transform_Input_ID_12045();

extern void init_Transform_Input_ID_12045();

extern void perform_step_Transform_Input_ID_12045();

#endif // __HEADER_Transform_Input_ID_12045_h
