/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Transit_ID_8679_h
#define __HEADER_Transit_ID_8679_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Velocity_ID_8688;

extern GEN_TYPE_boolean noval_Velocity_ID_8688;

extern GEN_TYPE_double DistanceFrontIn_ID_8695;

extern GEN_TYPE_boolean noval_DistanceFrontIn_ID_8695;

extern GEN_TYPE_LDCameraData LDCameraDataIn_ID_16886;

extern GEN_TYPE_boolean noval_LDCameraDataIn_ID_16886;

extern GEN_TYPE_double DistanceFrontOut_ID_8718;

extern GEN_TYPE_boolean noval_DistanceFrontOut_ID_8718;

extern GEN_TYPE_double VelocityOut_ID_8778;

extern GEN_TYPE_boolean noval_VelocityOut_ID_8778;

extern GEN_TYPE_LDCameraData LDCameraData_ID_16893;

extern GEN_TYPE_boolean noval_LDCameraData_ID_16893;

extern void clear_inputs_Transit_ID_8679();

extern void clear_outputs_Transit_ID_8679();

extern void init_Transit_ID_8679();

extern void perform_step_Transit_ID_8679();

#endif // __HEADER_Transit_ID_8679_h
