/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_TurnOffPlatooning_ID_46536_h
#define __HEADER_TurnOffPlatooning_ID_46536_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int status_ID_47695;

extern GEN_TYPE_boolean noval_status_ID_47695;

extern GEN_TYPE_AD_TurnOffCommands ADTurnOff_ID_46541;

extern GEN_TYPE_boolean noval_ADTurnOff_ID_46541;

extern void clear_inputs_TurnOffPlatooning_ID_46536();

extern void clear_outputs_TurnOffPlatooning_ID_46536();

extern void init_TurnOffPlatooning_ID_46536();

extern void perform_step_TurnOffPlatooning_ID_46536();

#endif // __HEADER_TurnOffPlatooning_ID_46536_h
