/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Velocity_Return_ID_31819_h
#define __HEADER_Velocity_Return_ID_31819_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double VelocityValue_ID_31828;

extern GEN_TYPE_boolean noval_VelocityValue_ID_31828;

extern GEN_TYPE_double VelocityReturn_ID_31835;

extern GEN_TYPE_boolean noval_VelocityReturn_ID_31835;

extern void clear_inputs_Velocity_Return_ID_31819();

extern void clear_outputs_Velocity_Return_ID_31819();

extern void init_Velocity_Return_ID_31819();

extern void perform_step_Velocity_Return_ID_31819();

#endif // __HEADER_Velocity_Return_ID_31819_h
