/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_Weight_Current_ID_45058_h
#define __HEADER_Weight_Current_ID_45058_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Weight_Current_ID_45064;

extern GEN_TYPE_boolean noval_Weight_Current_ID_45064;

extern void clear_inputs_Weight_Current_ID_45058();

extern void clear_outputs_Weight_Current_ID_45058();

extern void init_Weight_Current_ID_45058();

extern void perform_step_Weight_Current_ID_45058();

#endif // __HEADER_Weight_Current_ID_45058_h
