/* generated by AutoFOCUS 3 (2.14.0) on Mon Jul 08 13:45:02 CEST 2019 */
#ifndef __HEADER_WritePlatoonFile_ID_20010_h
#define __HEADER_WritePlatoonFile_ID_20010_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean Shutdown_ID_20020;

extern GEN_TYPE_boolean noval_Shutdown_ID_20020;

extern GEN_TYPE_double TargetVelocity_ID_20027;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_20027;

extern GEN_TYPE_double MaxAcceleration_ID_20034;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_20034;

extern GEN_TYPE_double Velocity_ID_20041;

extern GEN_TYPE_boolean noval_Velocity_ID_20041;

extern GEN_TYPE_double Acceleration_ID_20048;

extern GEN_TYPE_boolean noval_Acceleration_ID_20048;

extern GEN_TYPE_double SteeringAngle_ID_20055;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_20055;

extern void clear_inputs_WritePlatoonFile_ID_20010();

extern void clear_outputs_WritePlatoonFile_ID_20010();

extern void init_WritePlatoonFile_ID_20010();

extern void perform_step_WritePlatoonFile_ID_20010();

#endif // __HEADER_WritePlatoonFile_ID_20010_h
