/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/ACC_Error_Adjustment_ID_44627.h"

GEN_TYPE_double Error_ID_44636;

GEN_TYPE_boolean noval_Error_ID_44636;

GEN_TYPE_double Error_adjusted_ID_44641;

GEN_TYPE_boolean noval_Error_adjusted_ID_44641;

void clear_inputs_ACC_Error_Adjustment_ID_44627(){
	noval_Error_ID_44636 = true;
}

void clear_outputs_ACC_Error_Adjustment_ID_44627(){
	noval_Error_adjusted_ID_44641 = true;
}

void init_ACC_Error_Adjustment_ID_44627(){
	noval_Error_adjusted_ID_44641 = true;
}

void perform_step_ACC_Error_Adjustment_ID_44627(){
	clear_outputs_ACC_Error_Adjustment_ID_44627();
	if (!(noval_Error_ID_44636 == true)) {
		if (myabs(Error_ID_44636) <= 0.05) {
			noval_Error_adjusted_ID_44641 = false;
			Error_adjusted_ID_44641 = 0.0;
			
		}
		else {
			if (Error_ID_44636 >= 2.0) {
				noval_Error_adjusted_ID_44641 = false;
				Error_adjusted_ID_44641 = 2.0;
				
			}
			else {
				if (Error_ID_44636 <= -2.0) {
					noval_Error_adjusted_ID_44641 = false;
					Error_adjusted_ID_44641 = -2.0;
					
				}
				else {
					noval_Error_adjusted_ID_44641 = noval_Error_ID_44636;
					if (!noval_Error_ID_44636) {
						Error_adjusted_ID_44641 = Error_ID_44636;
					}
					
				}
			}
		}
	}
	else {
		noval_Error_adjusted_ID_44641 = true;
	}
	return;
	
}
