/* generated by AutoFOCUS 3 (2.14.0) on Fri May 03 16:11:03 CEST 2019 */
#include "inc-gen/Autonomous_Driving_ID_19261.h"

GEN_TYPE_ADOnOffCommands Control_AD_ID_23312;

GEN_TYPE_boolean noval_Control_AD_ID_23312;

GEN_TYPE_double Velocity_ID_24288;

GEN_TYPE_boolean noval_Velocity_ID_24288;

GEN_TYPE_double DistanceFront_ID_24295;

GEN_TYPE_boolean noval_DistanceFront_ID_24295;

GEN_TYPE_double VelocityFrontObstacle_ID_24302;

GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_24302;

GEN_TYPE_LDCameraData LDCameraData_ID_19358;

GEN_TYPE_boolean noval_LDCameraData_ID_19358;

GEN_TYPE_MessageSplit receiveSplit_ID_24267;

GEN_TYPE_boolean noval_receiveSplit_ID_24267;

GEN_TYPE_MessagePlatoon receivePlatoonMessage_ID_24274;

GEN_TYPE_boolean noval_receivePlatoonMessage_ID_24274;

GEN_TYPE_MessageNewLeader receiveNewLeader_ID_24260;

GEN_TYPE_boolean noval_receiveNewLeader_ID_24260;

GEN_TYPE_MessageLeave receiveLeave_ID_24253;

GEN_TYPE_boolean noval_receiveLeave_ID_24253;

GEN_TYPE_MessageLeaderHB receiveLeaderHB_ID_24246;

GEN_TYPE_boolean noval_receiveLeaderHB_ID_24246;

GEN_TYPE_MessageFuse receiveFuse_ID_24239;

GEN_TYPE_boolean noval_receiveFuse_ID_24239;

GEN_TYPE_MessageFollower receiveFollowerMessage_ID_24281;

GEN_TYPE_boolean noval_receiveFollowerMessage_ID_24281;

GEN_TYPE_MessageHandshake receiveHandshake_ID_28292;

GEN_TYPE_boolean noval_receiveHandshake_ID_28292;

GEN_TYPE_boolean EB_On_ID_28530;

GEN_TYPE_boolean noval_EB_On_ID_28530;

GEN_TYPE_double SteeringAngle_ID_28588;

GEN_TYPE_boolean noval_SteeringAngle_ID_28588;

GEN_TYPE_double BrakePedal_ID_29921;

GEN_TYPE_boolean noval_BrakePedal_ID_29921;

GEN_TYPE_double MaxAcceleration_ID_31703;

GEN_TYPE_boolean noval_MaxAcceleration_ID_31703;

GEN_TYPE_double TargetVelocity_ID_31767;

GEN_TYPE_boolean noval_TargetVelocity_ID_31767;

GEN_TYPE_double MaxAccelerationAD_ID_24484;

GEN_TYPE_boolean noval_MaxAccelerationAD_ID_24484;

GEN_TYPE_double TargetVelocityAD_ID_24498;

GEN_TYPE_boolean noval_TargetVelocityAD_ID_24498;

GEN_TYPE_double SteeringAngleAD_ID_24491;

GEN_TYPE_boolean noval_SteeringAngleAD_ID_24491;

GEN_TYPE_AD_TurnOffCommands ADTurnOff_ID_20493;

GEN_TYPE_boolean noval_ADTurnOff_ID_20493;

GEN_TYPE_MessageSplit sendSplit_ID_24234;

GEN_TYPE_boolean noval_sendSplit_ID_24234;

GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_24227;

GEN_TYPE_boolean noval_sendPlatoonMessage_ID_24227;

GEN_TYPE_MessageNewLeader sendNewLeader_ID_24220;

GEN_TYPE_boolean noval_sendNewLeader_ID_24220;

GEN_TYPE_MessageLeave sendLeave_ID_24213;

GEN_TYPE_boolean noval_sendLeave_ID_24213;

GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_24206;

GEN_TYPE_boolean noval_sendLeaderHB_ID_24206;

GEN_TYPE_MessageFuse sendFuse_ID_24199;

GEN_TYPE_boolean noval_sendFuse_ID_24199;

GEN_TYPE_MessageFollower sendFollowerMessage_ID_24192;

GEN_TYPE_boolean noval_sendFollowerMessage_ID_24192;

GEN_TYPE_MessageHandshake sendHandshake_ID_28287;

GEN_TYPE_boolean noval_sendHandshake_ID_28287;

GEN_TYPE_boolean Platooning_EB_Triggered_ID_29187;

GEN_TYPE_boolean noval_Platooning_EB_Triggered_ID_29187;

GEN_TYPE_boolean platooningOff_ID_29230;

GEN_TYPE_boolean noval_platooningOff_ID_29230;

GEN_TYPE_boolean IsLeader_ID_29611;

GEN_TYPE_boolean noval_IsLeader_ID_29611;

GEN_TYPE_int leaderIDtoCodeGen_ID_31112;

GEN_TYPE_boolean noval_leaderIDtoCodeGen_ID_31112;

GEN_TYPE_int frontVehicleIDtoCodeGen_ID_31105;

GEN_TYPE_boolean noval_frontVehicleIDtoCodeGen_ID_31105;

void clear_inputs_Autonomous_Driving_ID_19261(){
	noval_Control_AD_ID_23312 = true;
	noval_Velocity_ID_24288 = true;
	noval_DistanceFront_ID_24295 = true;
	noval_VelocityFrontObstacle_ID_24302 = true;
	noval_LDCameraData_ID_19358 = true;
	noval_receiveSplit_ID_24267 = true;
	noval_receivePlatoonMessage_ID_24274 = true;
	noval_receiveNewLeader_ID_24260 = true;
	noval_receiveLeave_ID_24253 = true;
	noval_receiveLeaderHB_ID_24246 = true;
	noval_receiveFuse_ID_24239 = true;
	noval_receiveFollowerMessage_ID_24281 = true;
	noval_receiveHandshake_ID_28292 = true;
	noval_EB_On_ID_28530 = true;
	noval_SteeringAngle_ID_28588 = true;
	noval_BrakePedal_ID_29921 = true;
	noval_MaxAcceleration_ID_31703 = true;
	noval_TargetVelocity_ID_31767 = true;
}

void clear_outputs_Autonomous_Driving_ID_19261(){
	noval_MaxAccelerationAD_ID_24484 = true;
	noval_TargetVelocityAD_ID_24498 = true;
	noval_SteeringAngleAD_ID_24491 = true;
	noval_ADTurnOff_ID_20493 = true;
	noval_sendSplit_ID_24234 = true;
	noval_sendPlatoonMessage_ID_24227 = true;
	noval_sendNewLeader_ID_24220 = true;
	noval_sendLeave_ID_24213 = true;
	noval_sendLeaderHB_ID_24206 = true;
	noval_sendFuse_ID_24199 = true;
	noval_sendFollowerMessage_ID_24192 = true;
	noval_sendHandshake_ID_28287 = true;
	noval_Platooning_EB_Triggered_ID_29187 = true;
	noval_platooningOff_ID_29230 = true;
	noval_IsLeader_ID_29611 = true;
	noval_leaderIDtoCodeGen_ID_31112 = true;
	noval_frontVehicleIDtoCodeGen_ID_31105 = true;
}

void init_Autonomous_Driving_ID_19261(){
	noval_MaxAccelerationAD_ID_24484 = true;
	noval_TargetVelocityAD_ID_24498 = true;
	noval_SteeringAngleAD_ID_24491 = true;
	noval_ADTurnOff_ID_20493 = true;
	noval_sendSplit_ID_24234 = true;
	noval_sendPlatoonMessage_ID_24227 = true;
	noval_sendNewLeader_ID_24220 = true;
	noval_sendLeave_ID_24213 = true;
	noval_sendLeaderHB_ID_24206 = true;
	noval_sendFuse_ID_24199 = true;
	noval_sendFollowerMessage_ID_24192 = true;
	noval_sendHandshake_ID_28287 = true;
	noval_Platooning_EB_Triggered_ID_29187 = true;
	noval_platooningOff_ID_29230 = true;
	noval_IsLeader_ID_29611 = true;
	noval_leaderIDtoCodeGen_ID_31112 = true;
	noval_frontVehicleIDtoCodeGen_ID_31105 = true;
}

void perform_step_Autonomous_Driving_ID_19261(){
	clear_outputs_Autonomous_Driving_ID_19261();
	return;
	
}
