/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/D_term_ID_16019.h"

GEN_TYPE_double Error_ID_16087;

GEN_TYPE_boolean noval_Error_ID_16087;

GEN_TYPE_double LastErrorIn_ID_16137;

GEN_TYPE_boolean noval_LastErrorIn_ID_16137;

GEN_TYPE_double Coef_D_ID_16046;

GEN_TYPE_boolean noval_Coef_D_ID_16046;

GEN_TYPE_double LastErrorOut_ID_16126;

GEN_TYPE_boolean noval_LastErrorOut_ID_16126;

void clear_inputs_D_term_ID_16019(){
	noval_Error_ID_16087 = true;
	noval_LastErrorIn_ID_16137 = true;
}

void clear_outputs_D_term_ID_16019(){
	noval_Coef_D_ID_16046 = true;
	noval_LastErrorOut_ID_16126 = true;
}

void init_D_term_ID_16019(){
	noval_Coef_D_ID_16046 = true;
	noval_LastErrorOut_ID_16126 = true;
}

void perform_step_D_term_ID_16019(){
	clear_outputs_D_term_ID_16019();
	if ((noval_Error_ID_16087 == true || noval_LastErrorIn_ID_16137 == true) || noval_Error_ID_16087 == false && Error_ID_16087 == 0.0) {
		noval_Coef_D_ID_16046 = false;
		Coef_D_ID_16046 = 0.0;
		
	}
	else {
		noval_Coef_D_ID_16046 = false;
		Coef_D_ID_16046 = (COEFFICIENT_LK_CONTROLLER_D() / TICK_TIME()) * (Error_ID_16087 - LastErrorIn_ID_16137);
		
	}
	noval_LastErrorOut_ID_16126 = noval_Error_ID_16087;
	if (!noval_Error_ID_16087) {
		LastErrorOut_ID_16126 = Error_ID_16087;
	}
	
	return;
	
}
