/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/EB_Memory_ID_15316.h"

GEN_TYPE_boolean Activated_ID_15341;

GEN_TYPE_boolean noval_Activated_ID_15341;

GEN_TYPE_double MaxAccelerationEB_ID_15380;

GEN_TYPE_boolean noval_MaxAccelerationEB_ID_15380;

GEN_TYPE_boolean RumbleEB_ID_17262;

GEN_TYPE_boolean noval_RumbleEB_ID_17262;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Activated_ID_15336();

static GEN_TYPE_boolean fire_transition_Deactivated_ID_15339();

static GEN_TYPE_boolean fire_state_EB_Off_ID_15323();

static GEN_TYPE_boolean fire_state_EB_On_ID_15328();

void clear_inputs_EB_Memory_ID_15316(){
	noval_Activated_ID_15341 = true;
}

void clear_outputs_EB_Memory_ID_15316(){
	noval_MaxAccelerationEB_ID_15380 = true;
	noval_RumbleEB_ID_17262 = true;
}

void init_EB_Memory_ID_15316(){
	noval_MaxAccelerationEB_ID_15380 = true;
	noval_RumbleEB_ID_17262 = true;
	current_state = 15323;
}

void perform_step_EB_Memory_ID_15316(){
	clear_outputs_EB_Memory_ID_15316();
	if (current_state == 15328) {
		fire_state_EB_On_ID_15328();
	}
	else {
		if (current_state == 15323) {
			fire_state_EB_Off_ID_15323();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Activated_ID_15336(){
	if (!(noval_Activated_ID_15341 == true) && (noval_Activated_ID_15341 == false && Activated_ID_15341 == true)) {
		noval_MaxAccelerationEB_ID_15380 = false;
		MaxAccelerationEB_ID_15380 = MAX_BRAKE_VALUE();
		
		noval_RumbleEB_ID_17262 = false;
		RumbleEB_ID_17262 = true;
		
		current_state = 15328;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Deactivated_ID_15339(){
	if (!(noval_Activated_ID_15341 == true) && (noval_Activated_ID_15341 == false && Activated_ID_15341 == false)) {
		noval_MaxAccelerationEB_ID_15380 = true;
		noval_RumbleEB_ID_17262 = false;
		RumbleEB_ID_17262 = false;
		
		current_state = 15323;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_EB_Off_ID_15323(){
	if (!fire_transition_Activated_ID_15336()) {
		noval_MaxAccelerationEB_ID_15380 = true;
		noval_RumbleEB_ID_17262 = false;
		RumbleEB_ID_17262 = false;
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_EB_On_ID_15328(){
	if (!fire_transition_Deactivated_ID_15339()) {
		noval_MaxAccelerationEB_ID_15380 = false;
		MaxAccelerationEB_ID_15380 = MAX_BRAKE_VALUE();
		
		noval_RumbleEB_ID_17262 = false;
		RumbleEB_ID_17262 = true;
		
	}
	return true;
}
