/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/GearShift_ID_15020.h"

GEN_TYPE_int GearShiftIn_ID_15029;

GEN_TYPE_boolean noval_GearShiftIn_ID_15029;

GEN_TYPE_int GearShift_ID_15034;

GEN_TYPE_boolean noval_GearShift_ID_15034;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Up_ID_15054();

static GEN_TYPE_boolean fire_transition_Idle_ID_15060();

static GEN_TYPE_boolean fire_transition_Down_ID_15064();

static GEN_TYPE_boolean fire_transition_Up_ID_15068();

static GEN_TYPE_boolean fire_transition_Down_ID_15071();

static GEN_TYPE_boolean fire_transition_Idle_ID_15075();

static GEN_TYPE_boolean fire_state_Nothing_ID_15041();

static GEN_TYPE_boolean fire_state_Up_ID_15046();

static GEN_TYPE_boolean fire_state_Down_ID_15049();

void clear_inputs_GearShift_ID_15020(){
	noval_GearShiftIn_ID_15029 = true;
}

void clear_outputs_GearShift_ID_15020(){
	noval_GearShift_ID_15034 = true;
}

void init_GearShift_ID_15020(){
	noval_GearShift_ID_15034 = true;
	current_state = 15041;
}

void perform_step_GearShift_ID_15020(){
	clear_outputs_GearShift_ID_15020();
	if (current_state == 15049) {
		fire_state_Down_ID_15049();
	}
	else {
		if (current_state == 15046) {
			fire_state_Up_ID_15046();
		}
		else {
			if (current_state == 15041) {
				fire_state_Nothing_ID_15041();
			}
		}
	}
}

static GEN_TYPE_boolean fire_transition_Up_ID_15054(){
	if (!(noval_GearShiftIn_ID_15029 == true) && GearShiftIn_ID_15029 > 0) {
		noval_GearShift_ID_15034 = false;
		GearShift_ID_15034 = 1;
		
		current_state = 15046;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Idle_ID_15060(){
	if (noval_GearShiftIn_ID_15029 == true || noval_GearShiftIn_ID_15029 == false && GearShiftIn_ID_15029 == 0) {
		noval_GearShift_ID_15034 = true;
		current_state = 15041;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Down_ID_15064(){
	if (!(noval_GearShiftIn_ID_15029 == true) && GearShiftIn_ID_15029 < 0) {
		noval_GearShift_ID_15034 = false;
		GearShift_ID_15034 = -1;
		
		current_state = 15049;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Up_ID_15068(){
	if (!(noval_GearShiftIn_ID_15029 == true) && GearShiftIn_ID_15029 > 0) {
		noval_GearShift_ID_15034 = false;
		GearShift_ID_15034 = 1;
		
		current_state = 15046;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Down_ID_15071(){
	if (!(noval_GearShiftIn_ID_15029 == true) && GearShiftIn_ID_15029 < 0) {
		noval_GearShift_ID_15034 = false;
		GearShift_ID_15034 = -1;
		
		current_state = 15049;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Idle_ID_15075(){
	if (noval_GearShiftIn_ID_15029 == true || noval_GearShiftIn_ID_15029 == false && GearShiftIn_ID_15029 == 0) {
		noval_GearShift_ID_15034 = true;
		current_state = 15041;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Nothing_ID_15041(){
	if (!(fire_transition_Up_ID_15054() || fire_transition_Down_ID_15071())) {
		noval_GearShift_ID_15034 = true;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Up_ID_15046(){
	if (!(fire_transition_Idle_ID_15060() || fire_transition_Down_ID_15064())) {
		noval_GearShift_ID_15034 = true;
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Down_ID_15049(){
	if (!(fire_transition_Up_ID_15068() || fire_transition_Idle_ID_15075())) {
		noval_GearShift_ID_15034 = true;
	}
	return true;
}
