/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/History_ID_45048.h"

GEN_TYPE_double Output_ID_45054;

GEN_TYPE_boolean noval_Output_ID_45054;

GEN_TYPE_double History_ID_45056;

GEN_TYPE_boolean noval_History_ID_45056;

void clear_inputs_History_ID_45048(){
	noval_Output_ID_45054 = true;
}

void clear_outputs_History_ID_45048(){
	noval_History_ID_45056 = true;
}

void init_History_ID_45048(){
	noval_History_ID_45056 = false;
	History_ID_45056 = 0;
	
}

void perform_step_History_ID_45048(){
	clear_outputs_History_ID_45048();
	noval_History_ID_45056 = noval_Output_ID_45054;
	if (!noval_Output_ID_45054) {
		History_ID_45056 = Output_ID_45054;
	}
	
	return;
	
}
