/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/Last_Street_Width_ID_29276.h"

GEN_TYPE_double StreetWidthOut_ID_29289;

GEN_TYPE_boolean noval_StreetWidthOut_ID_29289;

GEN_TYPE_double StreetWidthIn_ID_29301;

GEN_TYPE_boolean noval_StreetWidthIn_ID_29301;

void clear_inputs_Last_Street_Width_ID_29276(){
	noval_StreetWidthOut_ID_29289 = true;
}

void clear_outputs_Last_Street_Width_ID_29276(){
	noval_StreetWidthIn_ID_29301 = true;
}

void init_Last_Street_Width_ID_29276(){
	noval_StreetWidthIn_ID_29301 = true;
}

void perform_step_Last_Street_Width_ID_29276(){
	clear_outputs_Last_Street_Width_ID_29276();
	noval_StreetWidthIn_ID_29301 = noval_StreetWidthOut_ID_29289;
	if (!noval_StreetWidthOut_ID_29289) {
		StreetWidthIn_ID_29301 = StreetWidthOut_ID_29289;
	}
	
	return;
	
}
