/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/merge_TurnOffs_ID_16204.h"

GEN_TYPE_boolean ACC_TurnOff_ID_16220;

GEN_TYPE_boolean noval_ACC_TurnOff_ID_16220;

GEN_TYPE_boolean LK_TurnOff_ID_16229;

GEN_TYPE_boolean noval_LK_TurnOff_ID_16229;

GEN_TYPE_DA_TurnOff_Commands DA_TurnOff_ID_16211;

GEN_TYPE_boolean noval_DA_TurnOff_ID_16211;

void clear_inputs_merge_TurnOffs_ID_16204(){
	noval_ACC_TurnOff_ID_16220 = true;
	noval_LK_TurnOff_ID_16229 = true;
}

void clear_outputs_merge_TurnOffs_ID_16204(){
	noval_DA_TurnOff_ID_16211 = true;
}

void init_merge_TurnOffs_ID_16204(){
	noval_DA_TurnOff_ID_16211 = true;
}

void perform_step_merge_TurnOffs_ID_16204(){
	clear_outputs_merge_TurnOffs_ID_16204();
	noval_DA_TurnOff_ID_16211 = false;
	DA_TurnOff_ID_16211.acc = ACC_TurnOff_ID_16220;
	DA_TurnOff_ID_16211.laneKeep = LK_TurnOff_ID_16229;
	
	
	return;
	
}
