/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Platoon_Info_ID_46410.h"

GEN_TYPE_Message_Type receiveMessageType_ID_46592;

GEN_TYPE_boolean noval_receiveMessageType_ID_46592;

GEN_TYPE_PlatoonInformation platoonInfoIn_ID_46649;

GEN_TYPE_boolean noval_platoonInfoIn_ID_46649;

GEN_TYPE_PlatoonState platoonState_ID_48513;

GEN_TYPE_boolean noval_platoonState_ID_48513;

GEN_TYPE_PlatoonInformation platoonStoredOld_ID_49049;

GEN_TYPE_boolean noval_platoonStoredOld_ID_49049;

GEN_TYPE_listParticipants fuseListOld_ID_54539;

GEN_TYPE_boolean noval_fuseListOld_ID_54539;

GEN_TYPE_Message_Type sendMessageType_ID_54208;

GEN_TYPE_boolean noval_sendMessageType_ID_54208;

GEN_TYPE_PlatoonState platoonStateOut_ID_48635;

GEN_TYPE_boolean noval_platoonStateOut_ID_48635;

GEN_TYPE_PlatoonInformation platoonStoredNew_ID_49056;

GEN_TYPE_boolean noval_platoonStoredNew_ID_49056;

GEN_TYPE_listParticipants fuseListNew_ID_54528;

GEN_TYPE_boolean noval_fuseListNew_ID_54528;

void clear_inputs_Platoon_Info_ID_46410(){
	noval_receiveMessageType_ID_46592 = true;
	noval_platoonInfoIn_ID_46649 = true;
	noval_platoonState_ID_48513 = true;
	noval_platoonStoredOld_ID_49049 = true;
	noval_fuseListOld_ID_54539 = true;
}

void clear_outputs_Platoon_Info_ID_46410(){
	noval_sendMessageType_ID_54208 = true;
	noval_platoonStateOut_ID_48635 = true;
	noval_platoonStoredNew_ID_49056 = true;
	noval_fuseListNew_ID_54528 = true;
}

void init_Platoon_Info_ID_46410(){
	noval_sendMessageType_ID_54208 = true;
	noval_platoonStateOut_ID_48635 = true;
	noval_platoonStoredNew_ID_49056 = true;
	noval_fuseListNew_ID_54528 = true;
}

void perform_step_Platoon_Info_ID_46410(){
	clear_outputs_Platoon_Info_ID_46410();
	if (!(noval_platoonState_ID_48513 == true) && !(noval_receiveMessageType_ID_46592 == true)) {
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == leader()) {
			if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == no_message() || noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == platoon()) {
				noval_sendMessageType_ID_54208 = false;
				sendMessageType_ID_54208 = platoon();
				
				if (!(noval_platoonStoredOld_ID_49049 == true)) {
					noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
					if (!noval_platoonStoredOld_ID_49049) {
						platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
					}
					
					noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
					if (!noval_fuseListOld_ID_54539) {
						fuseListNew_ID_54528 = fuseListOld_ID_54539;
					}
					
				}
				else {
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = roverID();
					platoonStoredNew_ID_49056.amount = 1;
					platoonStoredNew_ID_49056.id = roverID();
					platoonStoredNew_ID_49056.oldLeaderID = roverID();
					platoonStoredNew_ID_49056.leaderID = roverID();
					platoonStoredNew_ID_49056.myPosition = 1;
					(platoonStoredNew_ID_49056.participants.content)[0] = roverID();
					(platoonStoredNew_ID_49056.participants.content)[1] = 0;
					(platoonStoredNew_ID_49056.participants.content)[2] = 0;
					(platoonStoredNew_ID_49056.participants.content)[3] = 0;
					(platoonStoredNew_ID_49056.participants.content)[4] = 0;
					
					
					
					noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
					if (!noval_fuseListOld_ID_54539) {
						fuseListNew_ID_54528 = fuseListOld_ID_54539;
					}
					
				}
			}
			if (!(noval_platoonInfoIn_ID_46649 == true)) {
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == handshake()) {
					if (platoonInfoIn_ID_46649.id == roverID()) {
						noval_sendMessageType_ID_54208 = false;
						sendMessageType_ID_54208 = newLeader();
						
						noval_platoonStoredNew_ID_49056 = false;
						platoonStoredNew_ID_49056.tailID = get_tailID(fuse_participants(fuseListOld_ID_54539, (platoonStoredOld_ID_49049.participants)));
						platoonStoredNew_ID_49056.amount = get_nof_participants(fuse_participants(fuseListOld_ID_54539, (platoonStoredOld_ID_49049.participants)));
						platoonStoredNew_ID_49056.id = roverID();
						platoonStoredNew_ID_49056.oldLeaderID = platoonInfoIn_ID_46649.leaderID;
						platoonStoredNew_ID_49056.leaderID = roverID();
						platoonStoredNew_ID_49056.myPosition = 1;
						platoonStoredNew_ID_49056.participants = fuse_participants(fuseListOld_ID_54539, (platoonStoredOld_ID_49049.participants));
						
						
						noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
						if (!noval_fuseListOld_ID_54539) {
							fuseListNew_ID_54528 = fuseListOld_ID_54539;
						}
						
					}
					else {
						noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
						if (!noval_platoonStoredOld_ID_49049) {
							platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
						}
						
						noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
						if (!noval_fuseListOld_ID_54539) {
							fuseListNew_ID_54528 = fuseListOld_ID_54539;
						}
						
					}
				}
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == fuse()) {
					if (platoonInfoIn_ID_46649.id == roverID()) {
						noval_sendMessageType_ID_54208 = false;
						sendMessageType_ID_54208 = handshake();
						
						noval_fuseListNew_ID_54528 = false;
						fuseListNew_ID_54528 = platoonInfoIn_ID_46649.participants;
						
						noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
						if (!noval_platoonStoredOld_ID_49049) {
							platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
						}
						
					}
				}
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == split()) {
					noval_sendMessageType_ID_54208 = false;
					sendMessageType_ID_54208 = platoon();
					
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = get_tailID(split_participantsLeader((platoonStoredOld_ID_49049.participants), get_position((platoonStoredOld_ID_49049.participants), (platoonInfoIn_ID_46649.leaderID))));
					platoonStoredNew_ID_49056.amount = get_nof_participants((platoonStoredOld_ID_49049.participants)) - ((5 - get_position((platoonStoredOld_ID_49049.participants), (platoonInfoIn_ID_46649.leaderID))) + 1);
					platoonStoredNew_ID_49056.id = roverID();
					platoonStoredNew_ID_49056.oldLeaderID = roverID();
					platoonStoredNew_ID_49056.leaderID = roverID();
					platoonStoredNew_ID_49056.myPosition = 1;
					platoonStoredNew_ID_49056.participants = split_participantsLeader((platoonStoredOld_ID_49049.participants), get_position((platoonStoredOld_ID_49049.participants), (platoonInfoIn_ID_46649.leaderID)));
					
					
					noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
					if (!noval_fuseListOld_ID_54539) {
						fuseListNew_ID_54528 = fuseListOld_ID_54539;
					}
					
				}
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == leave()) {
					noval_sendMessageType_ID_54208 = false;
					sendMessageType_ID_54208 = platoon();
					
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = get_tailID(leave_participants((platoonStoredOld_ID_49049.participants), (platoonInfoIn_ID_46649.leaderID)));
					platoonStoredNew_ID_49056.amount = platoonStoredOld_ID_49049.amount - 1;
					platoonStoredNew_ID_49056.id = roverID();
					platoonStoredNew_ID_49056.oldLeaderID = platoonStoredOld_ID_49049.oldLeaderID;
					platoonStoredNew_ID_49056.leaderID = roverID();
					platoonStoredNew_ID_49056.myPosition = 1;
					platoonStoredNew_ID_49056.participants = leave_participants((platoonStoredOld_ID_49049.participants), (platoonInfoIn_ID_46649.leaderID));
					
					
					noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
					if (!noval_fuseListOld_ID_54539) {
						fuseListNew_ID_54528 = fuseListOld_ID_54539;
					}
					
				}
				if (((!(noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == handshake()) && !(noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == fuse())) && !(noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == split())) && !(noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == leave())) {
					noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
					if (!noval_platoonStoredOld_ID_49049) {
						platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
					}
					
					noval_fuseListNew_ID_54528 = noval_fuseListOld_ID_54539;
					if (!noval_fuseListOld_ID_54539) {
						fuseListNew_ID_54528 = fuseListOld_ID_54539;
					}
					
				}
			}
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == fuseStarter()) {
			noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
			if (!noval_platoonStoredOld_ID_49049) {
				platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
			}
			
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == fusing()) {
			if (!(noval_platoonInfoIn_ID_46649 == true)) {
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == platoon()) {
					noval_sendMessageType_ID_54208 = false;
					sendMessageType_ID_54208 = fuse();
					
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = platoonStoredOld_ID_49049.tailID;
					platoonStoredNew_ID_49056.amount = platoonStoredOld_ID_49049.amount;
					platoonStoredNew_ID_49056.id = platoonInfoIn_ID_46649.id;
					platoonStoredNew_ID_49056.oldLeaderID = platoonStoredOld_ID_49049.oldLeaderID;
					platoonStoredNew_ID_49056.leaderID = roverID();
					platoonStoredNew_ID_49056.myPosition = platoonStoredOld_ID_49049.myPosition;
					platoonStoredNew_ID_49056.participants = platoonStoredOld_ID_49049.participants;
					
					
				}
				else {
					noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
					if (!noval_platoonStoredOld_ID_49049) {
						platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
					}
					
				}
			}
			else {
				noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
				if (!noval_platoonStoredOld_ID_49049) {
					platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
				}
				
			}
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == follower()) {
			if (!(noval_platoonInfoIn_ID_46649 == true)) {
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == leave()) {
					if (platoonInfoIn_ID_46649.leaderID == platoonStoredOld_ID_49049.id && ((platoonStoredOld_ID_49049.participants).content)[1] == roverID()) {
						noval_sendMessageType_ID_54208 = false;
						sendMessageType_ID_54208 = split();
						
					}
					noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
					if (!noval_platoonStoredOld_ID_49049) {
						platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
					}
					
				}
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == newLeader()) {
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = get_tailID((platoonStoredOld_ID_49049.participants));
					platoonStoredNew_ID_49056.amount = get_nof_participants((platoonStoredOld_ID_49049.participants));
					platoonStoredNew_ID_49056.id = platoonInfoIn_ID_46649.id;
					platoonStoredNew_ID_49056.oldLeaderID = platoonInfoIn_ID_46649.oldLeaderID;
					platoonStoredNew_ID_49056.leaderID = platoonInfoIn_ID_46649.leaderID;
					platoonStoredNew_ID_49056.myPosition = get_position((platoonStoredOld_ID_49049.participants), roverID());
					platoonStoredNew_ID_49056.participants = platoonStoredOld_ID_49049.participants;
					
					
				}
				if (noval_receiveMessageType_ID_46592 == false && receiveMessageType_ID_46592 == heartbeat()) {
					noval_platoonStoredNew_ID_49056 = false;
					platoonStoredNew_ID_49056.tailID = get_tailID((platoonInfoIn_ID_46649.participants));
					platoonStoredNew_ID_49056.amount = get_nof_participants((platoonInfoIn_ID_46649.participants));
					platoonStoredNew_ID_49056.id = platoonInfoIn_ID_46649.leaderID;
					platoonStoredNew_ID_49056.oldLeaderID = platoonStoredOld_ID_49049.leaderID;
					platoonStoredNew_ID_49056.leaderID = platoonInfoIn_ID_46649.leaderID;
					platoonStoredNew_ID_49056.myPosition = get_position((platoonInfoIn_ID_46649.participants), roverID());
					platoonStoredNew_ID_49056.participants = platoonInfoIn_ID_46649.participants;
					
					
				}
				else {
					noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
					if (!noval_platoonStoredOld_ID_49049) {
						platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
					}
					
				}
			}
			else {
				noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
				if (!noval_platoonStoredOld_ID_49049) {
					platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
				}
				
			}
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == handshaking()) {
			if (platoonInfoIn_ID_46649.id == platoonStoredOld_ID_49049.id) {
				noval_sendMessageType_ID_54208 = false;
				sendMessageType_ID_54208 = handshake();
				
			}
			noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
			if (!noval_platoonStoredOld_ID_49049) {
				platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
			}
			
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == leaving()) {
			noval_sendMessageType_ID_54208 = false;
			sendMessageType_ID_54208 = leave();
			
			noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
			if (!noval_platoonStoredOld_ID_49049) {
				platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
			}
			
		}
		if (noval_platoonState_ID_48513 == false && platoonState_ID_48513 == splitting()) {
			noval_sendMessageType_ID_54208 = false;
			sendMessageType_ID_54208 = split();
			
			noval_platoonStoredNew_ID_49056 = false;
			platoonStoredNew_ID_49056.tailID = roverID();
			platoonStoredNew_ID_49056.amount = (get_nof_participants((platoonStoredOld_ID_49049.participants)) - get_position((platoonStoredOld_ID_49049.participants), roverID())) + 1;
			platoonStoredNew_ID_49056.id = roverID();
			platoonStoredNew_ID_49056.oldLeaderID = platoonStoredOld_ID_49049.leaderID;
			platoonStoredNew_ID_49056.leaderID = roverID();
			platoonStoredNew_ID_49056.myPosition = 1;
			platoonStoredNew_ID_49056.participants = split_participants((platoonStoredOld_ID_49049.participants), (platoonStoredOld_ID_49049.myPosition));
			
			
		}
	}
	else {
		noval_platoonStoredNew_ID_49056 = noval_platoonStoredOld_ID_49049;
		if (!noval_platoonStoredOld_ID_49049) {
			platoonStoredNew_ID_49056 = platoonStoredOld_ID_49049;
		}
		
	}
	noval_platoonStateOut_ID_48635 = noval_platoonState_ID_48513;
	if (!noval_platoonState_ID_48513) {
		platoonStateOut_ID_48635 = platoonState_ID_48513;
	}
	
	return;
	
}
