/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Platooning_EB_Overwrite_ID_29192.h"

GEN_TYPE_boolean ForceEBOff_In_ID_29208;

GEN_TYPE_boolean noval_ForceEBOff_In_ID_29208;

GEN_TYPE_double MaxAccelerationEB_In_ID_29256;

GEN_TYPE_boolean noval_MaxAccelerationEB_In_ID_29256;

GEN_TYPE_boolean platooningOff_ID_31942;

GEN_TYPE_boolean noval_platooningOff_ID_31942;

GEN_TYPE_boolean Platooning_EB_Triggered_ID_31951;

GEN_TYPE_boolean noval_Platooning_EB_Triggered_ID_31951;

GEN_TYPE_double MaxAccelerationAD_ID_31960;

GEN_TYPE_boolean noval_MaxAccelerationAD_ID_31960;

GEN_TYPE_boolean ForceEBOff_ID_44969;

GEN_TYPE_boolean noval_ForceEBOff_ID_44969;

GEN_TYPE_double MaxAccelerationEB_ID_29311;

GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29311;

GEN_TYPE_boolean platooningOffOut_ID_29705;

GEN_TYPE_boolean noval_platooningOffOut_ID_29705;

void clear_inputs_Platooning_EB_Overwrite_ID_29192(){
	noval_ForceEBOff_In_ID_29208 = true;
	noval_MaxAccelerationEB_In_ID_29256 = true;
	noval_platooningOff_ID_31942 = true;
	noval_Platooning_EB_Triggered_ID_31951 = true;
	noval_MaxAccelerationAD_ID_31960 = true;
}

void clear_outputs_Platooning_EB_Overwrite_ID_29192(){
	noval_ForceEBOff_ID_44969 = true;
	noval_MaxAccelerationEB_ID_29311 = true;
	noval_platooningOffOut_ID_29705 = true;
}

void init_Platooning_EB_Overwrite_ID_29192(){
	noval_ForceEBOff_ID_44969 = true;
	noval_MaxAccelerationEB_ID_29311 = true;
	noval_platooningOffOut_ID_29705 = true;
}

void perform_step_Platooning_EB_Overwrite_ID_29192(){
	clear_outputs_Platooning_EB_Overwrite_ID_29192();
	noval_platooningOffOut_ID_29705 = noval_platooningOff_ID_31942;
	if (!noval_platooningOff_ID_31942) {
		platooningOffOut_ID_29705 = platooningOff_ID_31942;
	}
	
	if (!(noval_Platooning_EB_Triggered_ID_31951 == true) && (noval_Platooning_EB_Triggered_ID_31951 == false && Platooning_EB_Triggered_ID_31951 == true)) {
		noval_ForceEBOff_ID_44969 = false;
		ForceEBOff_ID_44969 = false;
		
		noval_MaxAccelerationEB_ID_29311 = noval_MaxAccelerationAD_ID_31960;
		if (!noval_MaxAccelerationAD_ID_31960) {
			MaxAccelerationEB_ID_29311 = MaxAccelerationAD_ID_31960;
		}
		
	}
	else {
		if (!(noval_platooningOff_ID_31942 == true) && platooningOff_ID_31942 || noval_Platooning_EB_Triggered_ID_31951 == true) {
			noval_ForceEBOff_ID_44969 = noval_ForceEBOff_In_ID_29208;
			if (!noval_ForceEBOff_In_ID_29208) {
				ForceEBOff_ID_44969 = ForceEBOff_In_ID_29208;
			}
			
			if (!(noval_ForceEBOff_In_ID_29208 == true) && (noval_ForceEBOff_In_ID_29208 == false && ForceEBOff_In_ID_29208 == true)) {
				noval_MaxAccelerationEB_ID_29311 = true;
			}
			else {
				noval_MaxAccelerationEB_ID_29311 = noval_MaxAccelerationEB_In_ID_29256;
				if (!noval_MaxAccelerationEB_In_ID_29256) {
					MaxAccelerationEB_ID_29311 = MaxAccelerationEB_In_ID_29256;
				}
				
			}
		}
		else {
			if (noval_Platooning_EB_Triggered_ID_31951 == false && Platooning_EB_Triggered_ID_31951 == false) {
				noval_ForceEBOff_ID_44969 = false;
				ForceEBOff_ID_44969 = true;
				
				noval_MaxAccelerationEB_ID_29311 = true;
			}
		}
	}
	return;
	
}
