/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/RGB_Adapter_ID_19000.h"

GEN_TYPE_RGBColor ColorBackLeft_ID_19148;

GEN_TYPE_boolean noval_ColorBackLeft_ID_19148;

GEN_TYPE_RGBColor ColorBackRight_ID_19155;

GEN_TYPE_boolean noval_ColorBackRight_ID_19155;

GEN_TYPE_int Red_Left_ID_19162;

GEN_TYPE_boolean noval_Red_Left_ID_19162;

GEN_TYPE_int Green_Left_ID_19171;

GEN_TYPE_boolean noval_Green_Left_ID_19171;

GEN_TYPE_int Blue_Left_ID_19180;

GEN_TYPE_boolean noval_Blue_Left_ID_19180;

GEN_TYPE_int Red_Right_ID_19189;

GEN_TYPE_boolean noval_Red_Right_ID_19189;

GEN_TYPE_int Green_Right_ID_19198;

GEN_TYPE_boolean noval_Green_Right_ID_19198;

GEN_TYPE_int Blue_Right_ID_19207;

GEN_TYPE_boolean noval_Blue_Right_ID_19207;

void clear_inputs_RGB_Adapter_ID_19000(){
	noval_ColorBackLeft_ID_19148 = true;
	noval_ColorBackRight_ID_19155 = true;
}

void clear_outputs_RGB_Adapter_ID_19000(){
	noval_Red_Left_ID_19162 = true;
	noval_Green_Left_ID_19171 = true;
	noval_Blue_Left_ID_19180 = true;
	noval_Red_Right_ID_19189 = true;
	noval_Green_Right_ID_19198 = true;
	noval_Blue_Right_ID_19207 = true;
}

void init_RGB_Adapter_ID_19000(){
	noval_Red_Left_ID_19162 = true;
	noval_Green_Left_ID_19171 = true;
	noval_Blue_Left_ID_19180 = true;
	noval_Red_Right_ID_19189 = true;
	noval_Green_Right_ID_19198 = true;
	noval_Blue_Right_ID_19207 = true;
}

void perform_step_RGB_Adapter_ID_19000(){
	clear_outputs_RGB_Adapter_ID_19000();
	return;
	
}
