/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/Rumble_Delay_ID_15596.h"

GEN_TYPE_boolean RumbleLKIn_ID_30784;

GEN_TYPE_boolean noval_RumbleLKIn_ID_30784;

GEN_TYPE_boolean RumbleLK_ID_15603;

GEN_TYPE_boolean noval_RumbleLK_ID_15603;

void clear_inputs_Rumble_Delay_ID_15596(){
	noval_RumbleLKIn_ID_30784 = true;
}

void clear_outputs_Rumble_Delay_ID_15596(){
	noval_RumbleLK_ID_15603 = true;
}

void init_Rumble_Delay_ID_15596(){
	noval_RumbleLK_ID_15603 = true;
}

void perform_step_Rumble_Delay_ID_15596(){
	clear_outputs_Rumble_Delay_ID_15596();
	if (!(noval_RumbleLKIn_ID_30784 == true) && RumbleLKIn_ID_30784) {
		noval_RumbleLK_ID_15603 = false;
		RumbleLK_ID_15603 = true;
		
	}
	else {
		noval_RumbleLK_ID_15603 = false;
		RumbleLK_ID_15603 = false;
		
	}
	return;
	
}
