/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Scale_ID_10083.h"

GEN_TYPE_double SteeringWheel_ID_12250;

GEN_TYPE_boolean noval_SteeringWheel_ID_12250;

GEN_TYPE_double Velocity_ID_12162;

GEN_TYPE_boolean noval_Velocity_ID_12162;

GEN_TYPE_double SteeringAngleMD_ID_12258;

GEN_TYPE_boolean noval_SteeringAngleMD_ID_12258;

void clear_inputs_Scale_ID_10083(){
	noval_SteeringWheel_ID_12250 = true;
	noval_Velocity_ID_12162 = true;
}

void clear_outputs_Scale_ID_10083(){
	noval_SteeringAngleMD_ID_12258 = true;
}

void init_Scale_ID_10083(){
	noval_SteeringAngleMD_ID_12258 = true;
}

void perform_step_Scale_ID_10083(){
	clear_outputs_Scale_ID_10083();
	if (!(noval_Velocity_ID_12162 == true)) {
		noval_SteeringAngleMD_ID_12258 = false;
		SteeringAngleMD_ID_12258 = scaleSteering(myabs(Velocity_ID_12162)) * SteeringWheel_ID_12250;
		
	}
	else {
		noval_SteeringAngleMD_ID_12258 = noval_SteeringWheel_ID_12250;
		if (!noval_SteeringWheel_ID_12250) {
			SteeringAngleMD_ID_12258 = SteeringWheel_ID_12250;
		}
		
	}
	return;
	
}
