/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Start_ID_44398.h"

GEN_TYPE_int ButtonStartIn_ID_44431;

GEN_TYPE_boolean noval_ButtonStartIn_ID_44431;

GEN_TYPE_KeyEvent ButtonStartOut_ID_44436;

GEN_TYPE_boolean noval_ButtonStartOut_ID_44436;

static GEN_TYPE_int current_state;

static GEN_TYPE_boolean fire_transition_Press_ID_44419();

static GEN_TYPE_boolean fire_transition_Release_ID_44422();

static GEN_TYPE_boolean fire_state_Released_ID_44405();

static GEN_TYPE_boolean fire_state_Pressed_ID_44411();

void clear_inputs_Start_ID_44398(){
	noval_ButtonStartIn_ID_44431 = true;
}

void clear_outputs_Start_ID_44398(){
	noval_ButtonStartOut_ID_44436 = true;
}

void init_Start_ID_44398(){
	noval_ButtonStartOut_ID_44436 = true;
	current_state = 44405;
}

void perform_step_Start_ID_44398(){
	clear_outputs_Start_ID_44398();
	if (current_state == 44411) {
		fire_state_Pressed_ID_44411();
	}
	else {
		if (current_state == 44405) {
			fire_state_Released_ID_44405();
		}
	}
}

static GEN_TYPE_boolean fire_transition_Press_ID_44419(){
	if (noval_ButtonStartIn_ID_44431 == false && ButtonStartIn_ID_44431 == 1) {
		noval_ButtonStartOut_ID_44436 = false;
		ButtonStartOut_ID_44436 = pressed();
		
		current_state = 44411;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_transition_Release_ID_44422(){
	if (noval_ButtonStartIn_ID_44431 == true || noval_ButtonStartIn_ID_44431 == false && ButtonStartIn_ID_44431 == 0) {
		noval_ButtonStartOut_ID_44436 = false;
		ButtonStartOut_ID_44436 = notPressed();
		
		current_state = 44405;
		return true;
	}
	else {
		return false;
	}
}

static GEN_TYPE_boolean fire_state_Released_ID_44405(){
	if (!fire_transition_Press_ID_44419()) {
		noval_ButtonStartOut_ID_44436 = false;
		ButtonStartOut_ID_44436 = notPressed();
		
	}
	return true;
}

static GEN_TYPE_boolean fire_state_Pressed_ID_44411(){
	if (!fire_transition_Release_ID_44422()) {
		noval_ButtonStartOut_ID_44436 = false;
		ButtonStartOut_ID_44436 = pressed();
		
	}
	return true;
}
