/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Stopping_distances_comparison_ID_15280.h"

GEN_TYPE_double Velocity_ID_15402;

GEN_TYPE_boolean noval_Velocity_ID_15402;

GEN_TYPE_double DistanceFront_ID_15397;

GEN_TYPE_boolean noval_DistanceFront_ID_15397;

GEN_TYPE_double VelocityFrontObstacle_ID_15392;

GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_15392;

GEN_TYPE_boolean CriticalSituation_ID_44761;

GEN_TYPE_boolean noval_CriticalSituation_ID_44761;

void clear_inputs_Stopping_distances_comparison_ID_15280(){
	noval_Velocity_ID_15402 = true;
	noval_DistanceFront_ID_15397 = true;
	noval_VelocityFrontObstacle_ID_15392 = true;
}

void clear_outputs_Stopping_distances_comparison_ID_15280(){
	noval_CriticalSituation_ID_44761 = true;
}

void init_Stopping_distances_comparison_ID_15280(){
	noval_CriticalSituation_ID_44761 = true;
}

void perform_step_Stopping_distances_comparison_ID_15280(){
	clear_outputs_Stopping_distances_comparison_ID_15280();
	if (noval_Velocity_ID_15402 == true || noval_DistanceFront_ID_15397 == true) {
		noval_CriticalSituation_ID_44761 = false;
		CriticalSituation_ID_44761 = true;
		
	}
	else {
		if (DistanceFront_ID_15397 <= (-0.5 * pow(Velocity_ID_15402, 2.0)) / MAX_BRAKE_VALUE() + pow(Velocity_ID_15402, EB_BUFFER_POW()) * EB_BUFFER_FACTOR_FOLLOW()) {
			noval_CriticalSituation_ID_44761 = false;
			CriticalSituation_ID_44761 = true;
			
			return;
		}
		noval_CriticalSituation_ID_44761 = false;
		CriticalSituation_ID_44761 = false;
		
	}
	return;
	
}
