/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Sum_ID_15989.h"

GEN_TYPE_double Coef_P_ID_16030;

GEN_TYPE_boolean noval_Coef_P_ID_16030;

GEN_TYPE_double Coef_I_ID_16039;

GEN_TYPE_boolean noval_Coef_I_ID_16039;

GEN_TYPE_double Coef_D_ID_16048;

GEN_TYPE_boolean noval_Coef_D_ID_16048;

GEN_TYPE_double Steering_FeedForward_ID_31436;

GEN_TYPE_boolean noval_Steering_FeedForward_ID_31436;

GEN_TYPE_double SteeringAngleRegulated_ID_16316;

GEN_TYPE_boolean noval_SteeringAngleRegulated_ID_16316;

void clear_inputs_Sum_ID_15989(){
	noval_Coef_P_ID_16030 = true;
	noval_Coef_I_ID_16039 = true;
	noval_Coef_D_ID_16048 = true;
	noval_Steering_FeedForward_ID_31436 = true;
}

void clear_outputs_Sum_ID_15989(){
	noval_SteeringAngleRegulated_ID_16316 = true;
}

void init_Sum_ID_15989(){
	noval_SteeringAngleRegulated_ID_16316 = true;
}

void perform_step_Sum_ID_15989(){
	clear_outputs_Sum_ID_15989();
	if ((noval_Coef_P_ID_16030 == true || noval_Coef_I_ID_16039 == true) || noval_Coef_D_ID_16048 == true) {
		noval_SteeringAngleRegulated_ID_16316 = false;
		SteeringAngleRegulated_ID_16316 = 0.0;
		
		return;
	}
	noval_SteeringAngleRegulated_ID_16316 = false;
	SteeringAngleRegulated_ID_16316 = ((Coef_P_ID_16030 + Coef_I_ID_16039) + Coef_D_ID_16048) + Steering_FeedForward_ID_31436;
	
	return;
	
}
