/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/Tick_Counter_ID_46205.h"

GEN_TYPE_int NewCount_ID_54368;

GEN_TYPE_boolean noval_NewCount_ID_54368;

GEN_TYPE_int OldCount_ID_54373;

GEN_TYPE_boolean noval_OldCount_ID_54373;

void clear_inputs_Tick_Counter_ID_46205(){
	noval_NewCount_ID_54368 = true;
}

void clear_outputs_Tick_Counter_ID_46205(){
	noval_OldCount_ID_54373 = true;
}

void init_Tick_Counter_ID_46205(){
	noval_OldCount_ID_54373 = true;
}

void perform_step_Tick_Counter_ID_46205(){
	clear_outputs_Tick_Counter_ID_46205();
	if (!(noval_NewCount_ID_54368 == true)) {
		noval_OldCount_ID_54373 = false;
		OldCount_ID_54373 = NewCount_ID_54368 + 1;
		
	}
	else {
		noval_OldCount_ID_54373 = false;
		OldCount_ID_54373 = 0;
		
	}
	return;
	
}
