/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Transit_ID_8679.h"

GEN_TYPE_double Velocity_ID_8688;

GEN_TYPE_boolean noval_Velocity_ID_8688;

GEN_TYPE_double DistanceFrontIn_ID_8695;

GEN_TYPE_boolean noval_DistanceFrontIn_ID_8695;

GEN_TYPE_LDCameraData LDCameraDataIn_ID_16886;

GEN_TYPE_boolean noval_LDCameraDataIn_ID_16886;

GEN_TYPE_double DistanceFrontOut_ID_8718;

GEN_TYPE_boolean noval_DistanceFrontOut_ID_8718;

GEN_TYPE_double VelocityOut_ID_8778;

GEN_TYPE_boolean noval_VelocityOut_ID_8778;

GEN_TYPE_LDCameraData LDCameraData_ID_16893;

GEN_TYPE_boolean noval_LDCameraData_ID_16893;

void clear_inputs_Transit_ID_8679(){
	noval_Velocity_ID_8688 = true;
	noval_DistanceFrontIn_ID_8695 = true;
	noval_LDCameraDataIn_ID_16886 = true;
}

void clear_outputs_Transit_ID_8679(){
	noval_DistanceFrontOut_ID_8718 = true;
	noval_VelocityOut_ID_8778 = true;
	noval_LDCameraData_ID_16893 = true;
}

void init_Transit_ID_8679(){
	noval_DistanceFrontOut_ID_8718 = true;
	noval_VelocityOut_ID_8778 = true;
	noval_LDCameraData_ID_16893 = true;
}

void perform_step_Transit_ID_8679(){
	clear_outputs_Transit_ID_8679();
	noval_VelocityOut_ID_8778 = noval_Velocity_ID_8688;
	if (!noval_Velocity_ID_8688) {
		VelocityOut_ID_8778 = Velocity_ID_8688;
	}
	
	noval_DistanceFrontOut_ID_8718 = noval_DistanceFrontIn_ID_8695;
	if (!noval_DistanceFrontIn_ID_8695) {
		DistanceFrontOut_ID_8718 = DistanceFrontIn_ID_8695;
	}
	
	noval_LDCameraData_ID_16893 = noval_LDCameraDataIn_ID_16886;
	if (!noval_LDCameraDataIn_ID_16886) {
		LDCameraData_ID_16893 = LDCameraDataIn_ID_16886;
	}
	
	return;
	
}
