/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:02 CEST 2019 */
#include "inc-gen/Transit_for_Testing_ID_45252.h"

GEN_TYPE_double LD_Distance_Left_ID_45262;

GEN_TYPE_boolean noval_LD_Distance_Left_ID_45262;

GEN_TYPE_double LD_Distance_Right_ID_45269;

GEN_TYPE_boolean noval_LD_Distance_Right_ID_45269;

GEN_TYPE_double LD_Left_ID_45276;

GEN_TYPE_boolean noval_LD_Left_ID_45276;

GEN_TYPE_double LD_Right_ID_45285;

GEN_TYPE_boolean noval_LD_Right_ID_45285;

void clear_inputs_Transit_for_Testing_ID_45252(){
	noval_LD_Distance_Left_ID_45262 = true;
	noval_LD_Distance_Right_ID_45269 = true;
}

void clear_outputs_Transit_for_Testing_ID_45252(){
	noval_LD_Left_ID_45276 = true;
	noval_LD_Right_ID_45285 = true;
}

void init_Transit_for_Testing_ID_45252(){
	noval_LD_Left_ID_45276 = true;
	noval_LD_Right_ID_45285 = true;
}

void perform_step_Transit_for_Testing_ID_45252(){
	clear_outputs_Transit_for_Testing_ID_45252();
	noval_LD_Left_ID_45276 = noval_LD_Distance_Left_ID_45262;
	if (!noval_LD_Distance_Left_ID_45262) {
		LD_Left_ID_45276 = LD_Distance_Left_ID_45262;
	}
	
	noval_LD_Right_ID_45285 = noval_LD_Distance_Right_ID_45269;
	if (!noval_LD_Distance_Right_ID_45269) {
		LD_Right_ID_45285 = LD_Distance_Right_ID_45269;
	}
	
	return;
	
}
