/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/TurnOffPlatooning_ID_46536.h"

GEN_TYPE_int status_ID_47695;

GEN_TYPE_boolean noval_status_ID_47695;

GEN_TYPE_AD_TurnOffCommands ADTurnOff_ID_46541;

GEN_TYPE_boolean noval_ADTurnOff_ID_46541;

void clear_inputs_TurnOffPlatooning_ID_46536(){
	noval_status_ID_47695 = true;
}

void clear_outputs_TurnOffPlatooning_ID_46536(){
	noval_ADTurnOff_ID_46541 = true;
}

void init_TurnOffPlatooning_ID_46536(){
	noval_ADTurnOff_ID_46541 = true;
}

void perform_step_TurnOffPlatooning_ID_46536(){
	clear_outputs_TurnOffPlatooning_ID_46536();
	if (!(noval_status_ID_47695 == true) && (noval_status_ID_47695 == false && status_ID_47695 == 2)) {
		noval_ADTurnOff_ID_46541 = false;
		ADTurnOff_ID_46541.Platooning = true;
		
		
	}
	return;
	
}
