/* generated by AutoFOCUS 3 (2.14.0) on Tue Jul 09 17:20:03 CEST 2019 */
#include "inc-gen/Velocity_Return_ID_31819.h"

GEN_TYPE_double VelocityValue_ID_31828;

GEN_TYPE_boolean noval_VelocityValue_ID_31828;

GEN_TYPE_double VelocityReturn_ID_31835;

GEN_TYPE_boolean noval_VelocityReturn_ID_31835;

void clear_inputs_Velocity_Return_ID_31819(){
	noval_VelocityValue_ID_31828 = true;
}

void clear_outputs_Velocity_Return_ID_31819(){
	noval_VelocityReturn_ID_31835 = true;
}

void init_Velocity_Return_ID_31819(){
	noval_VelocityReturn_ID_31835 = true;
}

void perform_step_Velocity_Return_ID_31819(){
	clear_outputs_Velocity_Return_ID_31819();
	noval_VelocityReturn_ID_31835 = noval_VelocityValue_ID_31828;
	if (!noval_VelocityValue_ID_31828) {
		VelocityReturn_ID_31835 = VelocityValue_ID_31828;
	}
	
	return;
	
}
