/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_ACC_P_Part_ID_44568_h
#define __HEADER_ACC_P_Part_ID_44568_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Error_adjusted_ID_44643;

extern GEN_TYPE_boolean noval_Error_adjusted_ID_44643;

extern GEN_TYPE_double Velocity_ID_44616;

extern GEN_TYPE_boolean noval_Velocity_ID_44616;

extern GEN_TYPE_double TargetVelocity_ID_44598;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_44598;

extern void clear_inputs_ACC_P_Part_ID_44568();

extern void clear_outputs_ACC_P_Part_ID_44568();

extern void init_ACC_P_Part_ID_44568();

extern void perform_step_ACC_P_Part_ID_44568();

#endif // __HEADER_ACC_P_Part_ID_44568_h
