/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Boundaries_active_ID_16338_h
#define __HEADER_Boundaries_active_ID_16338_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean BoundariesActive_In_ID_16347;

extern GEN_TYPE_boolean noval_BoundariesActive_In_ID_16347;

extern GEN_TYPE_boolean BoundariesActive_ID_16352;

extern GEN_TYPE_boolean noval_BoundariesActive_ID_16352;

extern void clear_inputs_Boundaries_active_ID_16338();

extern void clear_outputs_Boundaries_active_ID_16338();

extern void init_Boundaries_active_ID_16338();

extern void perform_step_Boundaries_active_ID_16338();

#endif // __HEADER_Boundaries_active_ID_16338_h
