/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Boundaries_ID_7833_h
#define __HEADER_Boundaries_ID_7833_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Velocity_ID_7870;

extern GEN_TYPE_boolean noval_Velocity_ID_7870;

extern GEN_TYPE_double MaxVelocityDiff_ID_7879;

extern GEN_TYPE_boolean noval_MaxVelocityDiff_ID_7879;

extern GEN_TYPE_double MaxValue_ID_7840;

extern GEN_TYPE_boolean noval_MaxValue_ID_7840;

extern GEN_TYPE_double MinValue_ID_7847;

extern GEN_TYPE_boolean noval_MinValue_ID_7847;

extern GEN_TYPE_double MaxErrorSum_ID_7854;

extern GEN_TYPE_boolean noval_MaxErrorSum_ID_7854;

extern void clear_inputs_Boundaries_ID_7833();

extern void clear_outputs_Boundaries_ID_7833();

extern void init_Boundaries_ID_7833();

extern void perform_step_Boundaries_ID_7833();

#endif // __HEADER_Boundaries_ID_7833_h
