/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Computation_ID_27_h
#define __HEADER_Computation_ID_27_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double History_ID_57;

extern GEN_TYPE_boolean noval_History_ID_57;

extern GEN_TYPE_double Input_ID_45022;

extern GEN_TYPE_boolean noval_Input_ID_45022;

extern GEN_TYPE_double Weight_Current_ID_84;

extern GEN_TYPE_boolean noval_Weight_Current_ID_84;

extern GEN_TYPE_double Output_ID_45391;

extern GEN_TYPE_boolean noval_Output_ID_45391;

extern void clear_inputs_Computation_ID_27();

extern void clear_outputs_Computation_ID_27();

extern void init_Computation_ID_27();

extern void perform_step_Computation_ID_27();

#endif // __HEADER_Computation_ID_27_h
