/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Delay_ID_16983_h
#define __HEADER_Delay_ID_16983_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean RumbleEB_In_ID_17264;

extern GEN_TYPE_boolean noval_RumbleEB_In_ID_17264;

extern GEN_TYPE_DriveModeSettings DriveMode_ID_31975;

extern GEN_TYPE_boolean noval_DriveMode_ID_31975;

extern GEN_TYPE_boolean FirstCritTick_ID_32331;

extern GEN_TYPE_boolean noval_FirstCritTick_ID_32331;

extern GEN_TYPE_boolean RumbleEB_ID_16997;

extern GEN_TYPE_boolean noval_RumbleEB_ID_16997;

extern GEN_TYPE_DriveModeSettings DriveMode_out_ID_31966;

extern GEN_TYPE_boolean noval_DriveMode_out_ID_31966;

extern GEN_TYPE_boolean FirstCritTick_Old_ID_32320;

extern GEN_TYPE_boolean noval_FirstCritTick_Old_ID_32320;

extern void clear_inputs_Delay_ID_16983();

extern void clear_outputs_Delay_ID_16983();

extern void init_Delay_ID_16983();

extern void perform_step_Delay_ID_16983();

#endif // __HEADER_Delay_ID_16983_h
