/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_DPadDown_ID_19888_h
#define __HEADER_DPadDown_ID_19888_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int DPadDownIn_ID_32527;

extern GEN_TYPE_boolean noval_DPadDownIn_ID_32527;

extern GEN_TYPE_KeyEvent DPadDownOut_ID_32520;

extern GEN_TYPE_boolean noval_DPadDownOut_ID_32520;

extern void clear_inputs_DPadDown_ID_19888();

extern void clear_outputs_DPadDown_ID_19888();

extern void init_DPadDown_ID_19888();

extern void perform_step_DPadDown_ID_19888();

#endif // __HEADER_DPadDown_ID_19888_h
