/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_DPadUp_ID_18678_h
#define __HEADER_DPadUp_ID_18678_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int DPadUpIn_ID_32542;

extern GEN_TYPE_boolean noval_DPadUpIn_ID_32542;

extern GEN_TYPE_KeyEvent DPadUpOut_ID_32505;

extern GEN_TYPE_boolean noval_DPadUpOut_ID_32505;

extern void clear_inputs_DPadUp_ID_18678();

extern void clear_outputs_DPadUp_ID_18678();

extern void init_DPadUp_ID_18678();

extern void perform_step_DPadUp_ID_18678();

#endif // __HEADER_DPadUp_ID_18678_h
