/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Driver_Assistance_Coordinator_ID_8040_h
#define __HEADER_Driver_Assistance_Coordinator_ID_8040_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAcceleration_ID_8116;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_8116;

extern GEN_TYPE_double TargetVelocity_ID_8125;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_8125;

extern GEN_TYPE_double SteeringAngle_ID_30789;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_30789;

extern GEN_TYPE_double SteeringAngleDA_ID_8084;

extern GEN_TYPE_boolean noval_SteeringAngleDA_ID_8084;

extern GEN_TYPE_double TargetVelocityDA_ID_8091;

extern GEN_TYPE_boolean noval_TargetVelocityDA_ID_8091;

extern GEN_TYPE_double MaxAccelerationDA_ID_8098;

extern GEN_TYPE_boolean noval_MaxAccelerationDA_ID_8098;

extern void clear_inputs_Driver_Assistance_Coordinator_ID_8040();

extern void clear_outputs_Driver_Assistance_Coordinator_ID_8040();

extern void init_Driver_Assistance_Coordinator_ID_8040();

extern void perform_step_Driver_Assistance_Coordinator_ID_8040();

#endif // __HEADER_Driver_Assistance_Coordinator_ID_8040_h
