/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_EBOff_ID_17684_h
#define __HEADER_EBOff_ID_17684_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_KeyEvent ButtonEBOff_ID_17693;

extern GEN_TYPE_boolean noval_ButtonEBOff_ID_17693;

extern GEN_TYPE_boolean ForceEBOff_ID_17757;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_17757;

extern void clear_inputs_EBOff_ID_17684();

extern void clear_outputs_EBOff_ID_17684();

extern void init_EBOff_ID_17684();

extern void perform_step_EBOff_ID_17684();

#endif // __HEADER_EBOff_ID_17684_h
