/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_FeedForward_ID_31418_h
#define __HEADER_FeedForward_ID_31418_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_LDCameraData LDCameraData_ID_31427;

extern GEN_TYPE_boolean noval_LDCameraData_ID_31427;

extern GEN_TYPE_double Steering_FeedForward_ID_31434;

extern GEN_TYPE_boolean noval_Steering_FeedForward_ID_31434;

extern void clear_inputs_FeedForward_ID_31418();

extern void clear_outputs_FeedForward_ID_31418();

extern void init_FeedForward_ID_31418();

extern void perform_step_FeedForward_ID_31418();

#endif // __HEADER_FeedForward_ID_31418_h
