/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_L1_ID_13496_h
#define __HEADER_L1_ID_13496_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonL1In_ID_32547;

extern GEN_TYPE_boolean noval_ButtonL1In_ID_32547;

extern GEN_TYPE_KeyEvent ButtonL1Out_ID_32500;

extern GEN_TYPE_boolean noval_ButtonL1Out_ID_32500;

extern void clear_inputs_L1_ID_13496();

extern void clear_outputs_L1_ID_13496();

extern void init_L1_ID_13496();

extern void perform_step_L1_ID_13496();

#endif // __HEADER_L1_ID_13496_h
