/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_L2_ID_13608_h
#define __HEADER_L2_ID_13608_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int In_ID_13633;

extern GEN_TYPE_boolean noval_In_ID_13633;

extern GEN_TYPE_int Out_ID_13631;

extern GEN_TYPE_boolean noval_Out_ID_13631;

extern void clear_inputs_L2_ID_13608();

extern void clear_outputs_L2_ID_13608();

extern void init_L2_ID_13608();

extern void perform_step_L2_ID_13608();

#endif // __HEADER_L2_ID_13608_h
