/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Lane_Warning_Rumble_ID_17219_h
#define __HEADER_Lane_Warning_Rumble_ID_17219_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean RumbleLW_ID_17250;

extern GEN_TYPE_boolean noval_RumbleLW_ID_17250;

extern GEN_TYPE_int RumbleLW_Out_ID_29215;

extern GEN_TYPE_boolean noval_RumbleLW_Out_ID_29215;

extern void clear_inputs_Lane_Warning_Rumble_ID_17219();

extern void clear_outputs_Lane_Warning_Rumble_ID_17219();

extern void init_Lane_Warning_Rumble_ID_17219();

extern void perform_step_Lane_Warning_Rumble_ID_17219();

#endif // __HEADER_Lane_Warning_Rumble_ID_17219_h
