/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Last_Steering_ID_44992_h
#define __HEADER_Last_Steering_ID_44992_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double SteeringAngle_ID_45001;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_45001;

extern GEN_TYPE_double LastSteeringAngle_ID_45008;

extern GEN_TYPE_boolean noval_LastSteeringAngle_ID_45008;

extern void clear_inputs_Last_Steering_ID_44992();

extern void clear_outputs_Last_Steering_ID_44992();

extern void init_Last_Steering_ID_44992();

extern void perform_step_Last_Steering_ID_44992();

#endif // __HEADER_Last_Steering_ID_44992_h
