/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_LK_Activator_Check_ID_15635_h
#define __HEADER_LK_Activator_Check_ID_15635_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_LDCameraData LDCameraData_ID_15651;

extern GEN_TYPE_boolean noval_LDCameraData_ID_15651;

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_45634;

extern GEN_TYPE_boolean noval_DA_States_ID_45634;

extern GEN_TYPE_boolean RumbleLKIn_ID_15656;

extern GEN_TYPE_boolean noval_RumbleLKIn_ID_15656;

extern GEN_TYPE_int SteeringCommand_ID_15967;

extern GEN_TYPE_boolean noval_SteeringCommand_ID_15967;

extern void clear_inputs_LK_Activator_Check_ID_15635();

extern void clear_outputs_LK_Activator_Check_ID_15635();

extern void init_LK_Activator_Check_ID_15635();

extern void perform_step_LK_Activator_Check_ID_15635();

#endif // __HEADER_LK_Activator_Check_ID_15635_h
