/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Manual_ID_6500_h
#define __HEADER_Manual_ID_6500_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int GearShift_ID_9872;

extern GEN_TYPE_boolean noval_GearShift_ID_9872;

extern GEN_TYPE_double GasPedal_ID_9873;

extern GEN_TYPE_boolean noval_GasPedal_ID_9873;

extern GEN_TYPE_double Throttle_ID_9875;

extern GEN_TYPE_boolean noval_Throttle_ID_9875;

extern GEN_TYPE_int Gear_ID_12649;

extern GEN_TYPE_boolean noval_Gear_ID_12649;

extern void clear_inputs_Manual_ID_6500();

extern void clear_outputs_Manual_ID_6500();

extern void init_Manual_ID_6500();

extern void perform_step_Manual_ID_6500();

#endif // __HEADER_Manual_ID_6500_h
