/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Max_Acceleration_ID_6878_h
#define __HEADER_Max_Acceleration_ID_6878_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double MaxAccelerationEB_ID_29308;

extern GEN_TYPE_boolean noval_MaxAccelerationEB_ID_29308;

extern GEN_TYPE_double MaxAccelerationMD_ID_16254;

extern GEN_TYPE_boolean noval_MaxAccelerationMD_ID_16254;

extern GEN_TYPE_double MaxAccelerationDA_ID_16200;

extern GEN_TYPE_boolean noval_MaxAccelerationDA_ID_16200;

extern GEN_TYPE_boolean ACC_On_Correct_ID_16269;

extern GEN_TYPE_boolean noval_ACC_On_Correct_ID_16269;

extern GEN_TYPE_boolean ForceEBOff_ID_29249;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_29249;

extern GEN_TYPE_double MaxAccelerationAD_ID_20259;

extern GEN_TYPE_boolean noval_MaxAccelerationAD_ID_20259;

extern GEN_TYPE_boolean Platooning_IsLeader_ID_29700;

extern GEN_TYPE_boolean noval_Platooning_IsLeader_ID_29700;

extern GEN_TYPE_boolean platooningOff_ID_29707;

extern GEN_TYPE_boolean noval_platooningOff_ID_29707;

extern GEN_TYPE_double MaxAcceleration_ID_18004;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_18004;

extern void clear_inputs_Max_Acceleration_ID_6878();

extern void clear_outputs_Max_Acceleration_ID_6878();

extern void init_Max_Acceleration_ID_6878();

extern void perform_step_Max_Acceleration_ID_6878();

#endif // __HEADER_Max_Acceleration_ID_6878_h
