/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_NoVal_Checker_ID_47760_h
#define __HEADER_NoVal_Checker_ID_47760_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double TargetVelocity_ID_47768;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_47768;

extern GEN_TYPE_double MaxAcceleration_ID_47775;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_47775;

extern GEN_TYPE_double SteeringAngle_ID_47789;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_47789;

extern GEN_TYPE_double TargetVelocityOut_ID_47831;

extern GEN_TYPE_boolean noval_TargetVelocityOut_ID_47831;

extern GEN_TYPE_double MaxAccelerationOut_ID_47840;

extern GEN_TYPE_boolean noval_MaxAccelerationOut_ID_47840;

extern GEN_TYPE_double SteeringAngleOut_ID_47849;

extern GEN_TYPE_boolean noval_SteeringAngleOut_ID_47849;

extern void clear_inputs_NoVal_Checker_ID_47760();

extern void clear_outputs_NoVal_Checker_ID_47760();

extern void init_NoVal_Checker_ID_47760();

extern void perform_step_NoVal_Checker_ID_47760();

#endif // __HEADER_NoVal_Checker_ID_47760_h
