/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_OLD_Stopping_distances_comparison_ID_45136_h
#define __HEADER_OLD_Stopping_distances_comparison_ID_45136_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Velocity_ID_45165;

extern GEN_TYPE_boolean noval_Velocity_ID_45165;

extern GEN_TYPE_double DistanceFront_ID_45167;

extern GEN_TYPE_boolean noval_DistanceFront_ID_45167;

extern GEN_TYPE_double VelocityFrontObstacle_ID_45169;

extern GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_45169;

extern GEN_TYPE_boolean CriticalSituation_ID_45163;

extern GEN_TYPE_boolean noval_CriticalSituation_ID_45163;

extern void clear_inputs_OLD_Stopping_distances_comparison_ID_45136();

extern void clear_outputs_OLD_Stopping_distances_comparison_ID_45136();

extern void init_OLD_Stopping_distances_comparison_ID_45136();

extern void perform_step_OLD_Stopping_distances_comparison_ID_45136();

#endif // __HEADER_OLD_Stopping_distances_comparison_ID_45136_h
