/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_P_term_ID_16009_h
#define __HEADER_P_term_ID_16009_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Error_ID_16080;

extern GEN_TYPE_boolean noval_Error_ID_16080;

extern GEN_TYPE_double Coef_P_ID_16028;

extern GEN_TYPE_boolean noval_Coef_P_ID_16028;

extern void clear_inputs_P_term_ID_16009();

extern void clear_outputs_P_term_ID_16009();

extern void init_P_term_ID_16009();

extern void perform_step_P_term_ID_16009();

#endif // __HEADER_P_term_ID_16009_h
