/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_R1_ID_13442_h
#define __HEADER_R1_ID_13442_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_int ButtonR1In_ID_32557;

extern GEN_TYPE_boolean noval_ButtonR1In_ID_32557;

extern GEN_TYPE_KeyEvent ButtonR1Out_ID_32490;

extern GEN_TYPE_boolean noval_ButtonR1Out_ID_32490;

extern void clear_inputs_R1_ID_13442();

extern void clear_outputs_R1_ID_13442();

extern void init_R1_ID_13442();

extern void perform_step_R1_ID_13442();

#endif // __HEADER_R1_ID_13442_h
