/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Steering_Angle_ID_6888_h
#define __HEADER_Steering_Angle_ID_6888_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_boolean LK_On_Correct_ID_16195;

extern GEN_TYPE_boolean noval_LK_On_Correct_ID_16195;

extern GEN_TYPE_double SteeringAngleMD_ID_6984;

extern GEN_TYPE_boolean noval_SteeringAngleMD_ID_6984;

extern GEN_TYPE_double SteeringAngleDA_ID_16242;

extern GEN_TYPE_boolean noval_SteeringAngleDA_ID_16242;

extern GEN_TYPE_double SteeringAngle_ID_6909;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_6909;

extern void clear_inputs_Steering_Angle_ID_6888();

extern void clear_outputs_Steering_Angle_ID_6888();

extern void init_Steering_Angle_ID_6888();

extern void perform_step_Steering_Angle_ID_6888();

#endif // __HEADER_Steering_Angle_ID_6888_h
