/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Steering_Angle_Transformation_ID_5661_h
#define __HEADER_Steering_Angle_Transformation_ID_5661_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double SteeringAngle_ID_5684;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_5684;

extern GEN_TYPE_double SteeringValue_ID_20005;

extern GEN_TYPE_boolean noval_SteeringValue_ID_20005;

extern void clear_inputs_Steering_Angle_Transformation_ID_5661();

extern void clear_outputs_Steering_Angle_Transformation_ID_5661();

extern void init_Steering_Angle_Transformation_ID_5661();

extern void perform_step_Steering_Angle_Transformation_ID_5661();

#endif // __HEADER_Steering_Angle_Transformation_ID_5661_h
