/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_Stopping_distances_comparison_ID_15280_h
#define __HEADER_Stopping_distances_comparison_ID_15280_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double Velocity_ID_15402;

extern GEN_TYPE_boolean noval_Velocity_ID_15402;

extern GEN_TYPE_double DistanceFront_ID_15397;

extern GEN_TYPE_boolean noval_DistanceFront_ID_15397;

extern GEN_TYPE_double VelocityFrontObstacle_ID_15392;

extern GEN_TYPE_boolean noval_VelocityFrontObstacle_ID_15392;

extern GEN_TYPE_boolean CriticalSituation_ID_44761;

extern GEN_TYPE_boolean noval_CriticalSituation_ID_44761;

extern void clear_inputs_Stopping_distances_comparison_ID_15280();

extern void clear_outputs_Stopping_distances_comparison_ID_15280();

extern void init_Stopping_distances_comparison_ID_15280();

extern void perform_step_Stopping_distances_comparison_ID_15280();

#endif // __HEADER_Stopping_distances_comparison_ID_15280_h
