/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_System_ID_4789_h
#define __HEADER_System_ID_4789_h
#include "inc-gen/data_dictionary.h"

#include "inc-gen/Start_ID_44398.h"

#include "inc-gen/Return_ID_31841.h"

#include "inc-gen/Distance_Transformation_ID_16635.h"

#include "inc-gen/Ranges_ID_32178.h"

#include "inc-gen/Min_ID_16760.h"

#include "inc-gen/Check_ID_24609.h"

#include "inc-gen/DPadDown_ID_19888.h"

#include "inc-gen/DPadRight_ID_18732.h"

#include "inc-gen/DPadLeft_ID_18705.h"

#include "inc-gen/DPadUp_ID_18678.h"

#include "inc-gen/L1_ID_13496.h"

#include "inc-gen/Select_ID_13469.h"

#include "inc-gen/R1_ID_13442.h"

#include "inc-gen/Home_ID_13373.h"

#include "inc-gen/Transform_Input_ID_12045.h"

#include "inc-gen/Mapping_ID_6657.h"

#include "inc-gen/BackLightController_ID_19416.h"

#include "inc-gen/RGB_Adapter_ID_19000.h"

#include "inc-gen/V2V_Receive_ID_22660.h"

#include "inc-gen/Message_Handler_ID_45890.h"

#include "inc-gen/Fuse_Split_ID_27169.h"

#include "inc-gen/Platooning_TurnOnOff_ID_20320.h"

#include "inc-gen/SumUpControl_ID_24113.h"

#include "inc-gen/Platoon_States_ID_46545.h"

#include "inc-gen/Platoon_Info_ID_46410.h"

#include "inc-gen/Message_Sender_ID_46097.h"

#include "inc-gen/V2V_Send_ID_22682.h"

#include "inc-gen/Lane_Keeping_ID_8424.h"

#include "inc-gen/Adaptive_Cruise_Control_ID_8419.h"

#include "inc-gen/Aggregate_ID_8429.h"

#include "inc-gen/CheckMode_ID_53842.h"

#include "inc-gen/VelocityDifference_ID_6918.h"

#include "inc-gen/Velocity_of_Obstacle_in_front_ID_6981.h"

#include "inc-gen/REMOVED_ID_44654.h"

#include "inc-gen/Transit_ID_8679.h"

#include "inc-gen/TargetDistance_ID_16386.h"

#include "inc-gen/ACC_Error_ID_44576.h"

#include "inc-gen/ACC_Error_Adjustment_ID_44627.h"

#include "inc-gen/ACC_P_Part_ID_44568.h"

#include "inc-gen/TargetVelocity_ID_10210.h"

#include "inc-gen/MaxAccel_Decel_ID_44530.h"

#include "inc-gen/FeedForward_ID_31418.h"

#include "inc-gen/Error_ID_16055.h"

#include "inc-gen/D_term_ID_16019.h"

#include "inc-gen/I_term_ID_16014.h"

#include "inc-gen/P_term_ID_16009.h"

#include "inc-gen/Sum_ID_15989.h"

#include "inc-gen/Boundaries_ID_16309.h"

#include "inc-gen/LK_Activator_Check_ID_15635.h"

#include "inc-gen/LK_Coordinator_ID_15951.h"

#include "inc-gen/Driver_Assistance_Coordinator_ID_8040.h"

#include "inc-gen/GearShift_ID_15020.h"

#include "inc-gen/Stopping_distances_comparison_ID_15280.h"

#include "inc-gen/EB_Coordinator_ID_15303.h"

#include "inc-gen/EB_Memory_ID_15316.h"

#include "inc-gen/Platooning_EB_Overwrite_ID_29192.h"

#include "inc-gen/L1_ID_13635.h"

#include "inc-gen/L2_ID_13608.h"

#include "inc-gen/R1_ID_13581.h"

#include "inc-gen/R2_ID_13554.h"

#include "inc-gen/DriveMode_Merge_ID_9317.h"

#include "inc-gen/Preliminary_DriveMode_ID_13768.h"

#include "inc-gen/DriveModeFusion_ID_13838.h"

#include "inc-gen/DrivingMode_ID_5723.h"

#include "inc-gen/Automatic_ID_12164.h"

#include "inc-gen/EngineMode_ID_9757.h"

#include "inc-gen/Manual_ID_6500.h"

#include "inc-gen/ThrottleFusion_ID_5874.h"

#include "inc-gen/Scale_ID_10083.h"

#include "inc-gen/DA_Plausibilization_Test_ID_10270.h"

#include "inc-gen/Max_Acceleration_ID_6878.h"

#include "inc-gen/Target_Velocity_ID_6883.h"

#include "inc-gen/Steering_Angle_ID_6888.h"

#include "inc-gen/merge_TurnOffs_ID_16204.h"

#include "inc-gen/Steering_Angle_Transformation_ID_5661.h"

#include "inc-gen/WritePlatoonFile_ID_20010.h"

#include "inc-gen/Transit_for_Testing_ID_45252.h"

#include "inc-gen/Speed_Change_ID_43293.h"

#include "inc-gen/Time_Change_ID_44217.h"

#include "inc-gen/EBRumble_ID_17138.h"

#include "inc-gen/Lane_Warning_Rumble_ID_17219.h"

#include "inc-gen/Lane_Keeping_Rumble_ID_30647.h"

#include "inc-gen/Coordinator_ID_29204.h"

#include "inc-gen/Deadzone_check_ID_7080.h"

#include "inc-gen/Max_Velocity_Diff_ID_7820.h"

#include "inc-gen/Boundaries_ID_7833.h"

#include "inc-gen/Boundary_check_ID_7172.h"

#include "inc-gen/OLD_Stopping_distances_comparison_ID_45136.h"

#include "inc-gen/Weight_Current_ID_73.h"

#include "inc-gen/Computation_ID_27.h"

#include "inc-gen/Weight_Current_ID_45058.h"

#include "inc-gen/Computation_ID_45034.h"

#include "inc-gen/NoVal_Checker_ID_47760.h"

#include "inc-gen/Velocity_Return_ID_31819.h"

#include "inc-gen/Rumble_Delay_ID_15596.h"

#include "inc-gen/VelocityMem_ID_11087.h"

#include "inc-gen/Mem_ID_12576.h"

#include "inc-gen/Prevent_cycle_ID_10366.h"

#include "inc-gen/Delay_ID_13898.h"

#include "inc-gen/Delay_ID_31910.h"

#include "inc-gen/Lane_Warning_ID_15516.h"

#include "inc-gen/EBOff_ID_17684.h"

#include "inc-gen/BlinkLeft_ID_19399.h"

#include "inc-gen/BlinkRight_ID_19411.h"

#include "inc-gen/Max_ACC_Velocity_ID_8163.h"

#include "inc-gen/ACC_Time_Gap_ID_44268.h"

#include "inc-gen/Last_Steering_ID_44992.h"

#include "inc-gen/Delay_ID_16983.h"

#include "inc-gen/History_ID_32.h"

#include "inc-gen/History_ID_45048.h"

#include "inc-gen/LastSensor_Memory_ID_7683.h"

#include "inc-gen/Velocity_Memory_ID_7729.h"

#include "inc-gen/Tick_Counter_ID_46205.h"

#include "inc-gen/TurnOffPlatooning_ID_46536.h"

#include "inc-gen/PlatoonInfoMem_ID_49039.h"

#include "inc-gen/TickCounter_ID_50455.h"

#include "inc-gen/Control_States_ID_45920.h"

#include "inc-gen/Error_Sum_ID_16094.h"

#include "inc-gen/Last_Error_ID_16099.h"

#include "inc-gen/Boundaries_active_ID_16338.h"

#include "inc-gen/Last_Street_Width_ID_29276.h"

extern GEN_TYPE_double DistanceToFrontUS1_ID_5278;

extern GEN_TYPE_boolean noval_DistanceToFrontUS1_ID_5278;

extern GEN_TYPE_double VelocityIn_ID_5264;

extern GEN_TYPE_boolean noval_VelocityIn_ID_5264;

extern GEN_TYPE_int ButtonY_ID_5257;

extern GEN_TYPE_boolean noval_ButtonY_ID_5257;

extern GEN_TYPE_int ButtonB_ID_5250;

extern GEN_TYPE_boolean noval_ButtonB_ID_5250;

extern GEN_TYPE_int ButtonA_ID_5243;

extern GEN_TYPE_boolean noval_ButtonA_ID_5243;

extern GEN_TYPE_int ButtonX_ID_5236;

extern GEN_TYPE_boolean noval_ButtonX_ID_5236;

extern GEN_TYPE_int ButtonR1_ID_5229;

extern GEN_TYPE_boolean noval_ButtonR1_ID_5229;

extern GEN_TYPE_double ButtonR2_ID_5222;

extern GEN_TYPE_boolean noval_ButtonR2_ID_5222;

extern GEN_TYPE_int ButtonL1_ID_5215;

extern GEN_TYPE_boolean noval_ButtonL1_ID_5215;

extern GEN_TYPE_double ButtonL2_ID_5208;

extern GEN_TYPE_boolean noval_ButtonL2_ID_5208;

extern GEN_TYPE_double LeftStick_X_ID_5201;

extern GEN_TYPE_boolean noval_LeftStick_X_ID_5201;

extern GEN_TYPE_double DistanceToFrontLaser_ID_5474;

extern GEN_TYPE_boolean noval_DistanceToFrontLaser_ID_5474;

extern GEN_TYPE_double RightStick_X_ID_6276;

extern GEN_TYPE_boolean noval_RightStick_X_ID_6276;

extern GEN_TYPE_double RightStick_Y_ID_6381;

extern GEN_TYPE_boolean noval_RightStick_Y_ID_6381;

extern GEN_TYPE_double DistanceToFrontObstacle_ID_10637;

extern GEN_TYPE_boolean noval_DistanceToFrontObstacle_ID_10637;

extern GEN_TYPE_boolean FrontObstacleCommand_ID_10644;

extern GEN_TYPE_boolean noval_FrontObstacleCommand_ID_10644;

extern GEN_TYPE_boolean Automatic_On_ID_12446;

extern GEN_TYPE_boolean noval_Automatic_On_ID_12446;

extern GEN_TYPE_double LeftStick_Y_ID_14558;

extern GEN_TYPE_boolean noval_LeftStick_Y_ID_14558;

extern GEN_TYPE_int ButtonHome_ID_14595;

extern GEN_TYPE_boolean noval_ButtonHome_ID_14595;

extern GEN_TYPE_int ButtonSelect_ID_14588;

extern GEN_TYPE_boolean noval_ButtonSelect_ID_14588;

extern GEN_TYPE_double LD_Orientation_ID_15746;

extern GEN_TYPE_boolean noval_LD_Orientation_ID_15746;

extern GEN_TYPE_boolean LD_present_left_ID_15732;

extern GEN_TYPE_boolean noval_LD_present_left_ID_15732;

extern GEN_TYPE_boolean LD_present_right_ID_15739;

extern GEN_TYPE_boolean noval_LD_present_right_ID_15739;

extern GEN_TYPE_double LD_Distance_Left_ID_15718;

extern GEN_TYPE_boolean noval_LD_Distance_Left_ID_15718;

extern GEN_TYPE_double LD_Distance_Right_ID_15725;

extern GEN_TYPE_boolean noval_LD_Distance_Right_ID_15725;

extern GEN_TYPE_double DistanceToFrontUS2_ID_16717;

extern GEN_TYPE_boolean noval_DistanceToFrontUS2_ID_16717;

extern GEN_TYPE_int DPadLeft_ID_18559;

extern GEN_TYPE_boolean noval_DPadLeft_ID_18559;

extern GEN_TYPE_int DPadRight_ID_18566;

extern GEN_TYPE_boolean noval_DPadRight_ID_18566;

extern GEN_TYPE_int DPadUp_ID_23935;

extern GEN_TYPE_boolean noval_DPadUp_ID_23935;

extern GEN_TYPE_int DPadDown_ID_23942;

extern GEN_TYPE_boolean noval_DPadDown_ID_23942;

extern GEN_TYPE_MessageNewLeader receiveNewLeader_ID_22788;

extern GEN_TYPE_boolean noval_receiveNewLeader_ID_22788;

extern GEN_TYPE_MessageFollower receiveFollowerMessage_ID_22802;

extern GEN_TYPE_boolean noval_receiveFollowerMessage_ID_22802;

extern GEN_TYPE_MessageFuse receiveFuse_ID_22795;

extern GEN_TYPE_boolean noval_receiveFuse_ID_22795;

extern GEN_TYPE_MessageLeaderHB receiveLeaderHB_ID_22823;

extern GEN_TYPE_boolean noval_receiveLeaderHB_ID_22823;

extern GEN_TYPE_MessageLeave receiveLeave_ID_22816;

extern GEN_TYPE_boolean noval_receiveLeave_ID_22816;

extern GEN_TYPE_MessagePlatoon receivePlatoonMessage_ID_22809;

extern GEN_TYPE_boolean noval_receivePlatoonMessage_ID_22809;

extern GEN_TYPE_MessageSplit receiveSplit_ID_22667;

extern GEN_TYPE_boolean noval_receiveSplit_ID_22667;

extern GEN_TYPE_MessageHandshake receiveHandshake_ID_29736;

extern GEN_TYPE_boolean noval_receiveHandshake_ID_29736;

extern GEN_TYPE_boolean LD_rover_detected_ID_31547;

extern GEN_TYPE_boolean noval_LD_rover_detected_ID_31547;

extern GEN_TYPE_int LD_rover_distance_ID_31540;

extern GEN_TYPE_boolean noval_LD_rover_distance_ID_31540;

extern GEN_TYPE_int LD_rover_id_ID_31533;

extern GEN_TYPE_boolean noval_LD_rover_id_ID_31533;

extern GEN_TYPE_boolean LD_curve_detected_ID_31526;

extern GEN_TYPE_boolean noval_LD_curve_detected_ID_31526;

extern GEN_TYPE_double LD_curve_radius_ID_31519;

extern GEN_TYPE_boolean noval_LD_curve_radius_ID_31519;

extern GEN_TYPE_boolean LD_server_connected_ID_31512;

extern GEN_TYPE_boolean noval_LD_server_connected_ID_31512;

extern GEN_TYPE_int LD_server_lastupdate_ID_31505;

extern GEN_TYPE_boolean noval_LD_server_lastupdate_ID_31505;

extern GEN_TYPE_int ButtonStart_ID_44386;

extern GEN_TYPE_boolean noval_ButtonStart_ID_44386;

extern GEN_TYPE_double MotorValue_ID_7314;

extern GEN_TYPE_boolean noval_MotorValue_ID_7314;

extern GEN_TYPE_double SteeringValue_ID_14149;

extern GEN_TYPE_boolean noval_SteeringValue_ID_14149;

extern GEN_TYPE_DriverAssistanceCommands DA_States_ID_11269;

extern GEN_TYPE_boolean noval_DA_States_ID_11269;

extern GEN_TYPE_double DistanceFrontOut_ID_11262;

extern GEN_TYPE_boolean noval_DistanceFrontOut_ID_11262;

extern GEN_TYPE_double VelocityFrontObstacleOut_ID_11255;

extern GEN_TYPE_boolean noval_VelocityFrontObstacleOut_ID_11255;

extern GEN_TYPE_double MaxAcceleration_ID_11234;

extern GEN_TYPE_boolean noval_MaxAcceleration_ID_11234;

extern GEN_TYPE_int Gear_ID_12464;

extern GEN_TYPE_boolean noval_Gear_ID_12464;

extern GEN_TYPE_double TargetVelocity_ID_11363;

extern GEN_TYPE_boolean noval_TargetVelocity_ID_11363;

extern GEN_TYPE_double VelocityValue_ID_14142;

extern GEN_TYPE_boolean noval_VelocityValue_ID_14142;

extern GEN_TYPE_DriveModeSettings DriveMode_ID_14070;

extern GEN_TYPE_boolean noval_DriveMode_ID_14070;

extern GEN_TYPE_boolean EB_On_ID_14065;

extern GEN_TYPE_boolean noval_EB_On_ID_14065;

extern GEN_TYPE_double SteeringAngle_ID_14169;

extern GEN_TYPE_boolean noval_SteeringAngle_ID_14169;

extern GEN_TYPE_int RumbleStrong_ID_17079;

extern GEN_TYPE_boolean noval_RumbleStrong_ID_17079;

extern GEN_TYPE_int RumbleWeak_ID_17086;

extern GEN_TYPE_boolean noval_RumbleWeak_ID_17086;

extern GEN_TYPE_int Red_Left_ID_19221;

extern GEN_TYPE_boolean noval_Red_Left_ID_19221;

extern GEN_TYPE_int Green_Left_ID_19228;

extern GEN_TYPE_boolean noval_Green_Left_ID_19228;

extern GEN_TYPE_int Blue_Left_ID_19235;

extern GEN_TYPE_boolean noval_Blue_Left_ID_19235;

extern GEN_TYPE_int Red_Right_ID_19242;

extern GEN_TYPE_boolean noval_Red_Right_ID_19242;

extern GEN_TYPE_int Green_Right_ID_19249;

extern GEN_TYPE_boolean noval_Green_Right_ID_19249;

extern GEN_TYPE_int Blue_Right_ID_19256;

extern GEN_TYPE_boolean noval_Blue_Right_ID_19256;

extern GEN_TYPE_MessagePlatoon sendPlatoonMessage_ID_22719;

extern GEN_TYPE_boolean noval_sendPlatoonMessage_ID_22719;

extern GEN_TYPE_MessageSplit sendSplit_ID_22691;

extern GEN_TYPE_boolean noval_sendSplit_ID_22691;

extern GEN_TYPE_MessageFollower sendFollowerMessage_ID_22712;

extern GEN_TYPE_boolean noval_sendFollowerMessage_ID_22712;

extern GEN_TYPE_MessageFuse sendFuse_ID_22705;

extern GEN_TYPE_boolean noval_sendFuse_ID_22705;

extern GEN_TYPE_MessageLeaderHB sendLeaderHB_ID_22733;

extern GEN_TYPE_boolean noval_sendLeaderHB_ID_22733;

extern GEN_TYPE_MessageLeave sendLeave_ID_22726;

extern GEN_TYPE_boolean noval_sendLeave_ID_22726;

extern GEN_TYPE_MessageNewLeader sendNewLeader_ID_22698;

extern GEN_TYPE_boolean noval_sendNewLeader_ID_22698;

extern GEN_TYPE_MessageHandshake sendHandshake_ID_31148;

extern GEN_TYPE_boolean noval_sendHandshake_ID_31148;

extern GEN_TYPE_int frontVehicleIDtoCodeGen_ID_31126;

extern GEN_TYPE_boolean noval_frontVehicleIDtoCodeGen_ID_31126;

extern GEN_TYPE_int leaderIDtoCodeGen_ID_31133;

extern GEN_TYPE_boolean noval_leaderIDtoCodeGen_ID_31133;

extern GEN_TYPE_double DistanceToFrontUS_2_ID_44351;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_2_ID_44351;

extern GEN_TYPE_double DistanceToFrontUS_1_ID_44358;

extern GEN_TYPE_boolean noval_DistanceToFrontUS_1_ID_44358;

extern GEN_TYPE_double ACC_TargetDistance_ID_44721;

extern GEN_TYPE_boolean noval_ACC_TargetDistance_ID_44721;

extern GEN_TYPE_double ACC_MaxVelocity_ID_44728;

extern GEN_TYPE_boolean noval_ACC_MaxVelocity_ID_44728;

extern GEN_TYPE_double ACC_TimeGap_ID_44735;

extern GEN_TYPE_boolean noval_ACC_TimeGap_ID_44735;

extern GEN_TYPE_double DistanceLaser_ID_44749;

extern GEN_TYPE_boolean noval_DistanceLaser_ID_44749;

extern GEN_TYPE_double Velocity_ID_44756;

extern GEN_TYPE_boolean noval_Velocity_ID_44756;

extern GEN_TYPE_boolean Critical_ID_44777;

extern GEN_TYPE_boolean noval_Critical_ID_44777;

extern GEN_TYPE_boolean ForceEBOff_ID_44833;

extern GEN_TYPE_boolean noval_ForceEBOff_ID_44833;

extern GEN_TYPE_double LD_Distance_Left_filtered_ID_45381;

extern GEN_TYPE_boolean noval_LD_Distance_Left_filtered_ID_45381;

extern GEN_TYPE_double LD_Distance_Right_filtered_ID_45227;

extern GEN_TYPE_boolean noval_LD_Distance_Right_filtered_ID_45227;

extern GEN_TYPE_double LD_Right_ID_45297;

extern GEN_TYPE_boolean noval_LD_Right_ID_45297;

extern GEN_TYPE_double LD_Left_ID_45304;

extern GEN_TYPE_boolean noval_LD_Left_ID_45304;

extern void clear_inputs_System_ID_4789();

extern void clear_outputs_System_ID_4789();

extern void init_System_ID_4789();

extern void perform_step_System_ID_4789();

#endif // __HEADER_System_ID_4789_h
