/* generated by AutoFOCUS 3 (2.14.0) on Fri Jul 05 17:37:26 CEST 2019 */
#ifndef __HEADER_VelocityDifference_ID_6918_h
#define __HEADER_VelocityDifference_ID_6918_h
#include "inc-gen/data_dictionary.h"

extern GEN_TYPE_double SampledDistanceFront_ID_17293;

extern GEN_TYPE_boolean noval_SampledDistanceFront_ID_17293;

extern GEN_TYPE_double LastDistanceFrontIn_ID_6974;

extern GEN_TYPE_boolean noval_LastDistanceFrontIn_ID_6974;

extern GEN_TYPE_double LastVelocityDiffIn_ID_7786;

extern GEN_TYPE_boolean noval_LastVelocityDiffIn_ID_7786;

extern GEN_TYPE_double LastDistanceFrontOut_ID_7704;

extern GEN_TYPE_boolean noval_LastDistanceFrontOut_ID_7704;

extern GEN_TYPE_double VelocityDiff_ID_7706;

extern GEN_TYPE_boolean noval_VelocityDiff_ID_7706;

extern GEN_TYPE_boolean InvalidValue_ID_7760;

extern GEN_TYPE_boolean noval_InvalidValue_ID_7760;

extern GEN_TYPE_double LastVelocityDiffOut_ID_7775;

extern GEN_TYPE_boolean noval_LastVelocityDiffOut_ID_7775;

extern void clear_inputs_VelocityDifference_ID_6918();

extern void clear_outputs_VelocityDifference_ID_6918();

extern void init_VelocityDifference_ID_6918();

extern void perform_step_VelocityDifference_ID_6918();

#endif // __HEADER_VelocityDifference_ID_6918_h
